### PR TITLE
Ignoring the ioda variable name convention changes for the time being.

### PR DESCRIPTION
**Pull request by guillaumevernieres**
- fixes  #280

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Looks like a similar issue that what you experienced earlier today @RussTreadon-NOAA ... Never simple.

**Comment by RussTreadon-NOAA** [comment]
The change to `CMakeLists.txt` has been tested on Orion and Hera within the global-workflow.  All ctests pass.   See #280 for details.

**Comment by RussTreadon-NOAA** [comment]
> Looks like a similar issue that what you experienced earlier today @RussTreadon-NOAA ... Never simple.

Agreed.   It's timing out trying to download files from ftp.emc.ncep.noaa.gov.   Urgh!

**Review by RussTreadon-NOAA — APPROVED** [review]
Automated and manual tests pass.  Approve!

**Comment by guillaumevernieres** [comment]
> > Looks like a similar issue that what you experienced earlier today @RussTreadon-NOAA ... Never simple.
> 
> Agreed. It's timing out trying to download files from ftp.emc.ncep.noaa.gov. Urgh!

all good now.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
