### PR TITLE
Add VADER and Update Modulefiles

### LINKED ISSUE #56: Add VADER and update modulefiles

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
Closes #56 

This PR adds VADER to the CMakeLists.txt for the pseudo bundle, adds vader/ to the .gitignore, and updates eckit and fckit module versions for Hera and Orion.

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
While, 
```
Orion-login-4[14] rtreadon$ module purge
Orion-login-4[15] rtreadon$ module use /work/noaa/da/Russ.Treadon/git/GDASApp/vader/modulefiles
Orion-login-4[16] rtreadon$ module load GDAS/orion
(gdasapp) Orion-login-4[17] rtreadon$
```
executes without error, `module list` shows the wrong eckit/ecmwf version
```
(gdasapp) Orion-login-4[17] rtreadon$ module list

Currently Loaded Modules:
  1) git/2.28.0          6) szip/2.1.1       11) jedi-impi/2020.2      16) eigen/3.3.7           21) cmake/3.22.1         26) hpc/1.2.0
  2) jedi-gcc/10.2.0     7) zlib/1.2.11      12) hdf5/1.12.0           17) bufr/noaa-emc-11.5.0  22) ecbuild/ecmwf-3.6.1  27) miniconda3/4.6.14
  3) intel/2020.2        8) udunits/2.2.28   13) pnetcdf/1.12.1        18) pybind11/2.7.0        23) eckit/ecmwf-1.16.0   28) gdasapp/1.0.0
  4) jedi-intel/2020.2   9) gsl_lite/0.37.0  14) netcdf/4.7.4          19) nccmp/1.8.7.0         24) fckit/ecmwf-0.9.5    29) GDAS/orion
  5) mkl/2020.2         10) impi/2020.2      15) boost-headers/1.68.0  20) pio/2.5.1-debug       25) atlas/ecmwf-0.29.0
```
Version 1.16.0 is loaded.  GDAS/orion specifies 1.18.2.  

Attempts to execute `build.sh` fail with
```
/apps/python-3.9.2/bin/python3: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
make[2]: *** [saber/src/saber/util/type_rng.F90] Error 127
make[2]: Leaving directory `/work/noaa/da/rtreadon/git/GDASApp/vader/build'
make[1]: *** [saber/src/saber/CMakeFiles/saber.dir/all] Error 2
make[1]: Leaving directory `/work/noaa/da/rtreadon/git/GDASApp/vader/build'
make: *** [all] Error 2
```

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA yes I'm experiencing the same behavior as you are... very strange.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , I've seen this before on Orion.   Pre-requisites for a module load unload a previously loaded module.    Perhaps a module load after  `eckit/ecmwf-1.18.2` unloads 1.18.2 and loads 1.16.0 instead.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA in fact, the `fckit` load seems to be what is doing it. Swapping the order does the trick. Will push the change now.

**Comment by RussTreadon-NOAA** [comment]
Orion build still fails after updating to c7bb062.  Here's the traceback

```
/apps/python-3.9.2/bin/python3: error while loading shared libraries: libpython\
3.9.so.1.0: cannot open shared object file: No such file or directory
make[2]: *** [saber/src/saber/util/type_rng.F90] Error 127
make[2]: Leaving directory `/work/noaa/da/rtreadon/git/GDASApp/vader/build'
make[1]: *** [saber/src/saber/CMakeFiles/saber.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA why is it using /apps/python-3.9.2/bin/python3? Something must not be right still with the modules.

**Comment by RussTreadon-NOAA** [comment]
The hack at [500a138](https://github.com/NOAA-EMC/GDASApp/pull/57/commits/500a138e1378a60db6f882a33c5a49780f9ac3e6) allows `build.sh` to run past the point of previous failures on Orion.   I'll let the build run to completion and execute ctests.

**Comment by RussTreadon-NOAA** [comment]
Orion build successfully ran to completion.   ctests begun.   Received _[Orion-login-3.HPC.MsState.Edu Arbiter2] New violation of usage policy by rtreadon_ email from Orion stating that I was overusing a login node.  Killed ctest.

**Review by RussTreadon-NOAA — APPROVED** [review]
Branch now builds on Orion.  Unable to successfully complete all ctests on interactive node.   Changes look to be straight forward.  Approve.

**Comment by RussTreadon-NOAA** [comment]
> Orion build successfully ran to completion. ctests begun. Received _[Orion-login-3.HPC.MsState.Edu Arbiter2] New violation of usage policy by rtreadon_ email from Orion stating that I was overusing a login node. Killed ctest.

FYI:  Relieved to receive a "normal status" email from Orion
```
Return to normal status
User rtreadon (Russ Treadon) has now returned to normal status (as of 15:16 on 06/01).

Continued excessive usage (beyond established thresholds) may result in lower limits (higher throttling) for longer periods of time. If you have not yet addressed the issues that caused your resources to be limited, your limits will be further reduced shortly.
```

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA that is odd, did the ecbuild command from the module not work properly? It should've specified to submit the MPI jobs to the batch queue automatically. But that is outside the scope of this PR, so I will merge now with your approval.

**Pull request merged**
