### PR TITLE
Improve consistency between GDASApp ATM jjob ctests and g-w

### LINKED ISSUE #475: Improve consistency between GDASApp and g-w ATM Var and Ens ctests and j-jobs
The following GDASApp ctests set up and execute g-w UFSDA ATM Var and Ens j-jobs
```
  Test #1480: test_gdasapp_setup_atm_cycled_exp
  Test #1481: test_gdasapp_atm_jjob_var_init
  Test #1482: test_gdasapp_atm_jjob_var_run
  Test #1483: test_gdasapp_atm_jjob_var_final
  Test #1484: test_gdasapp_atm_jjob_ens_init
  Test #1485: test_gdasapp_atm_jjob_ens_run
  Test #1486: test_gdasapp_atm_jjob_ens_final
```
Details regarding these ctests should be cleaned up
- directly use g-w `config.base.emc.dyn`.   g-w issue [#1618](https://github.com/NOAA-EMC/global-workflow/issues/1618) has been opened to introduce changes which make this possible.  The g-w issue requires corresponding changes be made on the GDASApp side.  This issue makes the first set of changes required to to use g-w `config.base.emc.dyn`.   A new GDASApp issue will be opened once the changes in g-w [#1618](https://github.com/NOAA-EMC/global-workflow/issues/1618) enter g-w `develop`.
- define `NETCDF` and `UTILROOT` in a manner consistent with g-w
- ensure greater consistency in terms of variables, logic, and scripting across GDASApp drivers for ATM Var and Ens j-job ctests

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
The files modified in this PR allow the user to directly use more g-w components in GDASApp ATM jjob ctests.   See GDASAPP issue #475 for details.

g-w PR [#1621](https://github.com/NOAA-EMC/global-workflow/pull/1621) contains g-w changes which work with the GDASApp changes in this PR.   The two PRs should be merged into their respective develops at about the same time.

Fixes #475

Note that correction of a bug in g-w PR [#1621](https://github.com/NOAA-EMC/global-workflow/pull/1621) causes the following GDASApp ctests to fail
```
The following tests FAILED:
        1449 - test_gdasapp_setup_cycled_exp (Failed)
        1463 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP (Failed)
        1464 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT (Failed)
        1465 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT_VRFY (Failed)
        1466 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN (Failed)
        1467 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT (Failed)
        1468 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST (Failed)
```
These ctests use C24 for the ensemble.  g-w does not support this resolution.

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
As reported in g-w issue [#1618](https://github.com/NOAA-EMC/global-workflow/issues/1618), the failed ctests specify an ensemble resolution of `resens=24`.   g-w does not support this resolution.   The same failed ctests specify an ensemble size of `nens=0`.   Given this, remove the ensemble resolution specification from the argument list passed to g-w `setup_expt.py`.  Specifically, two GDASApp files were modified as follows:

1) `test/setup_workflow_exp.sh`
```
@@ -10,7 +10,6 @@ app=ATM # NOTE make this S2SWA soon
 starttype='warm'
 gfscyc='4'
 resdet='48'
-resens='24'
 nens=0
 pslot='gdas_test'
 configdir=$srcdir/../../parm/config/gfs
@@ -24,6 +23,6 @@ rm -rf "${comrot}" "${expdir}"
 cd $srcdir/../../workflow

 echo "Running global-workflow experiment generation script"
-./setup_expt.py gfs cycled --idate $idate --edate $edate --app $app --start $starttype --gfs_cyc $gfscyc --resdet $resdet --resens $resens --n
ens $nens --pslot $pslot --configdir $configdir --comrot $comrot --expdir $expdir
+./setup_expt.py gfs cycled --idate $idate --edate $edate --app $app --start $starttype --gfs_cyc $gfscyc --resdet $resdet --nens $nens --pslot
 $pslot --configdir $configdir --comrot $comrot --expdir $expdir
```

2) `ush/soca/run_jjobs.py`

```
@@ -112,7 +112,6 @@ class JobCard:
             "start": "warm",
             "gfs_cyc": "0",
             "resdet": self.config['resdet'],
-            "resens": "24",
             "nens": "0",
             "pslot": "${PSLOT}",
             "configdir": "${PWD}/config/gfs",


 exit $?
```
A rerun of the ctests after making the above changes results in _Passed_ for the previous failing tests.
```
      Start 1449: test_gdasapp_setup_cycled_exp
11/49 Test #1449: test_gdasapp_setup_cycled_exp .............................   Passed    2.70 sec
      Start 1463: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
25/49 Test #1463: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP ........   Passed   46.36 sec
      Start 1464: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT
26/49 Test #1464: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT ........   Passed   75.42 sec
      Start 1465: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT_VRFY
27/49 Test #1465: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT_VRFY ...   Passed   42.93 sec
      Start 1466: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN
28/49 Test #1466: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN .........   Passed   43.59 sec
      Start 1467: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
29/49 Test #1467: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT .......   Passed   43.45 sec
      Start 1468: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST
30/49 Test #1468: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST ........   Passed   11.59 sec
```

In fact all 49 GDASApp ctests pass on Orion and Hera after making the above changes.

@guillaumevernieres , while removing `resens` from the argument list passed to `setup_expt.py` yields the desired ctest result, can we safely commit these changes to GDASApp?   I don't know all the use cases for `ush/soca/run_jjobs.py`.   I don't want the proposed change to cause problems in use cases outside of the ctests.

**Comment by guillaumevernieres** [comment]
Safe to commit @RussTreadon-NOAA , that's why we have ctests! Thanks again for fixing the marine stuff ...

**Comment by RussTreadon-NOAA** [comment]
> Safe to commit @RussTreadon-NOAA , that's why we have ctests! Thanks again for fixing the marine stuff ...

Thanks @guillaumevernieres .   Done at [ab5762a](https://github.com/NOAA-EMC/GDASApp/pull/476/commits/ab5762a2633295985c89d93e2718472cbf4269dd).

**Review by guillaumevernieres — DISMISSED** [review]
Looks good, thanks @RussTreadon-NOAA .

**Comment by RussTreadon-NOAA** [comment]
Thank you @guillaumevernieres for your approval.  Would you please re-approve.  I failed to make this an active PR.  You approved a draft. Sorry, my mistake.

**Comment by RussTreadon-NOAA** [comment]
> Thank you @guillaumevernieres for your approval. Would you please re-approve. I failed to make this an active PR. You approved a draft. Sorry, my mistake.

Wow, I learned something.  Changing a draft PR to Open does not remove prior approvals.   @guillaumevernieres , your initial approval remains.   Great!

**Comment by RussTreadon-NOAA** [comment]
g-w PR [#1621](https://github.com/NOAA-EMC/global-workflow/pull/1621) has been merged into g-w `develop`.   EIB requested g-w changes which require corresponding changes in `RussTreadon-NOAA:feature/atm_jjobs`.   These changes were committed at ec93446


GDASApp ctests were run from ec93446.    All 49 tests pass.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , this PR resolves the prototype cycling analysis resolution issue briefed during today's JEDI-T2O meeting.   EIB merged g-w PR [#1621](https://github.com/NOAA-EMC/global-workflow/pull/1621) into `develop`.   This GDASApp PR is now ready for review and, pending approval, merger into GDASApp `develop`.

**Review by CoryMartin-NOAA — APPROVED** [review]
Looks good to me, thanks @RussTreadon-NOAA

**Comment by CoryMartin-NOAA** [comment]
Given @guillaumevernieres 's previous approval, I will merge.

**Pull request merged**
