### PR TITLE
Enable the manual operation of the marine verification tool

### LINKED ISSUE #1314: marine post & vrfy bug fixes
#### 1. The ocean grid input file "ocngrid.nc" is missing and not properly copied/staged in the marine post task.

From the gdasocnanalvrfy.log:
```
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/scratch1/NCEPDEV/da/John.Steffen/expts/marine_candidate_092024/marine_candidate_092024/COMROOT/marine_candidate_092024/gdas.20210701/00/analysis/ocean/gdas.t21z.ocngrid.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'a7cdcd55-3299-4e6b-b1ee-07ec6b18a1a6']


FileNotFoundError: [Errno 2] No such file or directory: 
'/scratch1/NCEPDEV/da/John.Steffen/expts/marine_candidate_092024/marine_candidate_092024/COMROOT/marine_candidate_092024/gdas.20210701/00/analysis/ocean/gdas.t21z.ocngrid.nc'
```

- [x] Solution: 
Modify the /scripts/exgdas_global_marine_analysis_post.py script to uncomment the line that copies the soca_gridspec.nc file from the run directory to the COMROOT directory.

```
 post_file_list.append([os.path.join(anl_dir, 'soca_gridspec.nc'),
                        os.path.join(com_ocean_analysis, f'{RUN}.t{bcyc}z.ocngrid.nc')])
```

#### 2. Two variables are not defined in the marine_eva_post.py script: waterTemperature and salinity. See this previously reported issue here and the proposed fix: #1153 

- [x] Solution: Add the missed variables to the script

#### 3. Ice variable names are inconsistent between the netcdf files and the exgdas_global_marine_analysis_vrfy.py script (ie aicen vs. aice_h)

From the gdasocnanalvrfy.log:
```
"/scratch1/NCEPDEV/da/John.Steffen/global-workflow-082924-update/sorc/gdas.cd/scripts/exgdas_global_marine_analysis_vrfy.py", line 49, in plot_marine_vrfy
    ocnvrfyPlotter.plot()
  File "/scratch1/NCEPDEV/da/John.Steffen/global-workflow-082924-update/sorc/gdas.cd/ush/soca/soca_vrfy.py", line 292, in plot
    plotHorizontalSlice(self.config)
  File "/scratch1/NCEPDEV/da/John.Steffen/global-workflow-082924-update/sorc/gdas.cd/ush/soca/soca_vrfy.py", line 92, in plotHorizontalSlice
    slice_data = np.squeeze(data[variable])
  File "/scratch1/NCEPDEV/da/python/envs/eva/lib/python3.10/site-packages/xarray/core/dataset.py", line 1547, in __getitem__
    raise KeyError(
KeyError: "No variable named 'aicen'. Variables on the dataset include ['xaxis_1', 'yaxis_1', 'Time', 'aice_h', 'hi_h', 'hs_h']"
```

- [x] Solution: 
Modify the exgdas_global_marine_analysis_vrfy.py script to use correct/updated variable names (aice_h, hi_h, hs_h).
```
            plotConfig(grid_file=grid_file,
                       data_file=os.path.join(comout, f'{RUN}.t'+cyc+'z.ice.incr.nc'),
                       lats=np.arange(-60, 60, 10),
-                      variables_horiz={'aicen': [-0.2, 0.2],
-                                       'hicen': [-0.5, 0.5],
-                                       'hsnon': [-0.1, 0.1]},
+                      variables_horiz={'aice_h': [-0.2, 0.2],
+                                       'hi_h': [-0.5, 0.5],
+                                       'hs_h': [-0.1, 0.1]},


            plotConfig(grid_file=grid_file,
                       data_file=os.path.join(comout, f'{RUN}.t'+cyc+'z.iceana.nc'),
-                      variables_horiz={'aicen': [0.0, 1.0],
-                                       'hicen': [0.0, 4.0],
-                                       'hsnon': [0.0, 0.5]},
+                      variables_horiz={'aice_h': [0.0, 1.0],
+                                       'hi_h': [0.0, 4.0],
+                                       'hs_h': [0.0, 0.5]},
```

#### 4. The *bkgerr_stddev.nc file is not copied from the run directory to COMROOT.

From gdasocnanalpost.log:
```
OSError: unable to copy /scratch1/NCEPDEV/stmp2/John.Steffen/RUNDIRS/marine_candidate_092024/gdas.2021071400/gdasocnanal_00/ocean.bkgerr_stddev.inc.nc to /scratch1/NCEPDEV/da/John.Steffen/expts/marine_candidate_092024/marine_candidate_092024/COMROOT/marine_candidate_092024/gdas.20210714/00//analysis/ocean/gdas.t00z.ocn.bkgerr_stddev.nc
```

- [x] Solution:
Uncomment and modify the following lines in the exgdas_global_marine_analysis_post.py script.
```
post_file_list.append([os.path.join(anl_dir, f'ocean.bkgerr_stddev.nc'),
                           os.path.join(com_ocean_analysis, f'{RUN}.t{cyc}z.{domain}.bkgerr_stddev.nc')])
```

#### 5. Some of the other stats *.nc files are missing

From gdasocnanalvrfy.log:
```
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/scratch1/NCEPDEV/da/John.Steffen/expts/marine_candidate_092024/marine_candidate_092024/COMROOT/marine_candidate_092024/gdas.20210718/00/analysis/ocean/gdas.t00z.ocn.ssh_steric_stddev.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '4064cbe5-094a-4545-90a7-05261ef2648b']
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/scratch1/NCEPDEV/da/John.Steffen/expts/marine_candidate_092024/marine_candidate_092024/COMROOT/marine_candidate_092024/gdas.20210718/00/analysis/ocean/gdas.t00z.ocn.ssh_total_stddev.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'f3e07b76-bc45-4f50-b726-93ec119ff62b']
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/scratch1/NCEPDEV/da/John.Steffen/expts/marine_candidate_092024/marine_candidate_092024/COMROOT/marine_candidate_092024/gdas.20210718/00/analysis/ocean/gdas.t00z.ocn.recentering_error.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'b15dcb30-3e5d-4b7e-9305-d88764ca07b3']


FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/NCEPDEV/da/John.Steffen/expts/marine_candidate_092024/marine_candidate_092024/COMROOT/marine_candidate_092024/gdas.20210718/00/analysis/ocean/gdas.t00z.ocn.ssh_unbal_stddev.nc'
FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/NCEPDEV/da/John.Steffen/expts/marine_candidate_092024/marine_candidate_092024/COMROOT/marine_candidate_092024/gdas.20210718/00/analysis/ocean/gdas.t00z.ocn.steric_explained_variance.nc'
```

- [x] the solution : add the trap or conditions in order to pass these inexsited nc files

#### 6. Marine vrfy task is hanging and reaching the wall clock limit.

From gdasocnanalvrfy.log:
```/scratch1/NCEPDEV/da/python/envs/eva/lib/python3.10/site-packages/cartopy/io/__init__.py:241: DownloadWarning: Downloading: https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_coastline.zip
  warnings.warn(f'Downloading: {url}', DownloadWarning)
slurmstepd: error: *** JOB 482666 ON h34m28 CANCELLED AT 2024-10-03T18:35:59 DUE TO TIME LIMIT ***
```

- [x] Possible solutions:
Job is hanging during downloading the cartopy raster and shapefiles for coastlines. Instead, copy these files to the common folder and point to them inside the soca_vrfy.py script.

#### 7. The gdassoca_obsstats is failing during the marine post task, likely related to the in situ obs statistics

From the gdasocnanalpost.log:
```
2024-10-03 10:57:21,534 - WARNING  - root        : srun -l --export=ALL -n 1 /scratch1/NCEPDEV/da/John.Steffen/global-workflow-082924-update/sorc/gdas.cd/build/bin/gdassoca_obsstats.x diag_stats.yaml has failed exit 1
```

- [x] Solution:
The gdassoca_obsstats executable needs the ocean basin name to be defined

### LINKED ISSUE #1345: Write a simple driver for the verify application
Start with something simple like this (untested):

```bash
#!/bin/bash

# Check if the right number of arguments is passed
if [ "$#" -ne 7 ]; then
    echo "Usage: $0 COM_OCEAN_ANALYSIS COM_ICE_HISTORY_PREV COM_OCEAN_HISTORY_PREV cyc RUN HOMEgfs"
    exit 1
fi

# Assign command-line arguments to environment variables
export COM_OCEAN_ANALYSIS=$1
export COM_ICE_HISTORY_PREV=$2
export COM_OCEAN_HISTORY_PREV=$3
export cyc=$4
export RUN=$5
export HOMEgfs=$6

# Optional: Print the environment variables for debugging purposes
echo "COM_OCEAN_ANALYSIS=${COM_OCEAN_ANALYSIS}"
echo "COM_ICE_HISTORY_PREV=${COM_ICE_HISTORY_PREV}"
echo "COM_OCEAN_HISTORY_PREV=${COM_OCEAN_HISTORY_PREV}"
echo "cyc=${cyc}"
echo "RUN=${RUN}"
echo "HOMEgfs=${HOMEgfs}"

# Run the Python utility script
python3 /pathto/exgdas_global_marine_analysis_vrfy.py
```
then figure out how to sbatch that task without the failures that @JohnSteffen-NOAA reported.

### LINKED ISSUE #1349: Cosmetic adjustment to the verify task
Summary of the "review" panel.

## State space figures
- [x] colorbars need to have the bounds as labels
- [x] use "pcolor" instead of contourf  for the horizontal plots
- [x] fill continent
- [ ] ~~use long name for the variables (low priority)~~
- [x] figure out the missing variables for None None None in the title
- [x] Missing units
- [x] Colormap should go from Blue to Red

### Increment
- [x] missing ocean incr
- [x] global seaice figure are wrong

### Backgrounds/Analysis
- [x] global figures are not correct
- [x] color scales for ice and snow depth are swapped: use [0, 4m] hor hice and [0, 0.5m] for hsnow
- [x] try [33, 41] psu for salinity
- [x] missing horizontal and meridional sections 

### Background error
- [x] skip the ensemble stuff if the files are not present, it's currently failing

### Background Error Location
- [x] point the `gdas.t00z.ocean.bkgerr_stddev.nc` file out under bmatrix/ocean from `comout`

## Obs space figures (EVA)
- [x] size of scatter dots is too large
- [x] check how to plot passive obs, color scales are wrong for omb's

### PR DESCRIPTION
**Pull request by apchoiCMD**
#### This PR enables the Marine Verification Tool to run outside of the g-w CI workflow by submitting an `sbatch` job manually on Hera

Includes,
- Vrfy task run by a simple driver in the offline #1345 
- Improve cosmetic issues we found #1349 
- Bug fixes and more #1314 
- Move `scripts/old/exgdas_global_marine_analysis_vrfy.py` to old directory

Most up-to-date plots can be found at
```
/scratch1/NCEPDEV/da/Mindo.Choi/sandbox/marine_vrfy/gdas.20210827/00/analysis/ocean/vrfy
```

The wall time is as follows:
```
[Mindo.Choi@hfe02 vrfy]$ sacct -j 2477688 --format=JobID,JobName,State,ExitCode,Elapsed
JobID           JobName      State ExitCode    Elapsed
------------ ---------- ---------- -------- ----------
2477688      marine_vr+  COMPLETED      0:0   00:11:54
2477688.bat+      batch  COMPLETED      0:0   00:11:54
2477688.ext+     extern  COMPLETED      0:0   00:11:54
```

Additional plotting work will be added by consolidating vrfy task as follows:
- SST/SSH time series
- Omb time series
- Spatial SSH/SST/OHC
- HTML (?)

Close #1314 , Close #1345 , Close #1349

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@apchoiCMD , you need to rebase properly or start fresh from the most recent version of develop. What you submitted has conflict(s) and is out of sync with develop.

**Comment by apchoiCMD** [comment]
> @apchoiCMD , you need to rebase properly or start fresh from the most recent version of develop. What you submitted has conflict(s) and is out of sync with develop.

Yep, I am thinking about how to properly rebase it now, I will start fresh from the develop, Thanks!

**Comment by guillaumevernieres** [comment]
That doesn't look right @apchoiCMD . You are trying to updated submodules and atmos files ... Why not just start fresh from develop and just add what's required for your PR?

**Comment by apchoiCMD** [comment]
> That doesn't look right @apchoiCMD . You are trying to updated submodules and atmos files ... Why not just start fresh from develop and just add what's required for your PR?

OK, I am doing again with fresh new-

**Pull request closed without merging**
