### PR TITLE
Feature/add ozone obs

### LINKED ISSUE #77: Add initial YAML files for ozone observations
- [x] omi_aura
- [x] ompsnp_npp
- [x] ompstc8_npp

### PR DESCRIPTION
**Pull request by joshk24**
Closes #77 

I forgot to push/pull when i did the aircraft, sfcship files, so those are included in this request. Currently aircraft and omi_aura are generating plots, ran into an issue with sfcship (not related to my changes, this is the other issue i commented on earlier) ... feel free to scrap that part of my request if necessary!

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@joshk24 aircraft should already be in the repository, through #67 ... this PR should only add ozone if that is what the title says, but it is fine to include others (if they are working), just modify the title.

**Comment by joshk24** [comment]
ompsnp_jvg
ompsnp_omb
ompstc_jvg
ompstc_omb

**Comment by CoryMartin-NOAA** [comment]
Finally! Something looks terrible... lol. This is fine, it's something we need to flag/investigate, but wow are these O3 datasets wrong.

**Comment by CoryMartin-NOAA** [comment]
I bet this is something wrong with units, but this isn't a problem for this PR, since the point of this is 'can it run' not 'is it correct'.

**Review by CoryMartin-NOAA — APPROVED** [review]
Changes here look good to me, now we can run ozone observations in GDASApp! Which is important because now we need to know why the results look so bad...

**Review by CatherineThomas-NOAA — APPROVED** [review]
While the scatterplots leave a lot to be desired... the code changes are fine.  Approved.

**Pull request merged**
