### PR TITLE
Update YAMLs for time window section

### LINKED ISSUE #759: Change YAMLs for new window section
When JCSDA coordinates their merge of repos (Dec 7 currently?) we will need to update our YAML templates. 

The new format should look like:
```
time window:
  begin: <start datetime>
  length|end: <length|end datetime>
  bound to include: <begin|end (default)>
```

### PR DESCRIPTION
**Pull request by ShastriPaturi**
PR for updating YAMLs for the time window section.

close #759

### CODE REVIEW

**Review by CoryMartin-NOAA — DISMISSED** [review]
Thanks Shastri! What about land? :-) We can ask Jiarui if need be.

**Comment by ShastriPaturi** [comment]
> Thanks Shastri! What about land? :-) We can ask Jiarui if need be.

@CoryMartin-NOAA I will do it, since I started. I will add it here and will re-request your review.

**Comment by ShastriPaturi** [comment]
@CoryMartin-NOAA is the list now complete?

**Review by CoryMartin-NOAA — APPROVED** [review]
Thanks @ShastriPaturi !!

**Comment by CoryMartin-NOAA** [comment]
This is now being merged into the JEDI repositories. Will merge here too.

**Pull request merged**
