### PR TITLE
Point the CI to the dev/gdasapp global workflow branch

### LINKED ISSUE #1168: Use the dev/gdasapp global-worflow branch for the CI test

### PR DESCRIPTION
**Pull request by guillaumevernieres**
- fixes #1168 

I have not touched the "stable" script, this is just to change the CI to point to `dev/gdsaapp`. 

I'll work next on fixing the gw_ci test, for some reason the hpc account is not updated properly. But in the meantime, the plan is to do bushiness as usual with a different branch.

### CODE REVIEW

**Review by RussTreadon-NOAA — DISMISSED** [review]
Approve

**Comment by guillaumevernieres** [comment]
> Approve

Thanks @RussTreadon-NOAA . I should have done that before submitting this PR: I'm going to update the README as well ...

**Review by CoryMartin-NOAA — DISMISSED** [review]

**Review by danholdaway — DISMISSED** [review]

**Comment by RussTreadon-NOAA** [comment]
I manually ran `gw_driver.sh` as role.jedipara on Hera.  It ran to completion for this PR, #1169, and finished with the following command line output in the Hera PuTTY session
```
+ /scratch1/NCEPDEV/da/role.jedipara/CI/GDASApp/repo/ci/run_gw_ci.sh -d /scratch1/NCEPDEV/da/role.jedipara/CI/GDASApp/workflow/PR/1169/global-workflow -o /scratch1/NCEPDEV/da/role.jedipara/CI/GDASApp/workflow/PR/1169/output_e0c4c8e
Begin link_workflow.sh at Wed Jun 12 18:49:43 UTC 2024
End link_workflow.sh at 18:49:43 with error code 0 (time elapsed: 00:00:00)
+ ci_status=0
+ gh pr comment 1169 --body-file /scratch1/NCEPDEV/da/role.jedipara/CI/GDASApp/workflow/PR/1169/output_e0c4c8e
https://github.com/NOAA-EMC/GDASApp/pull/1169#issuecomment-2163735457
+ '[' 0 -eq 0 ']'
+ gh pr edit 1169 --remove-label hera-GW-RT-Running --add-label hera-GW-RT-Passed
https://github.com/NOAA-EMC/GDASApp/pull/1169
+ find /scratch1/NCEPDEV/da/role.jedipara/CI/GDASApp/workflow/PR/1169 -maxdepth 1 -mtime +3 -exec rm -rf '{}' ';'
```

Looks like CI from role.jedipara works.  I have not yet enabled a cron to run CI in the background.  The above test was executed from the command line.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA perhaps tomorrow morning we coordinate turning it on for jedipara and off for my account, and we see how it goes tomorrow and Friday?

**Comment by guillaumevernieres** [comment]
@CoryMartin-NOAA , @RussTreadon-NOAA , @danholdaway I added some logic to check for a companion pr in the global-workflow and clone that if it does exist. I only tested a small chunk of the added script, running the ci again now.

**Comment by guillaumevernieres** [comment]
Note for tomorrow: check that the g-w and gdasapp branches that were checked out is the correct ones.

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres @RussTreadon-NOAA FYI I'm going to be on leave until Thursday so I won't be able to help debug the CI running in my user account. I'm going to revert it to develop again, just so existing capabilities are not broken. Debugging can happen on the role account if necessary.

**Comment by RussTreadon-NOAA** [comment]
**Hera test**
Did the following as role.jedipara
1. clone `feature/devgdasapp`
2. `cp ci/gw_driver.sh /scratch1/NCEPDEV/da/role.jedipara/CI/GDASApp/repo/ci`
3. create forked g-w branch named [`feature/ci`](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/ci) to match the same branch name, [`feature/ci`](https://github.com/RussTreadon-NOAA/GDASApp/tree/feature/ci), referenced by GDASApp PR [#1173](https://github.com/NOAA-EMC/GDASApp/pull/1173)
4. [add label](https://github.com/NOAA-EMC/GDASApp/pull/1173#event-13164263946) _hera-GW-RT_ to GDASApp PR [#1173](https://github.com/NOAA-EMC/GDASApp/pull/1173)
5. execute `/scratch1/NCEPDEV/da/role.jedipara/CI/GDASApp/repo/ci/gw_driver.sh -t hera`
6. 48 our of 48 test_gdasapp pass
7. PR [#1173](https://github.com/NOAA-EMC/GDASApp/pull/1173) [label updated](https://github.com/NOAA-EMC/GDASApp/pull/1173#issuecomment-2168655075) to _hera-GW-RT-Passed_

**Comment by RussTreadon-NOAA** [comment]
Changes in `feature/devgdasapp` have been merged into `RussTreadon-NOAA:feature/ci`.  See PR #1173

**Comment by guillaumevernieres** [comment]
Changes included in #1173

**Pull request closed without merging**
