### PR TITLE
Add in a C++ linter

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
@guillaumevernieres hates lint! So let's clean this place up a bit and keep it tidy! We already do this for python, extending it to C++ for the utilities directory.

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
The irony that the C++ linter script fails the python norms!

**Comment by guillaumevernieres** [comment]
Thanks @CoryMartin-NOAA !

**Review by guillaumevernieres — DISMISSED** [review]
nice and clean :+1:

**Review by AndrewEichmann-NOAA — APPROVED** [review]
Looks reasonable. I wonder what lessons are in store from this....

**Pull request merged**
