### PR TITLE
fixing directory assignment bug

### PR DESCRIPTION
**Pull request by AndrewEichmann-NOAA**
Addresses https://github.com/NOAA-EMC/GDASApp/issues/477

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Sorry for only noticing now @AndrewEichmann-NOAA , but the changes need to be in the `global-workflow` here:  
https://github.com/NOAA-EMC/global-workflow/blob/4bebafd61d5a0fc2f52910294204af5f1f51cb21/jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY#L19

I made a naming convention mistake a while back, I'm not sure why that one wasn't noticed. 
I forgot the `_PREV` for ice and ocean. It should have been something like this:
```bash
RUN=${GDUMP} YMD=${gPDY} HH=${gcyc} generate_com -rx COM_OCEAN_HISTORY_PREV:COM_OCEAN_HISTORY_TMPL
```

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Ok, I'll reverse it. what's the difference between *_PREV and not *_PREV?

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Ok, I'll make the change in g-w

**Comment by AndrewEichmann-NOAA** [comment]
To be fixed with https://github.com/NOAA-EMC/global-workflow/pull/1631

**Pull request closed without merging**
