### PR TITLE
update build_all.sh argument list

### LINKED ISSUE #1427: Update g-w build_all.sh
g-w PR [#3186](https://github.com/NOAA-EMC/global-workflow/pull/3186) modified the argument list for `build_all.sh`.  

```
Builds all of the global-workflow components by calling the individual build scripts in parallel.

Usage: ./build_all.sh [-a UFS_app][-c build_config][-d][-f][-h][-v] [gfs] [gefs] [sfs] [gsi] [gdas] [all]
  -a UFS_app:
    Build a specific UFS app instead of the default.  This will be applied to all UFS (GFS, GEFS, SFS) builds.
  -d:
    Build in debug mode
  -f:
    Build the UFS model(s) using the -DFASTER=ON option.
  -h:
    Print this help message and exit
  -k:
    Kill all builds if any build fails
  -v:
    Execute all build scripts with -v option to turn on verbose where supported

  Specified systems (gfs, gefs, sfs, gsi, gdas) are non-exclusive, so they can be built together.
```

g-w PR [#3186](https://github.com/NOAA-EMC/global-workflow/pull/3186)  was merged into g-w develop at [`d85214d`](https://github.com/NOAA-EMC/global-workflow/commit/d85214db1683848019d67815c63dc663c6049ec5).

GDASApp uses `build_all.sh` in two files
- `ci/run_ci.sh`
- `prototypes/gen_prototype.sh`

This issue is opened to document and make the required updates to `build_all.sh`

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
# Description

This PR updates the argument list for `build_all.sh` to be consistent with g-w PR [#3186](https://github.com/NOAA-EMC/global-workflow/pull/3186) which was merged into g-w `develop` on  12/24/2024.

Two files are modified
```
ci/run_ci.sh
prototypes/gen_prototype.sh
```

# Companion PRs

None

# Issues

Resolves #1427

# Automated CI tests to run in Global Workflow

- [ ] atm_jjob 
- [ ] C96C48_ufs_hybatmDA 
- [ ] C96C48_hybatmaerosnowDA  
- [ ] C48mx500_3DVarAOWCDA 
- [ ] C48mx500_hybAOWCDA 
- [ ] C96C48_hybatmDA

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Attention @DavidNew-NOAA :  I have an [open question](https://github.com/NOAA-EMC/GDASApp/issues/1427#issuecomment-2562647522) regarding whether or not we need to retain directory `prototypes` and its contents.  It does not appear that we actively use this directory.  

I updated `build_all.sh` in `prototypes/gen_prototype.sh` so we could 
1. go ahead and merge this PR into `develop` and address the `prototypes` question later, or
2. remove `prototypes` as part of this PR pending agreement from DA staff

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA If this directory is not in use, I'm more than happy for it to be gotten rid of. However, I think we should get feedback from DA staff first, and too many of them are on leave. I wouldn't let it hold up this PR.

**Comment by RussTreadon-NOAA** [comment]
Agreed.  We can merge these changes and circle back regarding what to do with `prototypes`.

**Review by DavidNew-NOAA — APPROVED** [review]
Straightforward changes

**Pull request merged**
