### PR TITLE
restore test_gdasapp_atm_jjob functionality

### LINKED ISSUE #980: test_gdasapp_atm_jjob_var failures
Clone [afe874e](https://github.com/NOAA-EMC/global-workflow/commit/afe874ee8b28942e459796cd1005ec598458a5b7) g-w with [e029bd7](https://github.com/NOAA-EMC/GDASApp/commit/e029bd76095b5604f0d8cceb000f1d7c86e7530f) GDASApp.   Build GDASApp within g-w on Orion.  Execute `ctest -R test_gdasapp`.  12 out of 54 tests fail.  The failed jobs are
```
        1752 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP (Failed)
        1753 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT (Failed)
        1754 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN (Failed)
        1757 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT (Failed)
        1758 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST (Failed)
        1759 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY (Failed)
        1760 - test_gdasapp_soca_socahybridweights (Failed)
        1761 - test_gdasapp_soca_incr_handler (Failed)
        1762 - test_gdasapp_soca_ens_handler (Failed)
        1771 - test_gdasapp_atm_jjob_var_init (Failed)
        1772 - test_gdasapp_atm_jjob_var_run (Failed)
        1773 - test_gdasapp_atm_jjob_var_final (Failed)
```
Open this issue to document _Failed_ tests and work toward restoring these tests to _Passed_.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
`test_gdasapp_atm_jjob` tests fail due to inconsistencies between the GDASApp tests and recent g-w updates.   This PR restores _Passed_ result for `test_gdasapp_atm_jjob`.

Fixes #980

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
The orion-GW-RT behavior for this PR mimics that of PR #928 minus the test_gdasapp_atm_jjob and test_gdasapp_aero_gen_3dvar_yaml  job failures.

**Comment by RussTreadon-NOAA** [comment]
The modifications in this PR **do not work** when I build GDASApp inside g-w `develop` at [03ba78ae](https://github.com/NOAA-EMC/global-workflow/commit/03ba78ae3df589211d2776254c6e8584ecdc226f).  

Revert this PR to draft until this is resolved.

**Comment by RussTreadon-NOAA** [comment]
Below is the traceback from the failed `test_gdasapp_atm_jjob_var_init`
```
^[[38;5;39m2024-03-21 18:08:36,376 - DEBUG    - analysis    : ( <pygfs.task.atm_analysis.AtmAnalysis object at 0x2b654c0db810> )^[[\
0m
^[[38;21m2024-03-21 18:08:36,376 - INFO     - analysis    : Generate JEDI YAML config: /work2/noaa/da/rtreadon/git/global-workflow/\
pr928/sorc/gdas.cd/build/gdas/test/atm/global-workflow/testrun/RUNDIRS/gdas_test/gdasatmanl_18/gdas.t18z.atmvar.yaml^[[0m
Traceback (most recent call last):
  File "/work2/noaa/da/rtreadon/git/global-workflow/pr928/scripts/exglobal_atm_analysis_initialize.py", line 24, in <module>
    AtmAnl.initialize()
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/wxflow/logger.py", line 266, in w\
rapper
    retval = func(*args, **kwargs)
  File "/work2/noaa/da/rtreadon/git/global-workflow/pr928/ush/python/pygfs/task/atm_analysis.py", line 71, in initialize
    super().initialize()
  File "/work2/noaa/da/rtreadon/git/global-workflow/pr928/ush/python/pygfs/task/analysis.py", line 36, in initialize
    self.task_config.jedi_config = self.get_jedi_config()
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/wxflow/logger.py", line 266, in w\
rapper
    retval = func(*args, **kwargs)
  File "/work2/noaa/da/rtreadon/git/global-workflow/pr928/ush/python/pygfs/task/analysis.py", line 64, in get_jedi_config
    jedi_config = parse_j2yaml(self.task_config.JEDIYAML, self.task_config, searchpath=self.gdasapp_j2tmpl_dir)
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/wxflow/yaml_file.py", line 180, i\
n parse_j2yaml
    return YAMLFile(data=Jinja(path, data, searchpath=searchpath).render)
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/wxflow/yaml_file.py", line 37, in\
 __init__
    self.update(config)
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/wxflow/attrdict.py", line 120, in\
 update
    other.update(args[0])
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by RussTreadon-NOAA** [comment]
Don't fully understand what's going on but a clean install from the top yields _Passed_ for `test_gdasapp_atm_jjob`. 
```
Test project /work2/noaa/da/rtreadon/git/global-workflow/pr928/sorc/gdas.cd/build
      Start 1389: test_gdasapp_util_coding_norms
 1/54 Test #1389: test_gdasapp_util_coding_norms ........................   Passed    1.32 sec
      Start 1390: test_gdasapp_util_ioda_example
 2/54 Test #1390: test_gdasapp_util_ioda_example ........................   Passed    9.56 sec
      Start 1391: test_gdasapp_util_prepdata
 3/54 Test #1391: test_gdasapp_util_prepdata ............................   Passed    1.21 sec
      Start 1392: test_gdasapp_util_rads2ioda
 4/54 Test #1392: test_gdasapp_util_rads2ioda ...........................   Passed    0.74 sec
      Start 1393: test_gdasapp_util_ghrsst2ioda
 5/54 Test #1393: test_gdasapp_util_ghrsst2ioda .........................   Passed    0.18 sec
      Start 1394: test_gdasapp_util_smap2ioda
 6/54 Test #1394: test_gdasapp_util_smap2ioda ...........................   Passed    0.14 sec
      Start 1395: test_gdasapp_util_smos2ioda
 7/54 Test #1395: test_gdasapp_util_smos2ioda ...........................   Passed    0.17 sec
      Start 1396: test_gdasapp_util_viirsaod2ioda
 8/54 Test #1396: test_gdasapp_util_viirsaod2ioda .......................   Passed    0.13 sec
      Start 1397: test_gdasapp_util_icecamsr2ioda
 9/54 Test #1397: test_gdasapp_util_icecamsr2ioda .......................   Passed    0.13 sec
      Start 1733: test_gdasapp_check_python_norms
10/54 Test #1733: test_gdasapp_check_python_norms .......................   Passed    1.53 sec
      Start 1734: test_gdasapp_check_yaml_keys
11/54 Test #1734: test_gdasapp_check_yaml_keys ..........................   Passed    0.09 sec
      Start 1735: test_gdasapp_jedi_increment_to_fv3
12/54 Test #1735: test_gdasapp_jedi_increment_to_fv3 ....................   Passed    0.73 sec
      Start 1736: test_gdasapp_convert_ewok_yaml
13/54 Test #1736: test_gdasapp_convert_ewok_yaml ........................   Passed    0.18 sec
      Start 1737: test_gdasapp_setup_cycled_exp
14/54 Test #1737: test_gdasapp_setup_cycled_exp .........................   Passed    0.43 sec
      Start 1738: test_gdasapp_fv3jedi_jediinc2fv3
15/54 Test #1738: test_gdasapp_fv3jedi_jediinc2fv3 ......................   Passed    3.82 sec
      Start 1739: test_gdasapp_convert_bufr_temp_dbuoy
16/54 Test #1739: test_gdasapp_convert_bufr_temp_dbuoy ..................   Passed    2.94 sec
      Start 1740: test_gdasapp_convert_bufr_salt_dbuoy
17/54 Test #1740: test_gdasapp_convert_bufr_salt_dbuoy ..................   Passed    0.20 sec
      Start 1741: test_gdasapp_convert_bufr_temp_mbuoyb
18/54 Test #1741: test_gdasapp_convert_bufr_temp_mbuoyb .................   Passed    0.19 sec
      Start 1742: test_gdasapp_convert_bufr_salt_mbuoyb
19/54 Test #1742: test_gdasapp_convert_bufr_salt_mbuoyb .................   Passed    0.20 sec
      Start 1743: test_gdasapp_convert_bufr_tesacprof
20/54 Test #1743: test_gdasapp_convert_bufr_tesacprof ...................   Passed    0.21 sec
      Start 1744: test_gdasapp_convert_bufr_trkobprof
21/54 Test #1744: test_gdasapp_convert_bufr_trkobprof ...................   Passed    0.19 sec
      Start 1745: test_gdasapp_convert_bufr_sfcships
22/54 Test #1745: test_gdasapp_convert_bufr_sfcships ....................   Passed    0.20 sec
      Start 1746: test_gdasapp_convert_bufr_sfcshipsu
23/54 Test #1746: test_gdasapp_convert_bufr_sfcshipsu ...................   Passed    0.19 sec
      Start 1747: test_gdasapp_soca_nsst_increment_to_mom6
24/54 Test #1747: test_gdasapp_soca_nsst_increment_to_mom6 ..............   Passed   28.65 sec
      Start 1748: test_gdasapp_soca_prep
25/54 Test #1748: test_gdasapp_soca_prep ................................   Passed    3.80 sec
      Start 1749: test_gdasapp_soca_run_clean
26/54 Test #1749: test_gdasapp_soca_run_clean ...........................   Passed    0.02 sec
      Start 1750: test_gdasapp_soca_setup_obsprep
27/54 Test #1750: test_gdasapp_soca_setup_obsprep .......................   Passed    3.67 sec
      Start 1751: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS
28/54 Test #1751: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS ..............   Passed   42.80 sec
      Start 1752: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
29/54 Test #1752: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP ....***Failed   42.25 sec
      Start 1753: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT
30/54 Test #1753: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT ....***Failed   44.01 sec
      Start 1754: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN
31/54 Test #1754: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN .....***Failed   42.21 sec
      Start 1755: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_ECEN
32/54 Test #1755: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_ECEN ....   Passed   42.20 sec
      Start 1756: test_gdasapp_soca_copy_scratch
33/54 Test #1756: test_gdasapp_soca_copy_scratch ........................   Passed    0.77 sec
      Start 1757: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
34/54 Test #1757: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT ...***Failed   42.21 sec
      Start 1758: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST
35/54 Test #1758: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST ....***Failed   10.19 sec
      Start 1759: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY
36/54 Test #1759: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY ....***Failed   74.19 sec
      Start 1760: test_gdasapp_soca_socahybridweights
37/54 Test #1760: test_gdasapp_soca_socahybridweights ...................***Failed   42.18 sec
      Start 1761: test_gdasapp_soca_incr_handler
38/54 Test #1761: test_gdasapp_soca_incr_handler ........................***Failed   10.16 sec
      Start 1762: test_gdasapp_soca_ens_handler
39/54 Test #1762: test_gdasapp_soca_ens_handler .........................***Failed   11.52 sec
      Start 1763: test_gdasapp_snow_create_ens
40/54 Test #1763: test_gdasapp_snow_create_ens ..........................   Passed    1.25 sec
      Start 1764: test_gdasapp_snow_imsproc
41/54 Test #1764: test_gdasapp_snow_imsproc .............................   Passed    4.00 sec
      Start 1765: test_gdasapp_snow_apply_jediincr
42/54 Test #1765: test_gdasapp_snow_apply_jediincr ......................   Passed    6.84 sec
      Start 1766: test_gdasapp_snow_letkfoi_snowda
43/54 Test #1766: test_gdasapp_snow_letkfoi_snowda ......................   Passed    9.15 sec
      Start 1767: test_gdasapp_convert_bufr_adpsfc_snow
44/54 Test #1767: test_gdasapp_convert_bufr_adpsfc_snow .................   Passed    4.46 sec
      Start 1768: test_gdasapp_convert_bufr_adpsfc
45/54 Test #1768: test_gdasapp_convert_bufr_adpsfc ......................   Passed    4.26 sec
      Start 1769: test_gdasapp_convert_gsi_satbias
46/54 Test #1769: test_gdasapp_convert_gsi_satbias ......................   Passed    1.78 sec
      Start 1770: test_gdasapp_setup_atm_cycled_exp
47/54 Test #1770: test_gdasapp_setup_atm_cycled_exp .....................   Passed    0.99 sec
      Start 1771: test_gdasapp_atm_jjob_var_init
48/54 Test #1771: test_gdasapp_atm_jjob_var_init ........................   Passed   44.35 sec
      Start 1772: test_gdasapp_atm_jjob_var_run
49/54 Test #1772: test_gdasapp_atm_jjob_var_run .........................   Passed  106.15 sec
      Start 1773: test_gdasapp_atm_jjob_var_final
50/54 Test #1773: test_gdasapp_atm_jjob_var_final .......................   Passed   52.26 sec
      Start 1774: test_gdasapp_atm_jjob_ens_init
51/54 Test #1774: test_gdasapp_atm_jjob_ens_init ........................   Passed   44.20 sec
      Start 1775: test_gdasapp_atm_jjob_ens_run
52/54 Test #1775: test_gdasapp_atm_jjob_ens_run .........................   Passed  299.36 sec
      Start 1776: test_gdasapp_atm_jjob_ens_final
53/54 Test #1776: test_gdasapp_atm_jjob_ens_final .......................   Passed   42.15 sec
      Start 1777: test_gdasapp_aero_gen_3dvar_yaml
54/54 Test #1777: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    0.37 sec

83% tests passed, 9 tests failed out of 54

Label Time Summary:
gdas-utils    =  13.59 sec*proc (9 tests)
script        =  13.59 sec*proc (9 tests)

Total Test time (real) = 1089.14 sec

The following tests FAILED:
        1752 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP (Failed)
        1753 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT (Failed)
        1754 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN (Failed)
        1757 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT (Failed)
        1758 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST (Failed)
        1759 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY (Failed)
        1760 - test_gdasapp_soca_socahybridweights (Failed)
        1761 - test_gdasapp_soca_incr_handler (Failed)
        1762 - test_gdasapp_soca_ens_handler (Failed)
```

Change this PR back to _Ready_.

**Comment by RussTreadon-NOAA** [comment]
With the merger of PR #989 into `RussTreadon-NOAA:feature/test_gdasapp_atm_jjob_var` all g-w ctests pass. 

I will merge the PR into `develop` pending approval.  I can not merge _as is_ because I am the author of these changes.

**Review by guillaumevernieres — APPROVED** [review]
Thanks @RussTreadon-NOAA

**Comment by RussTreadon-NOAA** [comment]
Thank you @guillaumevernieres !   About to press the green button.

**Pull request merged**
