### PR TITLE
Code clean-up and a reference test for VIIRS AOD IODA converter

### PR DESCRIPTION
**Pull request by ypwang19**
### Description:

- Remove duplicate code (NetCDFToIodaConverter2d.h) and implement the channel dimension to the original constructors.

- Update the VIIRS ioda converter ctest with reference test.

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]
This all looks great, thanks @ypwang19 for a great cleanup!

**Review by andytangborn — APPROVED** [review]
Looks good to me.

**Review by guillaumevernieres — APPROVED** [review]
Looks great @ypwang19 ! Thanks for doing this. 
Triggering the ci on hera/orion ...

**Review by apchoiCMD — APPROVED** [review]
Looks good to me, thanks for doing this @ypwang19

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres curious as to why the labels are still 'running'...

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres curious as to why the labels are still 'running'...

Same here, but I see you found the issue!

**Comment by guillaumevernieres** [comment]
The CI failure is unrelated to this work, merging! 
Are you going to submit a bug fix PR in the g-w @ShastriPaturi ?

**Pull request merged**
