### PR TITLE
Update select JEDI hashes

### LINKED ISSUE #1313: Resume nightly testing of GDASApp
Directory `ci` contains the following scripts
```
driver.sh  gw_driver.sh  hera.sh  orion.sh  run_ci.sh  run_gw_ci.sh  stable_driver.sh
```
along with directory `validation`.  

`stable_driver.sh` was previously run via cron to 
- clone global-workflow `develop`
- update jedi hashes in `sorc/gdas.cd`
-  build g-w with updated `sorc/gdas.cd`
- run GDASApp ctests
- if all tests _Passed_ push updated `sorc/gdas.cd` to GDASApp `feature/stable-nightly`

The nightly cron was turned off after several failures.

This issue is opened to document the work needed to resume nightly testing of GDASApp.

### LINKED ISSUE #1407: Update soil variables in fv3jedi fieldmetadata and atmospheric ctest reference files
fv3-jedi PR [#1305](https://github.com/JCSDA-internal/fv3-jedi/pull/1305) modified the processing of soil variables. When the GDASApp `sorc/fv3-jedi` hash is updated to [`97e10d5`](https://github.com/JCSDA-internal/fv3-jedi/commit/97e10d5addfe75debab7a6b5604e7a7443f00333) or a hash thereafter, it is necessary to update at a minimum the following files
```
parm/io/fv3jedi_fieldmetadata_history.yaml
test/testreference/C96C48_ufs_hybatmDA_3dvar.ref
test/testreference/C96C48_ufs_hybatmDA_lgetkf_observer.ref
test/testreference/C96C48_ufs_hybatmDA_lgetkf_solver.ref
test/testreference/atm_jjob_3dvar.ref
test/testreference/atm_jjob_lgetkf.ref
test/testreference/atm_jjob_lgetkf_observer.ref
test/testreference/atm_jjob_lgetkf_solver.ref
```
The `parm/jcb-gdas` hash also needs to be updated to use the new soil variables.  This change is documented in jcb-gdas issue [#49](https://github.com/NOAA-EMC/jcb-gdas/issues/49).

### LINKED ISSUE #1419: GDASApp gdas-utils build fails with updated jedi hashes
jcsda-internal/oops issue [#2794](https://github.com/JCSDA-internal/oops/issues/2794) removed the --validate-only and --no-validate options from the OOPS Applications.  This issue touched several repos via the following PRs

[Remove validation options from OOPS Applications #2795](https://github.com/JCSDA-internal/oops/pull/2795)
[Remove validation options from OOPS Applications JCSDA-internal/ioda#1391](https://github.com/JCSDA-internal/ioda/pull/1391)
[Remove validation options from OOPS Applications JCSDA-internal/ufo#3548](https://github.com/JCSDA-internal/ufo/pull/3548)
[Remove validation options from OOPS Applications JCSDA-internal/saber#979](https://github.com/JCSDA-internal/saber/pull/979)
[Remove validation options from OOPS Applications JCSDA-internal/soca#1101](https://github.com/JCSDA-internal/soca/pull/1101)
[Remove validation options from OOPS Applications JCSDA-internal/fv3-jedi#1308](https://github.com/JCSDA-internal/fv3-jedi/pull/1308)

[Remove validation options from OOPS Applications JCSDA-internal/lfric-jedi#953](https://github.com/JCSDA-internal/lfric-jedi/pull/953)
[Remove validation options from OOPS Applications JCSDA-internal/ops-um-jedi#244](https://github.com/JCSDA-internal/ops-um-jedi/pull/244)
[Remove validation options from OOPS Applications MetOffice/orca-jedi#126](https://github.com/MetOffice/orca-jedi/pull/126)

Many of these PRs were merged in their respective `develop` on 12/16/2024.  The 12/17/2024 run of `stable_driver.sh` updated to the following components in `sorc` to new hashes
```
Hera(hfe04):/scratch1/NCEPDEV/da/Russ.Treadon/CI/GDASApp/test/stable/20241
217/global-workflow/sorc/gdas.cd/sorc$ git diff .
diff --git a/sorc/fv3-jedi b/sorc/fv3-jedi
index 136dfb9..55e64b1 160000
--- a/sorc/fv3-jedi
+++ b/sorc/fv3-jedi
@@ -1 +1 @@
-Subproject commit 136dfb9c2f8541584e62fa74c616d686602bcdad
+Subproject commit 55e64b165dc13e9881918e427c28e546a8373b2c
diff --git a/sorc/ioda b/sorc/ioda
index 22cd20e..7f0c6c0 160000
--- a/sorc/ioda
+++ b/sorc/ioda
@@ -1 +1 @@
-Subproject commit 22cd20eae0685914a5b967e13f95779b57bb448c
+Subproject commit 7f0c6c058b189baa6a043c917920cc78a98a094b
diff --git a/sorc/iodaconv b/sorc/iodaconv
index 6f87a0f..a2c29b8 160000
--- a/sorc/iodaconv
+++ b/sorc/iodaconv
@@ -1 +1 @@
-Subproject commit 6f87a0f279e836fd604e5b313a25bd1e54bff80e
+Subproject commit a2c29b867443182ce24360d4ca53a6f56af55faa
diff --git a/sorc/oops b/sorc/oops
index 1ba321f..58b0687 160000
--- a/sorc/oops
+++ b/sorc/oops
@@ -1 +1 @@
-Subproject commit 1ba321ff912c6338d7362667eff37ddbf569cb18
+Subproject commit 58b068767ec4af2cbecfe86499b87a0d4723778f
diff --git a/sorc/saber b/sorc/saber
index de5015c..04087e6 160000
--- a/sorc/saber
+++ b/sorc/saber
@@ -1 +1 @@
-Subproject commit de5015c8328f5b3d64acc99739fbaa64ef571172
+Subproject commit 04087e606c0d6642ca081977901be509e45fd1fe
diff --git a/sorc/soca b/sorc/soca
index 44c4d6e..8e4237a 160000
--- a/sorc/soca
+++ b/sorc/soca
@@ -1 +1 @@
-Subproject commit 44c4d6e53efa774bbaa038b0ecc4c34e3a33c9df
+Subproject commit 8e4237a578de6fbacf0d8b8941ba32153b534d25
diff --git a/sorc/ufo b/sorc/ufo
index 85ef98c..7da3e54 160000
--- a/sorc/ufo
+++ b/sorc/ufo
@@ -1 +1 @@
-Subproject commit 85ef98cb99f3eae1ed15e39f0cb05046af36fef1
+Subproject commit 7da3e5401b4737c98be2f9f6d2cfc6c70c8c9078
diff --git a/sorc/vader b/sorc/vader
index 3049658..0792f69 160000
--- a/sorc/vader
+++ b/sorc/vader
@@ -1 +1 @@
-Subproject commit 3049658d185c8095caf0e506795d0e5995fa92cf
+Subproject commit 0792f693148c3d09a166021e6b8c2758cb8a1251
```

The GDASApp build with the updated jedi hashes aborted with the following message
```
/scratch1/NCEPDEV/da/Russ.Treadon/CI/GDASApp/test/stable/20241217/global-workflow/sorc/gdas.cd/bundle/gdas-utils/soca/gdassoca_obsstats.cc(8): error: object of abstract class type "gdasapp::ObsStats" is not allowed:
            pure virtual function "oops::Application::execute" has no overrider
    gdasapp::ObsStats obsStats;
                      ^

compilation aborted for /scratch1/NCEPDEV/da/Russ.Treadon/CI/GDASApp/test/stable/20241217/global-workflow/sorc/gdas.cd/bundle/gdas-utils/ioda_example/gdas_meanioda.cc (code 2)
compilation aborted for /scratch1/NCEPDEV/da/Russ.Treadon/CI/GDASApp/test/stable/20241217/global-workflow/sorc/gdas.cd/bundle/gdas-utils/soca/gdassoca_obsstats.cc (code 2)
make[2]: *** [gdas-utils/soca/CMakeFiles/gdassoca_obsstats.x.dir/build.make:76: gdas-utils/soca/CMakeFiles/gdassoca_obsstats.x.dir/gdassoca_obsstats.cc.o] Error 2
make[2]: *** [gdas-utils/obsproc/applications/CMakeFiles/gdas_obsprovider2ioda.x.dir/build.make:76: gdas-utils/obsproc/applications/CMakeFiles/gdas_obsprovider2ioda.x.dir/gdas_obsprovider2ioda.cc.o] Error 2
make[2]: Leaving directory '/scratch1/NCEPDEV/da/Russ.Treadon/CI/GDASApp/test/stable/20241217/global-workflow/sorc/gdas.cd/build'
make[1]: *** [CMakeFiles/Makefile2:28921: gdas-utils/obsproc/applications/CMakeFiles/gdas_obsprovider2ioda.x.dir/all] Error 2
```

We need to examine applications in `gdas-utils`.  Looks like several need to be updated to work with the the removal of the --validate-only and --no-validate options from JEDI repositories

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
This PR updates select jedi hashes in `sorc` with recent JCSDA updates.

Resolves: #1313
Resolves: #1407
Resolves: #1419

Depends
 - [x] jcb-gdas [#56](https://github.com/NOAA-EMC/jcb-gdas/pull/56)
 - [x] DA-utils [#7](https://github.com/NOAA-EMC/DA-utils/pull/7)

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Change this PR back to draft.  Also change jcb-gdas https://github.com/NOAA-EMC/jcb-gdas/pull/56 and 
 DA-utils https://github.com/NOAA-EMC/DA-utils/pull/7 to draft.  

Once g-w PR [#3163](https://github.com/NOAA-EMC/global-workflow/pull/3163) is merged into `develop`, we can
1. merge jcb-gdas https://github.com/NOAA-EMC/jcb-gdas/pull/56
2. merge DA-utils https://github.com/NOAA-EMC/DA-utils/pull/7
3. update `parm/jcb-gdas` and `sorc/da-utils` hashes in this PR
4. merge this PR into `develop`

**Comment by guillaumevernieres** [comment]
@RussTreadon-NOAA , any idea of a timeline for when this PR will be merged?

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres : This PR is waiting for g-w PR [#3163](https://github.com/NOAA-EMC/global-workflow/pull/3163) to be merged into g-w `develop`.  g-w CI for [#3163](https://github.com/NOAA-EMC/global-workflow/pull/3163) was run over the weekend and passes.  Given this, I was hopeful that [#3163](https://github.com/NOAA-EMC/global-workflow/pull/3163) would be merged into g-w `develop` yesterday.  This did not happen.

**Comment by RussTreadon-NOAA** [comment]
g-w PR [#3163](https://github.com/NOAA-EMC/global-workflow/pull/3163) has been merged into g-w `develop`.  This PR may move forward.  

First we need to 
- approve and merge jcb-gdas PR [#56](https://github.com/NOAA-EMC/jcb-gdas/pull/56)
- approve and merge DA-utils PR [#7](https://github.com/NOAA-EMC/DA-utils/pull/7)

After this, we can update the `parm/jcb-gdas` and `sorc/da-utils` hashes in this PR

Note:  The 20241220 stable nightly was run using this PR along with g-w [#3163](https://github.com/NOAA-EMC/global-workflow/pull/3163).  All 134 gdasapp ctests passed.

**Review by danholdaway — DISMISSED** [review]

**Comment by RussTreadon-NOAA** [comment]
Running full suite of gdasapp ctests, both GDASApp and g-w based, using g-w `develop` at [`e684944`](https://github.com/NOAA-EMC/global-workflow/commit/e6849447fb231979ec2112594d51be9e93b99a5e)) and `feature/stable-nightly` at 5ea120e.  

Based on last night's stable-nightly results all tests should pass.  So far 110/134 tests have run and passed.  Several g-w based jobs are PENDING in the queue.  I'll update this PR with the full ctest results once all tests finish.

**Review by danholdaway — DISMISSED** [review]

**Review by CoryMartin-NOAA — DISMISSED** [review]
approved pending successful completion of tests

**Comment by RussTreadon-NOAA** [comment]
jcb-algorithm PR [#9](https://github.com/NOAA-EMC/jcb-algorithms/pull/9) removes `Jb` from the test reference output file.  This caused test_gdasapp_atm_jjob_var_run to fail
```
0: OOPS_STATS Run end                                  - Runtime:     53.83 sec,  Memory: total:     9.52 Gb, per task: min =     1.54 Gb, max =     1.64 Gb
0: Run: Finishing oops::Variational<FV3JEDI, UFO and IODA observations> with status = 0
0: terminate called after throwing an instance of 'oops::TestReferenceTextMismatchError'
0:   what():  Test reference Text mismatch @ Line:1
0: Test: 'CostJo   : Nonlinear Jo(AMSUA N19) = 3.9490015258314117e+04, nobs = 73667, Jo/n = 5.3606112992675303e-01, err = 6.2697697603634124e+00'
0: Ref:  'CostJb   : Nonlinear Jb = 0.0000000000000000e+00'
srun: error: h35m34: task 0: Aborted (core dumped)
```

I suspect other ctests will fail the reference check.  I will update the references in `feature/stable-nightly` once the updated reference files from all failures are available.

Previous tests did not catch this because `feature/stable-nightly` was using an earlier hash of `jcb-algorithms`.

**Comment by danholdaway** [comment]
Thanks @RussTreadon-NOAA. Apologies, I let Guillaume remove the backward compatibility there. I didn't realize that would be included in the ref.

**Comment by RussTreadon-NOAA** [comment]
No problem.  The reference check is doing its job.

**Comment by RussTreadon-NOAA** [comment]
Ugh, updating the reference file dismissed the approvals!

@CoryMartin-NOAA, @danholdaway , or @DavidNew-NOAA :  If you see this message would you please approve this PR.

g-w based reference checks did not fail because g-w PR [#3177](https://github.com/NOAA-EMC/global-workflow/pull/3177) turned off reference checks in g-w based GDASApp ctests.   

We still need to update select reference files for g-w based ctests given jcb-algorithm PR [#9](https://github.com/NOAA-EMC/jcb-algorithms/pull/9), but we don't need to do so for this PR.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
Thank you @CoryMartin-NOAA !   I'll go ahead and merge.

**Pull request merged**
