### PR TITLE
Make the seaice DA actually do something ...

### LINKED ISSUE #1087: The sea-ice DA IS broken
It doesn't look like the restart that contains the analysis is used. 

That doesn't look right:
https://github.com/NOAA-EMC/GDASApp/blob/7436897ad63bbc1489c5bc1e09810728173c5e2b/scripts/exgdas_global_marine_analysis_post.py#L102

### PR DESCRIPTION
**Pull request by guillaumevernieres**
- fixes #1087

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
- I don't understand the failures of the marine DA on hera ... Only post should have failed
- Failure on orion is related to a change in the g-w that hasn't been merge yet
- I suppose we were expecting things to be broken for the atmosphere? Pinging @danholdaway , @CoryMartin-NOAA or @RussTreadon-NOAA ... in no particular order! It's complaining about not finding an executable.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres :  I was looking at log files in `/scratch1/NCEPDEV/da/Cory.R.Martin/CI/GDASApp/workflow/PR/1092/global-workflow/sorc/gdas.cd/build/gdas/test/atm/global-workflow/testrun` when the directory disappeared.

The `atm_jjob` tests probably failed because g-w has not yet been updated to be consistent with GDASApp PR [#1075](https://github.com/NOAA-EMC/GDASApp/pull/1075).  

I just finished building g-w PR [#2565](https://github.com/NOAA-EMC/global-workflow/pull/2565) on Hera.  All `test_gdasapp` jobs pass including the atm var and ens jobs.  
```
      Start 1772: test_gdasapp_setup_atm_cycled_exp
37/45 Test #1772: test_gdasapp_setup_atm_cycled_exp .....................   Passed    2.45 sec
      Start 1773: test_gdasapp_atm_jjob_var_init
38/45 Test #1773: test_gdasapp_atm_jjob_var_init ........................   Passed   48.96 sec
      Start 1774: test_gdasapp_atm_jjob_var_run
39/45 Test #1774: test_gdasapp_atm_jjob_var_run .........................   Passed  106.39 sec
      Start 1775: test_gdasapp_atm_jjob_var_inc
40/45 Test #1775: test_gdasapp_atm_jjob_var_inc .........................   Passed  106.61 sec
      Start 1776: test_gdasapp_atm_jjob_var_final
41/45 Test #1776: test_gdasapp_atm_jjob_var_final .......................   Passed   42.83 sec
      Start 1777: test_gdasapp_atm_jjob_ens_init
42/45 Test #1777: test_gdasapp_atm_jjob_ens_init ........................   Passed   79.26 sec
      Start 1778: test_gdasapp_atm_jjob_ens_run
43/45 Test #1778: test_gdasapp_atm_jjob_ens_run .........................   Passed  554.52 sec
      Start 1779: test_gdasapp_atm_jjob_ens_final
44/45 Test #1779: test_gdasapp_atm_jjob_ens_final .......................   Passed   74.43 sec
      Start 1780: test_gdasapp_aero_gen_3dvar_yaml
45/45 Test #1780: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    1.06 sec

100% tests passed, 0 tests failed out of 45

Label Time Summary:
gdas-utils    =   9.55 sec*proc (9 tests)
script        =   9.55 sec*proc (9 tests)

Total Test time (real) = 1605.60 sec
```

JEDI ATM CI is now running on Hera.

**Comment by guillaumevernieres** [comment]
Sorry @RussTreadon-NOAA , I asked @CoryMartin-NOAA to remove the pr directory. The issue in the marine DA didn't make any sense.

**Review by apchoiCMD — APPROVED** [review]

**Review by AndrewEichmann-NOAA — APPROVED** [review]
I'll take your word for it

**Pull request merged**
