### PR TITLE
Fix example GDAS OOPS utility

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
Time Window issues strike again!

I haven't tested yet because I think fv3-jedi also needs merged now...

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
FV3-JEDI was merged 5 mins ago, we should try to build now.

**Review by RussTreadon-NOAA — DISMISSED** [review]
Looks right.  Caveat:  I say this as an inexperienced c++ programmer.  

Approve.

**Review by AndrewEichmann-NOAA — DISMISSED** [review]
Let's give it a whirl

**Review by ShastriPaturi — DISMISSED** [review]

**Review by ShastriPaturi — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , with this PR now in `develop` is it time to update `feature/gdas-validation` with the current head of `develop`?

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA probably yes, but maybe double check with others since that would require a recompile of code

**Pull request merged**
