### PR TITLE
Add Obs. trimming function to IODA converter of icec and sss_smap

### LINKED ISSUE #682: Implementation of obs. trimming
A trim method was developed by @AndrewEichmann-NOAA but only implemented for a few providers. It also need to be implemented for the following:
- IceAmsr2Ioda
- ~Rads2Ioda~
- Smap2Ioda

### PR DESCRIPTION
**Pull request by apchoiCMD**
- Adds the basic trim function to icec_amsr2 and sss_smap
- Excludes ioda converter for adt_rads

Closes to https://github.com/NOAA-EMC/GDASApp/issues/682

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Looks like [OOPS PR2423](https://github.com/JCSDA-internal/oops/pull/2423) broke the `ioda-converters` build.
@apchoiCMD , same comment that I made to @AndrewEichmann-NOAA , "Resolved" is not a github keyword and will not trigger the closing of the issue. Replace with "fixes" or "closes".

**Comment by guillaumevernieres** [comment]
@CoryMartin-NOAA , @andytangborn , is the error in aero run and final expected?

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres unfortunately yes.

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres unfortunately yes.

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres I'm looking into it, I also noticed it earlier today.

**Review by guillaumevernieres — APPROVED** [review]
Thanks @apchoiCMD

**Review by AndrewEichmann-NOAA — APPROVED** [review]
Looks good

**Pull request merged**
