### PR TITLE
Marine obs reorganization and more ... 

### LINKED ISSUE #869: Regexp to select the marine obs is too restrictive
I assumed that would be the case, and it is. Doing things like this `??????????????-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.nc` for example, is not general enough to work. We need to replace `?` with `*` and remove the version number to capture more of the possible cases.

### LINKED ISSUE #874: Update JEDI #'s
FYI @CoryMartin-NOAA and @RussTreadon-NOAA

### PR DESCRIPTION
**Pull request by guillaumevernieres**
Things done:
- Assumes that the obs will be organized like something like this from now on:
```console
└── gdas.20180415
    └── 12
        └── ocean
            ├── adt
            │   ├── rads_adt_3a_2018105.nc
            │   └── rads_adt_3b_2018105.nc
            ├── icec
            │   ├── AMSR2-SEAICE-NH_v2r2_GW1_s201804150835180_e201804151014170_c201804151052280.nc
            │   ├── AMSR2-SEAICE-NH_v2r2_GW1_s201804151014190_e201804151150170_c201804151309570.nc
            │   ├── AMSR2-SEAICE-SH_v2r2_GW1_s201804150835180_e201804151014170_c201804151052280.nc
            │   └── AMSR2-SEAICE-SH_v2r2_GW1_s201804151014190_e201804151150170_c201804151309570.nc
            ├── sss
            └── sst
                ├── 20180415095000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.nc
                ├── 20180415114000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.nc
                └── 20180415132000-STAR-L3U_GHRSST-SSTsubskin-AVHRRF_MB-ACSPO_V2.80-v02.0-fv01.0.nc
```
- Use of the `*` wildcard instead of `?` to simplify the obs file selection
- Addition of binning for the sst retrieval
- The `soca` # needs to be more recent.
- This wasn't planned as part of this work, but the bump localization was having issues, so I replaced it with `diffusion`

### Issues addressed
- fixes #869 
- fixes #874

### CODE REVIEW

**Review by ShastriPaturi — APPROVED** [review]

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres I'm refactoring the obsprep_setup, so don't sweat that too much

**Review by apchoiCMD — APPROVED** [review]

**Review by AndrewEichmann-NOAA — APPROVED** [review]

**Comment by guillaumevernieres** [comment]
@RussTreadon-NOAA , @CoryMartin-NOAA , FYI: I added an update to the # commit of the JEDI repositories.

**Comment by CoryMartin-NOAA** [comment]
Just a question: Is this the assumed structure for DMPDIR, COM_OBS, or both?

**Comment by guillaumevernieres** [comment]
> Just a question: Is this the assumed structure for DMPDIR, COM_OBS, or both?

@CoryMartin-NOAA , what's in the description is the assumed structure of DMPDIR.

**Comment by CoryMartin-NOAA** [comment]
Thanks, @guillaumevernieres !

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
