### PR TITLE
Updated adpupa prepbufr api for the ObsError group variables

### PR DESCRIPTION
**Pull request by PraveenKumar-NOAA**
This PR updates the adpupa prepbufr api for the ObsError group variables and also updates the function for the dateiTme variable. 

The following file has been changed: 
~/ush/ioda/bufr2ioda/bufr2ioda_adpupa_prepbufr.py

### CODE REVIEW

**Review by nicholasesposito — DISMISSED** [review]
Looks good

**Comment by PraveenKumar-NOAA** [comment]
@emilyhcliu @ADCollard @CoryMartin-NOAA @RussTreadon-NOAA please review this PR, thanks.

**Review by ADCollard — DISMISSED** [review]

**Review by CoryMartin-NOAA — DISMISSED** [review]

**Comment by CoryMartin-NOAA** [comment]
Do we want this in `develop` or the sprint branch?

**Comment by CoryMartin-NOAA** [comment]
@PraveenKumar-NOAA now that I've rebased, can you resolve the conflicts?

**Comment by PraveenKumar-NOAA** [comment]
> @PraveenKumar-NOAA now that I've rebased, can you resolve the conflicts?

@CoryMartin-NOAA done, thanks.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
