### PR TITLE
Updates to GDASapp to account for new JCB policies

### PR DESCRIPTION
**Pull request by danholdaway**
- Renaming of atmosphere YAMLS and keys.
- Add marine YAML files to JCB
- Add creation of 3DVarFGAT YAML for marine using JCB (not used yet but YAML matched exactly).

Once approved I will merge the JCB PRs and then we can merge this after updating the hashes.

A G-W PR will follow the approval and merge of this PR.

G-W branch required for testing: https://github.com/danholdaway/global-workflow/tree/feature/rename_atm

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
**Orion test**
Install `feature/rename_atm` at 2ec1767 inside g-w `devleop` at [`c44d0ac8`](https://github.com/NOAA-EMC/global-workflow/commit/c44d0ac86cfdf78eb87492431bf6d825e8bae637).  Initial run of `test_gdasapp` yielded the following ctest failures
```
64% tests passed, 17 tests failed out of 47

Label Time Summary:
gdas-utils    =   4.10 sec*proc (9 tests)
script        =   4.10 sec*proc (9 tests)

Total Test time (real) = 1370.19 sec

The following tests FAILED:
        1756 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP (Failed)
        1757 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT (Failed)
        1758 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN (Failed)
        1761 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT (Failed)
        1762 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST (Failed)
        1763 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY (Failed)
        1764 - test_gdasapp_soca_socahybridweights (Failed)
        1765 - test_gdasapp_soca_incr_handler (Failed)
        1766 - test_gdasapp_soca_ens_handler (Failed)
        1775 - test_gdasapp_atm_jjob_var_init (Failed)
        1776 - test_gdasapp_atm_jjob_var_run (Failed)
        1777 - test_gdasapp_atm_jjob_var_inc (Failed)
        1778 - test_gdasapp_atm_jjob_var_final (Failed)
        1779 - test_gdasapp_atm_jjob_ens_init (Failed)
        1780 - test_gdasapp_atm_jjob_ens_run (Failed)
        1781 - test_gdasapp_atm_jjob_ens_inc (Failed)
        1782 - test_gdasapp_atm_jjob_ens_final (Failed)
```

Need to update g-w `sorc/jcb` to be consistent with jcb-algorithms and jcb-gdas used in `sorc/gdas.cd/parm`.  Update working copy of `sorc/jcb` to jcb branch `feature/rename_atm` at [`d167c6c`](https://github.com/NOAA-EMC/jcb/commit/d167c6c27312ae6fbd9d82c2747fecc6687eb0f9).  Rerun `test_gdasapp`.  More ctests pass.  Failures are limited to soca tests
```
81% tests passed, 9 tests failed out of 47

Label Time Summary:
gdas-utils    =   4.66 sec*proc (9 tests)
script        =   4.66 sec*proc (9 tests)

Total Test time (real) = 1787.51 sec

The following tests FAILED:
        1756 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP (Failed)
        1757 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT (Failed)
        1758 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN (Failed)
        1761 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT (Failed)
        1762 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST (Failed)
        1763 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY (Failed)
        1764 - test_gdasapp_soca_socahybridweights (Failed)
        1765 - test_gdasapp_soca_incr_handler (Failed)
        1766 - test_gdasapp_soca_ens_handler (Failed)
```
Some of these failures may flip to _Passed_ if the initial `test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP` failure is resolved. 

Took a peek at `/work2/noaa/da/rtreadon/git/global-workflow/rename_atm/sorc/gdas.cd/build/gdas/test/soca/gw/testrun/JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP.out`.  

The traceback flagged `gdas.t12z.insitu_surface_trkob.2018041512.nc4` as a missing file.  This, however, may not be the cause of the failure.  The traceback ends with 
```
  File "/work2/noaa/da/rtreadon/git/global-workflow/rename_atm/parm/gdas/jcb-algorithms/3dfgat.yaml.j2", line 45, in top-level template code
    {% include observation_from_jcb + '.yaml.j2' %}
  File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: insitu_profile_bathy.yaml.j2
+ JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP[1]: postamble JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP 1717527206 1
```

**Comment by danholdaway** [comment]
Thanks for testing @RussTreadon-NOAA. Passing tests require https://github.com/danholdaway/global-workflow/tree/feature/rename_atm branch of global-workflow. You should be able to switch branch and run the tests again without a rebuild since it's just a change to jcb and config that matters.

**Comment by danholdaway** [comment]
Ah I see you did that. Perhaps the failure is because of more observations added to obs_list without those YAMLs going to JCB as well. Let me check.

**Comment by danholdaway** [comment]
@RussTreadon-NOAA I fixed that failure by adding the insitu YAML files to JCB. There should be zero downstream impact on the other tests, which should all pass again.

**Comment by RussTreadon-NOAA** [comment]
Updated branches and submodules in `/work2/noaa/da/rtreadon/git/global-workflow/rename_atm`.  (Note:  I am working in a locally modified copy of g-w `develop`.)

45 out of 47 tests pass
```
96% tests passed, 2 tests failed out of 47

Label Time Summary:
gdas-utils    =   9.85 sec*proc (9 tests)
script        =   9.85 sec*proc (9 tests)

Total Test time (real) = 1953.63 sec

The following tests FAILED:
        1836 - test_gdasapp_fv3jedi_fv3inc (Failed)
        1849 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY (Failed)
```

A rerun of `test_gdasapp_fv3jedi_fv3inc` passed
```
(gdasapp) Orion-login-2:/work2/noaa/da/rtreadon/git/global-workflow/rename_atm/sorc/gdas.cd/build$ ctest -R test_gdasapp_fv3jedi_fv3inc
Test project /work2/noaa/da/rtreadon/git/global-workflow/rename_atm/sorc/gdas.cd/build
    Start 1836: test_gdasapp_fv3jedi_fv3inc
1/1 Test #1836: test_gdasapp_fv3jedi_fv3inc ......   Passed    5.43 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   5.98 sec
```
I can not explain why the first run failed.  The test includes a reference check.  Is it possible that fv3jedi_fv3inc test results are not bitwise identical from one run to the next?  What do you think @DavidNew-NOAA?

A check of the log file for `test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY` shows
```
2024-06-06 20:49:14:INFO:Loading input YAML from preevayamls/eva_insitu_profile_tesac_salinity_2018041512.yaml
Traceback (most recent call last):
  File "/work2/noaa/da/rtreadon/git/global-workflow/rename_atm/sorc/gdas.cd/scripts/exgdas_global_marine_analysis_vrfy.py", line 187, in <module>
    marine_eva_post.marine_eva_post(infile, 'evayamls', diagdir)
  File "/work2/noaa/da/rtreadon/git/global-workflow/rename_atm/sorc/gdas.cd/ush/eva/marine_eva_post.py", line 39, in marine_eva_post
    layer['vmin'] = vminmax[variable]['vmin']
KeyError: 'salinity'
+ JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY[1]: postamble JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY 1717706755 1
+ preamble.sh[70]: set +x
End JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY at 20:49:15 with error code 1 (time elapsed: 00:03:20)
+ Unknown[1]: postamble slurm_script 1717706753 1
```
My working copy of `feature/rename_atm` may not be consistent with the current state of g-w `develop` and/or other repositories.

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA There shouldn't be a reference check of the input/output state for the fv3inc tests. However, there were some significant updates to Global Workflow on Wednesday, and I was getting some similar errors yesterday until I updates all my repos

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA Sorry, I take that back. There is a reference check for `test_gdasapp_fv3jedi_fv3inc`. I was thinking of `test_gdasapp_atm_jjob_var_inc` and `test_gdasapp_atm_jjob_ens_inc`. Eventually I wish to add reference checks for those two jobs which will make `test_gdasapp_fv3jedi_fv3inc` somewhat redundant. Anyways, I'm not sure about whether things are bitwise identical from one run to the next. I would hope they are on the same machine.

**Comment by RussTreadon-NOAA** [comment]
**Orion tests**

Install forked g-w [`feature/rename_atm`](https://github.com/danholdaway/global-workflow/tree/feature/rename_atm) at [`09ec021`](https://github.com/danholdaway/global-workflow/commit/09ec0213198ecda06a6aea5f71d6ec52b446d218) on Orion.  This fork clones GDASApp `feature/rename_atm` into g-w `sorc/gdas.cd`.  Update cloned `sorc/gdas.cd` to current head, 72beb13, of GDASApp `feature/rename_atm`.

Run GDASApp ctests.  47 out of 47 tests pass
```
Test project /work2/noaa/da/rtreadon/git/global-workflow/rename_atm/sorc/gdas.cd/build
      Start 1489: test_gdasapp_util_coding_norms
 1/47 Test #1489: test_gdasapp_util_coding_norms ........................   Passed    8.84 sec
...
      Start 1869: test_gdasapp_aero_gen_3dvar_yaml
47/47 Test #1869: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    0.26 sec

100% tests passed, 0 tests failed out of 47

Label Time Summary:
gdas-utils    =  16.49 sec*proc (9 tests)
script        =  16.49 sec*proc (9 tests)

Total Test time (real) = 1521.82 sec
```

Run g-w CI C96C48_ufs_hybatmDA.  The following jobs failed
```
202402240000           gdasatmanlvar                    18266389                DEAD                   1         2         102.0
202402240000            gfsatmanlvar                    18266345                DEAD                   1         2          66.0
```
due to 
```
 6: GSI grid: number of processor in layout does not match number in communicator
12: GSI grid: number of processor in layout does not match number in communicator
14: GSI grid: number of processor in layout does not match number in communicator
18: GSI grid: number of processor in layout does not match number in communicator
```
Examination of the input yaml found
```
        saber central block:
          saber block name: gsi static covariance
          read:
            gsi akbk: ./fv3jedi/akbk.nc4
            gsi error covariance file: /work/noaa/stmp/rtreadon/ORION/RUNDIRS/prename/gfsatmanl_00/berror/gsi-coeffs-gfs-global.nc4
            gsi berror namelist file: /work/noaa/stmp/rtreadon/ORION/RUNDIRS/prename/gfsatmanl_00/berror/gfs_gsi_global.nml
            processor layout x direction: 12
            processor layout y direction: 8
            debugging mode: false
        saber outer blocks:
        - saber block name: gsi interpolation to model grid
          gsi akbk: ./fv3jedi/akbk.nc4
          gsi error covariance file: /work/noaa/stmp/rtreadon/ORION/RUNDIRS/prename/gfsatmanl_00/berror/gsi-coeffs-gfs-global.nc4
          gsi berror namelist file: /work/noaa/stmp/rtreadon/ORION/RUNDIRS/prename/gfsatmanl_00/berror/gfs_gsi_global.nml
          processor layout x direction: 12
          processor layout y direction: 12
          debugging mode: false
```
The `[12,8]` layout is correct.  The `[12,12]` layout is wrong.   Trace this to a typo in `parm/jcb-gdas/model/atmosphere/atmosphere_background_error_hybrid_gsibec_bump.yaml.j2`  
```
       gsi berror namelist file: {{atmosphere_gsibec_path}}/gfs_gsi_global.nml
       processor layout x direction: {{atmosphere_layout_gsib_x}}
-      processor layout y direction: {{atmosphere_layout_gsib_x}}
+      processor layout y direction: {{atmosphere_layout_gsib_y}}
```
[Note this](https://github.com/NOAA-EMC/jcb-gdas/pull/15#pullrequestreview-2108177905) in jcb PR [#15](https://github.com/NOAA-EMC/jcb-gdas/pull/15).

Correct typo in working copy.  GDASApp-base DA jobs successfully ran to completion.  All jobs now complete
```
(gdasapp) Orion-login-4:/work2/noaa/stmp/rtreadon/EXPDIR/prename$ rocotostat -d prename.db -w prename.xml -c all -s
   CYCLE         STATE           ACTIVATED              DEACTIVATED
202402231800        Done    Jun 10 2024 14:40:15    Jun 10 2024 15:00:30
202402240000        Done    Jun 10 2024 14:40:15    Jun 10 2024 18:01:42
```

**Comment by danholdaway** [comment]
Thanks @RussTreadon-NOAA, feel free to push the required changes to the PRs

**Comment by RussTreadon-NOAA** [comment]
Need to update `parm/jcb-gdas` hash to [`a5d0277`](https://github.com/NOAA-EMC/jcb-gdas/commit/a5d0277de30473784d5d7aed4f054757efddd3e5).  Should also bring `feature/rename_atm` up to date with current head of GDASApp `develop`.

**Review by RussTreadon-NOAA — APPROVED** [review]
Both GDASApp ctests and g-w C96C48_ufs_hybatmDA CI run on various platforms.  Results are acceptable.

Approve.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA, @guillaumevernieres, and @DavidNew-NOAA  - the changes in this PR have been tested via g-w PR [#2700](https://github.com/NOAA-EMC/global-workflow/pull/2700) with acceptable results.  I'd like to merge this PR in GDASApp `develop`.  Any objections?

@danholdaway has three JCB PRs related to GDASApp PR #1144 (this PR):
- [jcb #7](https://github.com/NOAA-EMC/jcb/pull/7)
- [jcb-algoritms #2](https://github.com/NOAA-EMC/jcb-algorithms/pull/2)
- [jcb-gdas #15](https://github.com/NOAA-EMC/jcb-gdas/pull/15)

Each of the jcb PRs have been approved by Cory, David, and Russ.  These jcb PRs should also be merged into their respective `develop`.  Are we OK with doing so?

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA No objection here

**Review by guillaumevernieres — APPROVED** [review]

**Pull request merged**
