### PR TITLE
Update Hera build to Rocky 8

### LINKED ISSUE #958: Build and run GDASApp on Rocky8 Hera nodes
Hera is transitioning to the Rocky-8 OS as scheduled below
- 3/5: 1/3 of Hera (and 50% FGE)
- 3/19: 2/3 of Hera
- 4/2: remainder of Hera (remainder of FGE)

We need to ensure GDASApp can build and run on Rocky-8 Hera nodes.  This issue is opened to track this transition.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
Hera is transitioning from CentOS 7  to Rocky 8.   This PR updates the Hera intel GDASApp build to Rocky 8.

Below is the Hera Rocky 8 transition schedule as of the creation of this PR
- 3/19: two thirds of Hera transitioned to Rocky 8
- 4/2: transition complete.  All Hera uses Rocky 8

Fixes #958

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA , this PR contains changes required to build and run GDASApp on Hera Rocky 8 nodes.   Cross link this PR with g-w [#2329](https://github.com/NOAA-EMC/global-workflow/issues/2329).

**Comment by RussTreadon-NOAA** [comment]
The changes in this PR are ready for review.  Once this PR is approved we need to decide when to merge this PR into `develop`

My preference is to merge on 3/19 when two thirds of Hera is transitioned to Rocky 8.  The latest we can merge is 4/2 after which all of Hera uses Rocky 8.

g-w issue [#2329](https://github.com/NOAA-EMC/global-workflow/issues/2329) needs a `gdas.cd` hash which builds and runs GDASApp on Hera Rocky 8 nodes.

**Comment by RussTreadon-NOAA** [comment]
RDHPCS admins informed users that after the 3/19 Hera maintenance _the default for users logging into Hera will be Rocky 8. You will have to hit ^C and select one of hfe01-hfe04 to access a CentOS 7 login node. All jobs submitted from a Rocky 8 login node will run on Rocky 8 compute nodes._

Given this we should merge this PR into `develop` no later than 3/19.

**Comment by RussTreadon-NOAA** [comment]
PR #975 updates the Eva build on Hera to work on Rocky 8 nodes.   Merged into `feature/rocky8` at [5d43b33](https://github.com/NOAA-EMC/GDASApp/pull/969/commits/5d43b3390ba41b5ee5d958c4861e2fddee0fdbed).

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA & @guillaumevernieres , we need to merge this PR into `develop` and pass a new `gdas.cd` hash to the g-w team.  When shall we merge this PR into `develop` - today (3/18) or tomorrow (3/19)?

**Comment by CoryMartin-NOAA** [comment]
I'm happy with ASAP.

**Comment by RussTreadon-NOAA** [comment]
Agreed. My preference is to merge this afternoon and pass the new `gdas.cd` hash to the g-w team shortly thereafter.

**Comment by RussTreadon-NOAA** [comment]
Would one of you, @CoryMartin-NOAA or @guillaumevernieres, approve this PR?  I'll merge once the PR is approved.  (I can't approve my own PR.)

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
@HenryWinterbottom-NOAA and @aerorahul :  The GDASApp Hera intel build has been updated to Rocky 8.  Done at [e029bd7](https://github.com/NOAA-EMC/GDASApp/commit/e029bd76095b5604f0d8cceb000f1d7c86e7530f).

**Comment by HenryRWinterbottom** [comment]
Thank you @RussTreadon-NOAA. I will build, test, and follow up this issue.

**Pull request merged**
