### PR TITLE
Addition of a switch for the cycling type

### LINKED ISSUE #1071: Seaice analysis insertion is not correct when DO_IAU is switched on
Problem discovered by @JessicaMeixner-NOAA . The failing marine DA is blocking this issue: [issues/2438](https://github.com/NOAA-EMC/global-workflow/issues/2438)

### PR DESCRIPTION
**Pull request by guillaumevernieres**
Draft because I still need to test this while cycling.

- fixes #1071

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
FYI @JessicaMeixner-NOAA , that "should" fix the current issue, but I have yet to test within a proper cycling test ...

**Review by apchoiCMD — APPROVED** [review]

**Review by JessicaMeixner-NOAA — CHANGES_REQUESTED** [review]
Have additional similar issue in gdasocnanalpost that also needs fixed.

**Review by apchoiCMD — DISMISSED** [review]

**Comment by guillaumevernieres** [comment]
As @JessicaMeixner-NOAA wrote above @apchoiCMD , it's still broken ... Working on a fix. I'm re-requesting reviews so we don't see green checks on the review side, if anything just block the pr.

**Comment by apchoiCMD** [comment]
> As @JessicaMeixner-NOAA wrote above @apchoiCMD , it's still broken ... Working on a fix. I'm re-requesting reviews so we don't see green checks on the review side, if anything just block the pr.

Got it, I just assumed that you asked me to review again- @guillaumevernieres

**Review by AndrewEichmann-NOAA — DISMISSED** [review]
Looks ok

**Comment by JessicaMeixner-NOAA** [comment]
@guillaumevernieres I see regtests are running here.   Has the additional bug-fix been added? Should I retest on my side?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I see regtests are running here. Has the additional bug-fix been added? Should I retest on my side?

Not yet @JessicaMeixner-NOAA . ~We try to emulate the cycling in our ctest, but it's not perfect. The ci should have failed. I'll try to have the fix today.~
It didn't fail because we're not testing the "iau" cycling case.

**Review by JessicaMeixner-NOAA — COMMENTED** [review]
Thanks for the fixes @guillaumevernieres  my test now succeeded both failed jobs... gdasfcst is now running... I can report back with the full test has finished as well.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Review by AndrewEichmann-NOAA — APPROVED** [review]
Looks oker

**Review by apchoiCMD — APPROVED** [review]
Thanks @guillaumevernieres

**Pull request merged**
