### PR TITLE
Addition of a climatological ensemble B to the soca B-matrix

### LINKED ISSUE #489: Implement a hybrid static B for the marine DA
Upgrade the static $\bf{B}$ to look like $\bf B = B_{static}+B_{clim.ens.}$

### PR DESCRIPTION
**Pull request by guillaumevernieres**
### Work done
- Removed the BUMP correlation operator (temporary)
- Added a bump configuration for localization and its associated implementation
- Added the clim. ens. B to the saber blocks
- skipping the B-mat verify job for now. There's something wrong with the dirac implementation, to be revisited.
- Fixed a bug in `test_gdasapp_setup_cycled_exp`. I thought we catched that one earlier ... 

### Issues addressed
- fixes #489

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@liuxiao37k , could you have a look at the localization and saber blocks `yaml`'s?

**Comment by liuxiao37k** [comment]
> @liuxiao37k , could you have a look at the localization and saber blocks `yaml`'s?

The `saber_blocks.yaml` changes look fine to me. I tried slightly different parameters (e.g. `rescale_bkgerr:` 2.5 or 3.0) but those were optimized for a slightly different system as we know...

How was the testing with `strategy: crossed`? It didn't go well with BGC states, probably because of their huge ranges and numerical truncations when saving the ensembles.

**Review by liuxiao37k — APPROVED** [review]
I approve the yaml changes. I didn't run the unit tests.

**Review by CoryMartin-NOAA — APPROVED** [review]
No complaints, will wait until tests pass to merge

**Pull request merged**
