### PR TITLE
Get SOCA vrfy job working on Hera again

### LINKED ISSUE #994: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY fails on Hera Rocky 8
When GDASApp `develop` at 2198b41 is built and run on Hera Rocky 8 nodes, `test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY` fails with
```
+ slurm_script[50]: set +u
+ slurm_script[51]: conda activate eva
/var/spool/slurmd/job57658040/slurm_script: line 51: conda: command not found
+ slurm_script[1]: postamble slurm_script 1711388833 127
+ preamble.sh[70]: set +x
End slurm_script at 17:47:14 with error code 127 (time elapsed: 00:00:01)
```

This issue is opened to document this failure and its resolution.

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
What the title says. Fixes #994

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
unit tests fail because EMC RZDM is down...

**Review by guillaumevernieres — APPROVED** [review]
Thanks @CoryMartin-NOAA

**Comment by RussTreadon-NOAA** [comment]
> unit tests fail because EMC RZDM is down...

I am unable to build GDASApp from PR #1033.  I no longer think PR #1033 is the issue.  I'm beginning to suspect the failure is related to EMC RZDM being offline.  Attempts to build GDASApp `develop` at several hashes fail as [documented](https://github.com/NOAA-EMC/GDASApp/pull/1033#issuecomment-2058739950) in PR #1033.

**Comment by CoryMartin-NOAA** [comment]
I'm not sure what to do to fix this logjam. We have no idea when RZDM will be back. Do we disable all unit tests in the interim? Find an alternate place to store the files? Other options?

**Comment by guillaumevernieres** [comment]
> I'm not sure what to do to fix this logjam. We have no idea when RZDM will be back. Do we disable all unit tests in the interim? Find an alternate place to store the files? Other options?

should we put the tarball on hpc instead?

**Comment by RussTreadon-NOAA** [comment]
Why does our not being able to download test files from EMC RZDM break the GDASApp build?  It should only break testing, not the build, right?  Does cmake intertwine application testing with the application build in such a way that if we can't build the tests, we can't build GDASApp?

**Comment by RussTreadon-NOAA** [comment]
Do we have tarball `gdasapp-fix-${SHORTSHA}.tgz` available from somewhere besides `https://ftp.emc.ncep.noaa.gov/static_files/public/GDASApp`?

**Comment by CoryMartin-NOAA** [comment]
> Why does our not being able to download test files from EMC RZDM break the GDASApp build? It should only break testing, not the build, right? Does cmake intertwine application testing with the application build in such a way that if we can't build the tests, we can't build GDASApp?

It's because CMake is doing the downloading. It fails, so CMake can't finish. Perhaps we should instead have a test that runs that downloads/links the files. This is how JCSDA does it for JEDI.

**Comment by RussTreadon-NOAA** [comment]
Placing the tarball on HPC is an option but when the given machine is offline, we're stuck.  We could place the tarball on multiple HPC platforms.  Even this approach has potential pitfalls.  For example, we place the tarball in `/work2` but when we want to build on Orion or Hercules `/work2` is offline for some reason and only `/work` is available.

**Comment by RussTreadon-NOAA** [comment]
> > Why does our not being able to download test files from EMC RZDM break the GDASApp build? It should only break testing, not the build, right? Does cmake intertwine application testing with the application build in such a way that if we can't build the tests, we can't build GDASApp?
> 
> It's because CMake is doing the downloading. It fails, so CMake can't finish. Perhaps we should instead have a test that runs that downloads/links the files. This is how JCSDA does it for JEDI.

This is a good option.  It separates the application build from the application tests.  We should be able to compile GDASApp whether or not data for ctests is available.

**Review by guillaumevernieres — DISMISSED** [review]
The `test_gdasapp_util_ghrsst2ioda` job is failing too but isn't reported as failed. Can you update the references @apchoiCMD ?
The vrfy task is failing with an issue reading the layer thicknesses, not sure why ... 

This PR fixes the previous error, good enough to be merged. We'll comment out the `verify` test until one of us water people have time to look into it and fix the issue.

**Comment by apchoiCMD** [comment]
> The `test_gdasapp_util_ghrsst2ioda` job is failing too but isn't reported as failed. Can you update the references @apchoiCMD ? The vrfy task is failing with an issue reading the layer thicknesses, not sure why ...
> 
> This PR fixes the previous error, good enough to be merged. We'll comment out the `verify` test until one of us water people have time to look into it and fix the issue.

My bad but your PR #1050 already includes a modified test reference file https://github.com/NOAA-EMC/GDASApp/pull/1050/files#diff-68603b0771f7acb935fa0d121599ea74718ba8012d0e7dc7c1ee1a192150d93e Do you want me to update before merging your PR? Thanks @guillaumevernieres

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Pull request merged**
