### PR TITLE
Bugfix: Revival of the soca stand alone application

### LINKED ISSUE #125: PR#123 broke the soca stand alone application (static files need to be updated)
Self inflicted problem! Thanks for pointing out the issue @liuxiao37k .

Reason to remove this line? wouldn't we need to pre-create the directory to put the input*.nml files during `cmake`? `run_jedi_exe.py soca5deg.yaml` was complaining `input.nml doesn't exist`. See error message:
```
vi /work/noaa/ng-godas/xliu/prs/pr8/test-soca-gdasapp/test-5deg/GDASApp.o6570283
```

@guillaumevernieres

_Originally posted by @liuxiao37k in https://github.com/NOAA-EMC/GDASApp/pull/123#discussion_r956436790_

### PR DESCRIPTION
**Pull request by guillaumevernieres**
What the title says, a few minor bug fixes and some code tidy. 

 - fixes #125

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@CoryMartin-NOAA , @RussTreadon-NOAA , none of the ctests that we run on hpc cover the changes in this pr, I would suggest to skip the orion and hera ci ... But up to you.

**Review by RussTreadon-NOAA — COMMENTED** [review]
While existing ctests do not exercise the changes in this PR, do the changes in this PR revive the soca stand alone app?  If they do, let's get these changes into develop.   If not, what's missing to revive the soca stand alone app?

**Comment by guillaumevernieres** [comment]
> While existing ctests do not exercise the changes in this PR, do the changes in this PR revive the soca stand alone app? If they do, let's get these changes into develop. If not, what's missing to revive the soca stand alone app?

Yes, they do revive the stand alone GDASApp, that I broke a while back.

**Review by RussTreadon-NOAA — APPROVED** [review]
Thanks, @guillaumevernieres , for the confirmation.  Approve.

**Review by CoryMartin-NOAA — APPROVED** [review]
Changes look good to me

**Comment by guillaumevernieres** [comment]
Thanks for the quick review @RussTreadon-NOAA & @CoryMartin-NOAA

**Pull request merged**
