### PR TITLE
update jcb-gdas and soca hashes

### LINKED ISSUE #1367: Consolidate soca -> cice increments into one run
Consolidate converting soca increments + backgrounds -> cice restarts into one task (both for arctic and antarctic).

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
This PR updates the jcb-gdas and soca hashes.

Resolves #1367

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Running Hera CI as a final check but given [results](https://github.com/NOAA-EMC/GDASApp/issues/1367#issuecomment-2492077922) in #1367, automated CI should pass.   Once CI passes, we can merge this PR into GDASApp `develop` and update the GDASApp hash in g-w PR [#3118](https://github.com/NOAA-EMC/global-workflow/pull/3118).

**Review by shlyaeva — APPROVED** [review]
Thank you @RussTreadon-NOAA !

**Review by guillaumevernieres — APPROVED** [review]
Thanks @RussTreadon-NOAA

**Comment by RussTreadon-NOAA** [comment]
Test pass.  Two approvals.  Merge into `develop`

**Pull request merged**
