### PR TITLE
Added meridional section in the marine vrfy

### LINKED ISSUE #556: Add figures of meridional sections in the verify task
- [x] Build global-workflow/GDASApp
- [x] Run ctests
- [x] create a feature branch based off of develop:
```console
cd .../gdas.cd
git checkout -b feature/meridional-vrfy
```
- [x] Add zonal/meridional plotting capability in the vrfy task (python scripting), including a dedicated ```ctest```
See here: [soca_vrfy.py](https://github.com/NOAA-EMC/GDASApp/blob/develop/ush/soca/soca_vrfy.py)
- [x] Provide comments based on item 1 to enhance the Build document (see below)
https://docs.google.com/document/d/1ZL-Zbdv_ttGLxEmya0hmZmdycSuVhK-9bCzzbgAo0Pc/edit?pli=1

### PR DESCRIPTION
**Pull request by apchoiCMD**
## Description
Two python scripts were touched for adding plots of meridional section for vrfy job.

- fixes #556

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@apchoiCMD , can you point us to an example of a meridional section plotted with your code?

**Review by AndrewEichmann-NOAA — APPROVED** [review]
Code looks good

**Comment by apchoiCMD** [comment]
Saltmeridional_lon_-280_700m
Tempmeridional_lon_-280_700m

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Comment by AndrewEichmann-NOAA** [comment]
I missed that it didn't have the titles, which were added last week - The GDASApp branch needs develop merged in anyway, maybe add the title to it? It should be just a couple of lines.

**Comment by AndrewEichmann-NOAA** [comment]
Ah, never mind, it can be done later

**Comment by apchoiCMD** [comment]
I will discuss with Guillaume tomorrow, thanks for your help.

**Pull request merged**
