### PR TITLE
ocn to ocean

### LINKED ISSUE #938: Wrong naming of the static ensemble members
https://github.com/NOAA-EMC/GDASApp/blob/60c98b6a34689848c4c23e1e2f90414a906e0e66/scripts/exgdas_global_marine_analysis_prep.py#L166

It looks like I forgot to update the naming of the static members. `ocn` should have been `ocean` to stay consistent with the recent update ... 

- [x] #941

### PR DESCRIPTION
**Pull request by guillaumevernieres**
- fixes #938

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
We'll need to re-run the test after the current ones are done. Somebody forgot to switch hybvar to no ...

**Review by RussTreadon-NOAA — APPROVED** [review]
Approve pending successful CI tests

**Comment by guillaumevernieres** [comment]
I'm being impatient, there's a lot of waiting in the queue happening but the problematic tests are OK now when DOHYBVAR=NO.
Here's a screenshot of the status of the ctest as of a few mn's ago:
ci

grabbed from 
```
/scratch1/NCEPDEV/da/Cory.R.Martin/CI/GDASApp/workflow/PR/940/global-workflow/sorc/gdas.cd/build/log.ctest
```

We'll add the 2 tests in the future (HYBVAR=YES and NO).

**Comment by guillaumevernieres** [comment]
> Approve pending successful CI tests

Thanks @RussTreadon-NOAA .

**Review by apchoiCMD — APPROVED** [review]

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
