### PR TITLE
Only run 2 members for the marine hybrid

### PR DESCRIPTION
**Pull request by guillaumevernieres**
# Automated CI tests to run in Global Workflow

- [ ] atm_jjob 
- [ ] C96C48_ufs_hybatmDA 
- [ ] C96C48_hybatmaerosnowDA  
- [ ] C48mx500_3DVarAOWCDA 
- [x] C48mx500_hybAOWCDA 
- [ ] C96C48_hybatmDA

### CODE REVIEW

**Comment by DavidNew-NOAA** [comment]
@guillaumevernieres I didn't realize that without the checkboxes from the template I made in https://github.com/NOAA-EMC/GDASApp/pull/1401 for the PR description, none of the CI tests are actually run when you use the labels, only the GDASApp standalone tests. If you look at the CTest output for emcbot, it's:

```ctest -j12 -R gdasapp -E atm_jjob|C96C48_ufs_hybatmDA|C96C48_hybatmaerosnowDA|C48mx500_3DVarAOWCDA|C48mx500_hybAOWCDA|C96C48_hybatmDA```

meaning all those tests were excluded. When https://github.com/NOAA-EMC/GDASApp/pull/1401 is merged, that template will be included for all PRs.

**Comment by DavidNew-NOAA** [comment]
@guillaumevernieres Re my comment above, I added the checkboxes to your PR description and re-added the hera CI label.

**Review by danholdaway — APPROVED** [review]

**Review by AndrewEichmann-NOAA — APPROVED** [review]
Does this require changing any of the magic numbers in the scripts?

**Comment by guillaumevernieres** [comment]
> Does this require changing any of the magic numbers in the scripts?

Not in this repo.

**Pull request merged**
