### PR TITLE
Skip the ice specific diffusion

### PR DESCRIPTION
**Pull request by guillaumevernieres**
Companion PR to https://github.com/NOAA-EMC/jcb-gdas/pull/39

### CODE REVIEW

**Comment by jswhit2** [comment]
just ran a test on  hera (with this and https://github.com/NOAA-EMC/jcb-gdas/pull/39) and the gdas_marinebmat job now completes

**Review by jswhit2 — APPROVED** [review]

**Comment by jswhit2** [comment]
oops - spoke too soon.  I see this in the log for gdas_marinebmat

FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/NCEPDEV/stmp2/Jeffrey.S.Whitaker/RUNDIRS/C192coupled3dvar_test/gdas.2021032406/gdasmarineanalysis.2021032406/staticb/hz_ice.nc

**Comment by JohnSteffen-NOAA** [comment]
@jswhit2 That should be expected since we commented that line out, but I'm not sure what the downstream effects will be (if any).

**Comment by jswhit2** [comment]
This seems to fix it (at least gdas_marinebmat completes without errors)

```
diff --git a/ush/python/pygfs/task/marine_bmat.py b/ush/python/pygfs/task/marine_bmat.py
index a4a5b4f1..bae1e948 100644
--- a/ush/python/pygfs/task/marine_bmat.py
+++ b/ush/python/pygfs/task/marine_bmat.py
@@ -287,10 +287,10 @@ class MarineBMat(Task):
                                 f"{self.task_config.APREFIX}{diff_type}_ocean.nc")
             diffusion_coeff_list.append([src, dest])

-        src = os.path.join(self.task_config.DATAstaticb, f"hz_ice.nc")
-        dest = os.path.join(self.task_config.COMOUT_ICE_BMATRIX,
-                            f"{self.task_config.APREFIX}hz_ice.nc")
-        diffusion_coeff_list.append([src, dest])
+        #src = os.path.join(self.task_config.DATAstaticb, f"hz_ice.nc")
+        #dest = os.path.join(self.task_config.COMOUT_ICE_BMATRIX,
+        #                    f"{self.task_config.APREFIX}hz_ice.nc")
+        #diffusion_coeff_list.append([src, dest])

         FileHandler({'copy': diffusion_coeff_list}).sync()

```

**Comment by jswhit2** [comment]
however, gdas_marineanlinit fails with

```
Traceback (most recent call last):
  File "/scratch2/BMC/gsienkf/whitaker/global-workflow/scripts/exglobal_marine_analysis_initialize.py", line 24, in <module>
    MarineAnl.initialize()
  File "/scratch2/BMC/gsienkf/whitaker/global-workflow/ush/python/wxflow/logger.py", line 266, in wrapper
    retval = func(*args, **kwargs)
  File "/scratch2/BMC/gsienkf/whitaker/global-workflow/ush/python/pygfs/task/marine_analysis.py", line 119, in initialize
    self._prep_variational_yaml()
  File "/scratch2/BMC/gsienkf/whitaker/global-workflow/ush/python/wxflow/logger.py", line 266, in wrapper
    retval = func(*args, **kwargs)
  File "/scratch2/BMC/gsienkf/whitaker/global-workflow/ush/python/pygfs/task/marine_analysis.py", line 238, in _prep_variational_yaml
    jedi_config = render(jcb_config)
  File "/scratch2/BMC/gsienkf/whitaker/global-workflow/ush/python/jcb/renderer.py", line 268, in render
    return jcb_object.render(algorithm)
  File "/scratch2/BMC/gsienkf/whitaker/global-workflow/ush/python/jcb/renderer.py", line 199, in render
    jcb.abort_if('{{' in jedi_dict_yaml, f'In template_string_jinja2 '
  File "/scratch2/BMC/gsienkf/whitaker/global-workflow/ush/python/jcb/utilities/trapping.py", line 12, in abort_if
    raise ValueError(message)
ValueError: In template_string_jinja2 the output string still contains template directives. # Set the model component to be used in later configuration

```

**Comment by guillaumevernieres** [comment]
@jswhit2 , I got "lucky", looks like I had an `hz_ice.nc` file in `staticb` ... But yes, the lines you point to need to be removed. The variational step is going to fail now. There's a formatting issue somewhere. The bug fixes are in a gw pr, but I don't know when this will be looked at let alone merged. 
I have a variational job in the queue, I'll let you know if it's worth it to run anything or if the memory problem is on hera as well (it wasn't in @JohnSteffen-NOAA 's build).

**Comment by guillaumevernieres** [comment]
Back in business:  
mem-print

Same code, different compiler, different memory footprint.

**Comment by guillaumevernieres** [comment]
@jswhit2 , I isolated the needed fixes from my g-w pr here:
https://github.com/guillaumevernieres/global-workflow/tree/bugfix/config-str-int

can you work on C6?

**Comment by jswhit2** [comment]
@guillaumevernieres can't use c6 until all the builds support it - there's a bunch of PRs from @DavidBurrows-NCO  in to make this happen, and as soon as they are merged I'll give it a try

**Comment by guillaumevernieres** [comment]
I'm closing this. The bug fixes will be included in https://github.com/NOAA-EMC/global-workflow/pull/3034 and https://github.com/NOAA-EMC/GDASApp/pull/1353

**Pull request closed without merging**
