### PR TITLE
Adding AHI and SEVIRI satwnd thinning, enrolling AHI-H9, SEVIRI-M9, SEVIRI-M10

### PR DESCRIPTION
**Pull request by BrettHoover-NOAA**
This PR enrolls AHI-Himawari9, SEVIRI-METEOSAT9, and SEVIRI-METEOSAT10 satwnd types into JEDI, and establishes thinning for AHI and SEVIRI satwnd observations in their corresponding *.yaml.j2 files. This is the NOAA-EMC/GDASApp portion of the work, which enrolls the updated AHI and SEVIRI satwnd types in the bufr2ioda JSON files.

This is dependent on https://github.com/NOAA-EMC/jcb-gdas/pull/25, which has the corresponding yaml.j2 files for AHI and SEVIRI satwnd observations and the thinning filters.

Thinning tests to define the filter settings can be found in https://github.com/NOAA-EMC/GDASApp/issues/1143

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@BrettHoover-NOAA go ahead and update the JCB-GDAS hash

**Review by nicholasesposito — DISMISSED** [review]
Looks fine

**Review by PraveenKumar-NOAA — DISMISSED** [review]
Looks good to me.

**Comment by CoryMartin-NOAA** [comment]
@BrettHoover-NOAA please update the jcb-gdas hash in this PR and then it should be ready to merge

**Comment by BrettHoover-NOAA** [comment]
> @BrettHoover-NOAA please update the jcb-gdas hash in this PR and then it should be ready to merge

@CoryMartin-NOAA how do i update the jcb-gdas hash?

**Comment by CoryMartin-NOAA** [comment]
@BrettHoover-NOAA 
`cd parm/jcb-gdas`
`git checkout develop`
`cd ../`
`git add jcb-gdas`
`git commit`

I think that should do the trick.

**Comment by BrettHoover-NOAA** [comment]
@CoryMartin-NOAA Doesn't seem to work, `jcb-gdas` doesn't show up as something to add when I do a `git status` after checking out develop branch in parm/jcb-gdas

**Comment by BrettHoover-NOAA** [comment]
I'm going to update with `develop` here and pull a fresh version to local repository before doing anything

**Comment by CoryMartin-NOAA** [comment]
@BrettHoover-NOAA you might need to do a git pull on the `jcb-gdas` submodule once you are in develop to ensure you are getting the latest hash there

**Comment by BrettHoover-NOAA** [comment]
@CoryMartin-NOAA I'm running into an issue with which branch updates what. I can move to `parm/jcb-gdas` and checkout `develop`, and perform a `git pull` and bring the hash up to date. But when I move back to `GDASApp/` I'm still on the `develop` branch. If I checkout the `feature/add_satwnd_thinning` branch, it reverts `parm/jcb-gdas` to its original hash. I can't seem to update `jcb-gdas` hash on my feature branch.

**Comment by CoryMartin-NOAA** [comment]
@BrettHoover-NOAA are you on your feature branch before you try to `cd parm/jcb-gdas` and checkout/pull develop inside of there? This sounds odd.

**Comment by BrettHoover-NOAA** [comment]
@CoryMartin-NOAA The sequence I have been trying is:
start in feature branch of GDASApp
`cd parm/jcb-gdas`
`checkout develop`
`git pull`
`cd ../..` back to GDASApp
now I am in `develop` branch of GDASApp. I can checkout my feature branch from here, but it reverts `jcb-gdas` back to whatever hash it was set on in the feature branch.

Is there a step I'm missing?

**Comment by CoryMartin-NOAA** [comment]
@BrettHoover-NOAA I just did the following:
```
   19  git checkout -b feature/test
   20  git branch
   21  git status
   22  cd jcb-gdas/
   23  git checkout develop
   24  git log
   25  cd ..
   26  git branch
   27  history
   28  git status
   29  history
```
and I see with `git status`

```
On branch feature/test
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   jcb-gdas (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
```

So it seems it is working for me. I wonder if by some chance your submodules are screwed up.

When you cd into `jcb-gdas` what does `git remote -v` say? It should say 
```
origin	https://github.com/noaa-emc/jcb-gdas (fetch)
origin	https://github.com/noaa-emc/jcb-gdas (push)
```
I fear it may say
```
origin	https://github.com/NOAA-EMC/GDASApp.git (fetch)
origin	https://github.com/NOAA-EMC/GDASApp.git (push)
```

**Comment by BrettHoover-NOAA** [comment]
@CoryMartin-NOAA it is as you feared:
```
git remote -v
origin	https://github.com/NOAA-EMC/GDASApp.git (fetch)
origin	https://github.com/NOAA-EMC/GDASApp.git (push)
```

**Comment by CoryMartin-NOAA** [comment]
@BrettHoover-NOAA huh weird. Well I vote we don't worry too much about this and I can push the updated hash to this branch, does that work for you?

**Comment by BrettHoover-NOAA** [comment]
@CoryMartin-NOAA sure, that works fine for me

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
