### PR TITLE
Change hydrostatic_delz to delz

### PR DESCRIPTION
**Pull request by DavidNew-NOAA**
This PR is a companion to FV3-JEDI PR [#1263](https://github.com/JCSDA-internal/fv3-jedi/pull/1263) and JCB-GDAS PR [#27](https://github.com/NOAA-EMC/jcb-gdas/pull/27). It changes ```hydrostatic_delz``` to ```delz``` in the FV3 increment fields metadata override file, along with the test input and reference file for one CTest. See the above referenced FV3-JEDI PR for motivation and other details.

The gdasapp_fv3jedi_fv3inc CTest passes with these changes.

### CODE REVIEW

**Comment by DavidNew-NOAA** [comment]
I'm rolling this PR into another one, so will close it.

**Review by RussTreadon-NOAA — DISMISSED** [review]
Did not test but changes look good.

**Comment by RussTreadon-NOAA** [comment]
@danholdaway , if you have a chance would you take a look at this PR from @DavidNew-NOAA.  We need the changes in this PR if we update the fv3-jedi hash.

**Comment by RussTreadon-NOAA** [comment]
Testing of these changes along reported in jcb-gdas PR [#27.](https://github.com/NOAA-EMC/jcb-gdas/pull/27)  Combination of these two PRs works!

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA, once jcb-gdas PR [#27](https://github.com/NOAA-EMC/jcb-gdas/pull/27) is merged into jcb-gdas `develop`, we need to update the `parm/jcb-gdas` hash in this PR.

**Comment by RussTreadon-NOAA** [comment]
jcb-gdas PR [#27](https://github.com/NOAA-EMC/jcb-gdas/pull/27) merged.  Done at [272d6d7](https://github.com/NOAA-EMC/jcb-gdas/commit/272d6d73c0ceea5332fee005f59b3270527d10c7).

**Review by RussTreadon-NOAA — APPROVED** [review]
jcb-gdas at [272d6d7](https://github.com/NOAA-EMC/jcb-gdas/commit/272d6d73c0ceea5332fee005f59b3270527d10c7) replaces `hydrostatic_delz` with `delz`.  This is correct.

Approve.

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA , the jcb-gdas hash has been updated in `feature/hydrostatic-delz`.  Given your confirmation that everything looks correct,  we can merge into `develop`.

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA Looks good. Let's merge it

**Comment by danholdaway** [comment]
Just catching up, sick kid. Is it safe to update the hash of just fv3-jedi and not other JEDI repos?

**Comment by DavidNew-NOAA** [comment]
@danholdaway I tested it in an experiment on Hera GW without a problem, though only one cycle.

**Comment by DavidNew-NOAA** [comment]
@danholdaway Also, the jjob tests passed for @RussTreadon-NOAA https://github.com/NOAA-EMC/jcb-gdas/pull/27#issuecomment-2369208392

**Pull request merged**
