### PR TITLE
ioda+bump updates

### PR DESCRIPTION
**Pull request by guillaumevernieres**
The changes below should fix the soca ctests:
- Update of the test ioda files. We're no longer using what's in the tarball
- Changed the few obs yamls used for the testing, the rest will be updated in a distant future.
- Some of the bump keys were updated too

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
Changes look OK.    Do the proposed changes pass existing ctests?

**Comment by RussTreadon-NOAA** [comment]
> 80577cf

I see that [80577cf](https://github.com/NOAA-EMC/GDASApp/pull/305/commits/80577cf65d30327a70a12be004f684bc7f8797ae) passes automated tests.  What about ctests triggered by GW-RT labels?

**Comment by guillaumevernieres** [comment]
> > [80577cf](https://github.com/NOAA-EMC/GDASApp/commit/80577cf65d30327a70a12be004f684bc7f8797ae)
> 
> I see that [80577cf](https://github.com/NOAA-EMC/GDASApp/pull/305/commits/80577cf65d30327a70a12be004f684bc7f8797ae) passes automated tests. What about ctests triggered by GW-RT labels?

Thanks for the review @RussTreadon-NOAA . The soca ctest are ok, I haven't checked the atm/land test, I suspect no if the yamls/obs used in the testing have not been updated.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , if soca ctests pass, that's enough for this PR.

**Review by RussTreadon-NOAA — APPROVED** [review]
soca ctests pass.   approve.

**Review by nicholasesposito — COMMENTED** [review]
Looks good.

**Pull request merged**
