### PR TITLE
Fix Marine VRFY Task in the SOCA ctests

### LINKED ISSUE #829: Fix marine vrfy job
EVA yamls need to be updated, and probably $PYTHONPATH needs to be revised. See https://github.com/NOAA-EMC/GDASApp/pull/828 for more information

### PR DESCRIPTION
**Pull request by apchoiCMD**
#### What this PR includes:

- Fix test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY

by updating `marine_gdas_plots.yaml` format and it related `marine_eva_post.py`

- <del>As of now, ctests passed on `Hera Machine` and `Orion Machine` is still needed to check</del>
- ctests passed on both `Hera Machine` and `Orion Machine`, see https://github.com/NOAA-EMC/GDASApp/issues/829

Fixes #829

Thanks to @CoryMartin-NOAA

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
Looks like the key was to add `figure list`.  I don't know eva well enough to know if this is correct.  Since it worked on Hera, I assume it's correct.

Approve pending confirmation that the proposed changes work on Hera and Orion.   FYI, we can also run GDASApp on Hercules but this platform is not yet part of GDASApp CI.

**Comment by apchoiCMD** [comment]
> Looks like the key was to add `figure list`. I don't know eva well enough to know if this is correct. Since it worked on Hera, I assume it's correct.
> 
> Approve pending confirmation that the proposed changes work on Hera and Orion. FYI, we can also run GDASApp on Hercules but this platform is not yet part of GDASApp CI.

Thanks for the quick reply and information you provide. I will update it once tests on Orion is done.

**Comment by ShastriPaturi** [comment]
@apchoiCMD VRFY ctest fails on orion for me.

**Review by guillaumevernieres — APPROVED** [review]
Thanks for sorting this out @apchoiCMD and @RussTreadon-NOAA !

**Comment by RussTreadon-NOAA** [comment]
> Thanks for sorting this out @apchoiCMD and @RussTreadon-NOAA !

Credit goes to @apchoiCMD for getting VRFY working again.  I simply noted the failure.

**Comment by apchoiCMD** [comment]
> > Thanks for sorting this out @apchoiCMD and @RussTreadon-NOAA !
> 
> Credit goes to @apchoiCMD for getting VRFY working again. I simply noted the failure.

Everyone gets credits while working together- @RussTreadon-NOAA  and the hidden helper was @CoryMartin-NOAA , thanks to everyone for helping me.

**Pull request merged**
