### PR TITLE
Tier-2 tests

### PR DESCRIPTION
**Pull request by guillaumevernieres**
Tier-2 tests would not be part of the regular GDASApp CI and would only be executed prior to submitting a PR of `dev/gdasapp` into `develop`.  

Untested.

@CoryMartin-NOAA , @RussTreadon-NOAA , could you give me a sequential list of the `jjobs` that you want tested? That or commit directly to my branch. What needs to be updated is here
https://github.com/NOAA-EMC/GDASApp/blob/6f27a49964429e23814eaeef1ba32857dbf41606/test/gw-ci/CMakeLists.txt#L61
and here
https://github.com/NOAA-EMC/GDASApp/blob/6f27a49964429e23814eaeef1ba32857dbf41606/test/gw-ci/CMakeLists.txt#L68
and the marine DA example is here:
https://github.com/NOAA-EMC/GDASApp/blob/6f27a49964429e23814eaeef1ba32857dbf41606/test/gw-ci/CMakeLists.txt#L47

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
g-w C96C48_ufs_hybatmDA CI runs the following jobs

- 20240223 18Z half cycle 
   - gdasfcst and gdasatmos_prod_f*
   - enkfgdasfcst_mem[001, 002] and enkfgdasepos*
- 20240224 00Z full cycle - g-w CI also run gfs jobs but these can be omitted for GDASApp CI
   - gdasprep
   - gdasprepatmiodaobs
   - gdasatmanlinit
   - gdasatmanlvar
   - gdasatmanlfv3inc
   - gdasatmanlfinal
   - enkfgdasatmensanlinit
   - enkfgdasatmensanlletkf
   - enkfgdasatmensanlfv3inc
   - enkfgdasatmensanlfinal

g-w CI runs jobs after the above DA jobs finish.  This is useful since it ensures the generated analysis increment files are readable by downstream jobs.  However, adding these downstream jobs to GDASApp CI is too much at this point.

**Comment by CoryMartin-NOAA** [comment]
I probably won't be able to get you a list of aero+snow jobs until early next week, so don't wait for me if you want to proceed with this PR, otherwise I can get that to you Mon or Tues

**Comment by guillaumevernieres** [comment]
I updated the non-existent PR description @RussTreadon-NOAA , but the idea is to not run these as part of the regular GDASApp CI, but rather only prior to doing a PR in the global-workflow develop.

**Comment by guillaumevernieres** [comment]
These are the new tests added:
```
  Test #25: WCDA-3DVAR-C48mx500
  Test #26: WCDA-3DVAR-C48mx500_gdasfcst_202103241200
  Test #27: WCDA-3DVAR-C48mx500_enkfgdasfcst_001_202103241200
  Test #28: WCDA-3DVAR-C48mx500_enkfgdasfcst_000_202103241200
  Test #29: WCDA-3DVAR-C48mx500_gdasprepoceanobs_202103241800
  Test #30: WCDA-3DVAR-C48mx500_gdasocnanalprep_202103241800
  Test #31: WCDA-3DVAR-C48mx500_gdasocnanalbmat_202103241800
  Test #32: WCDA-3DVAR-C48mx500_gdasocnanalrun_202103241800
  Test #33: WCDA-3DVAR-C48mx500_gdasocnanalchkpt_202103241800
  Test #34: WCDA-3DVAR-C48mx500_gdasocnanalpost_202103241800
  Test #35: Aero-Snow-3DVAR-C96
  Test #36: Aero-Snow-3DVAR-C96_gdasfcst_202112201200
  Test #37: Aero-Snow-3DVAR-C96_enkfgdasfcst_001_202112201200
  Test #38: Aero-Snow-3DVAR-C96_enkfgdasfcst_000_202112201200
  Test #39: Atm-hyb-C96C48
  Test #40: Atm-hyb-C96C48_gdasfcst_202402231800
  Test #41: Atm-hyb-C96C48_enkfgdasfcst_001_202402231800
  Test #42: Atm-hyb-C96C48_enkfgdasfcst_002_202402231800
  Test #43: Atm-hyb-C96C48_gdasprep_202402240000
  Test #44: Atm-hyb-C96C48_gdasprepatmiodaobs_202402240000
  Test #45: Atm-hyb-C96C48_gdasatmanlinit_202402240000
  Test #46: Atm-hyb-C96C48_gdasatmanlvar_202402240000
  Test #47: Atm-hyb-C96C48_gdasatmanlfv3inc_202402240000
  Test #48: Atm-hyb-C96C48_gdasatmanlfinal_202402240000
  Test #49: Atm-hyb-C96C48_enkfgdasatmensanlinit_202402240000
  Test #50: Atm-hyb-C96C48_enkfgdasatmensanlletkf_202402240000
  Test #51: Atm-hyb-C96C48_enkfgdasatmensanlfv3inc_202402240000
  Test #52: Atm-hyb-C96C48_enkfgdasatmensanlfinal_202402240000
  Test #53: GFSv17-3DVAR-C384mx025
  Test #54: GFSv17-3DVAR-C384mx025_gdasfcst_202106300000
  Test #55: GFSv17-3DVAR-C384mx025_enkfgdasfcst_001_202106300000
  Test #56: GFSv17-3DVAR-C384mx025_enkfgdasfcst_000_202106300000
  Test #57: GFSv17-3DVAR-C384mx025_gdasprepoceanobs_202106300600
  Test #58: GFSv17-3DVAR-C384mx025_gdasocnanalprep_202106300600
  Test #59: GFSv17-3DVAR-C384mx025_gdasocnanalbmat_202106300600
  Test #60: GFSv17-3DVAR-C384mx025_gdasocnanalrun_202106300600
  Test #61: GFSv17-3DVAR-C384mx025_gdasocnanalchkpt_202106300600
  Test #62: GFSv17-3DVAR-C384mx025_gdasocnanalpost_202106300600
  Test #63: GFSv17-3DVAR-C384mx025_gdasocnanalvrfy_202106300600
  Test #64: GFSv17-3DVAR-C384mx025_gdasprep_202106300600
  Test #65: GFSv17-3DVAR-C384mx025_gdasanal_202106300600
  [...]

Total Tests: 77
```
... and as I'm seeing that list, I'm thinking we probably need a new label or a way to trigger only a subset of these.

**Review by RussTreadon-NOAA — COMMENTED** [review]
While I see `Tier-2` testing was a [SUCCESS](https://github.com/NOAA-EMC/GDASApp/pull/1185#issuecomment-2215897838) , we don't see a _hera-GW-RT-tier2-Passed_ label.   

A check of labels only shows _hera-GW-RT-tier2_.  Do we need to add _Running_, _Failed_, _Passed_ labels for _hera-GW-RT-tier2_?

**Comment by guillaumevernieres** [comment]
> While I see `Tier-2` testing was a [SUCCESS](https://github.com/NOAA-EMC/GDASApp/pull/1185#issuecomment-2215897838) , we don't see a _hera-GW-RT-tier2-Passed_ label.
> 
> A check of labels only shows _hera-GW-RT-tier2_. Do we need to add _Running_, _Failed_, _Passed_ labels for _hera-GW-RT-tier2_?

Sorry for the confusion @RussTreadon-NOAA . The tier-2 test actually did not run, but even if they did, only the GW-RT label would be updated. The label is just there to trigger the tier-2 test, I could rename it to `tier-2` only to make it less confusing?

**Comment by RussTreadon-NOAA** [comment]
Thanks @guillaumevernieres for the explanation.   I think renaming the tier-2 test trigger label would be helpful.  Would the `tier-2` label trigger jobs on only Hera or would it also trigger jobs on Orion?

**Comment by guillaumevernieres** [comment]
> Thanks @guillaumevernieres for the explanation. I think renaming the tier-2 test trigger label would be helpful. Would the `tier-2` label trigger jobs on only Hera or would it also trigger jobs on Orion?

You could trigger them on other machines, but currently the marine DA ones would fail. We've been meaning to update the yamls in the g-w ... On our todo list.

**Comment by RussTreadon-NOAA** [comment]
Got it.  The `hera-GW-RT-tier2` currently works as the trigger on Hera.  Given this, we can keep things simple, retain this label, and revisit (if needed) later.

**Review by RussTreadon-NOAA — DISMISSED** [review]
Approve.

**Comment by guillaumevernieres** [comment]
Not sure what I did but the tier-2 is not triggered anymore ... Great.
I'll do some debugging while working on the g-w b-matrix pr.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres should we keep this PR alive or close it?

**Pull request closed without merging**
