### PR TITLE
A few updates to adapt soca to the G-W UFS output 

### LINKED ISSUE #289: [bug] Thickness field isn't copied into the IAU increment
Not quite sure what happened, but something's broken.

### LINKED ISSUE #318: Add the BMAT_VRFY j-job to the g-w ctest
What the title says ... It's currently not working when added to the `yaml` of the single cycle application, I forgot why.

### LINKED ISSUE #321: Setup the pseudo model to read 3 hourly ocean/ice backgrounds
Currently hard-coded to 1 hour. Change to 3 or make it as a configurable.

### LINKED ISSUE #322: Make the pseudo model read the CICE history files instead of the "aggregated" restarts
We've got all we need in the history dumped by CICE. Process the files so they can be read by `soca/fms`.

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
The goal of this pr/work is to run the marine DA tasks in the global workflow without issues. 

### What was done
- fixes #321 
- fixes #322 
- fixes #289 
- fixes #318 

### What's left to do before un-drafting 
- [x] Upload `cice_hist.nc`, a dummy cice history file, to the EMC ftp server.
- [x] Cycle with the gw
- [x] Wait for [global-workflow/pull/1302](https://github.com/NOAA-EMC/global-workflow/pull/1302) to be merged

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@CoryMartin-NOAA , @RussTreadon-NOAA , @AndrewEichmann-NOAA and whomever would have an opinion on the subject:

I keep running into this issue when issuing a bugfix in the `global-workflow` to fix one of our ctest in this repo: In the automated ci, we don't do a ```git pull``` in the global-workflow sandbox, which means that when we resubmit the `ci` to hpc, the bugfix in the global-workflow was not fetched, and so the `ci` fails again. 

Any objection to pull the recent commit of the `g-w` develop branch as part of the `ci` submitted to hpc?

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres do you mean that our g-w branch is out of date? or that the CI is not including an update after it already started? Do we need a separate updating bot to update our g-w branch?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres do you mean that our g-w branch is out of date? or that the CI is not including an update after it already started? Do we need a separate updating bot to update our g-w branch?

Yes @CoryMartin-NOAA , the g-w branch is out of date. The g-w branch for the workflow was merged yesterday, but the g-w ci sandbox does not include the change. Couldn't we just "git pull" in the g-w sandbox before building? 

Adding a `git pull` before [run_gw_ci.sh#L45 ](https://github.com/NOAA-EMC/GDASApp/blob/a48f236da65bfefa0d99cc81672f0eb3944d6901/ci/run_gw_ci.sh#L45) ?

**Comment by guillaumevernieres** [comment]
> Automated Global-Workflow GDASApp Testing Results: Machine: orion
> 
> ```
> Start: Wed Feb  8 17:46:45 CST 2023 on Orion-login-1.HPC.MsState.Edu
> ---------------------------------------------------
> Build:                                 *SUCCESS*
> Build: Completed at Wed Feb  8 18:14:00 CST 2023
> ---------------------------------------------------
> Tests:                                  *Failed*
> Tests: Failed at Wed Feb  8 18:31:17 CST 2023
> Tests: 98% tests passed, 1 tests failed out of 43
> 	1361 - test_gdasapp_run_jedi_exe_3dvar (Failed)
> Tests: see output at /work2/noaa/stmp/cmartin/CI/GDASApp/workflow/PR/324/global-workflow/sorc/gdas.cd/build/log.ctest
> ```

I don't know why `test_gdasapp_run_jedi_exe_3dvar` failed on Orion @RussTreadon-NOAA , I had a look at the log thinking that the test ran out of time, but it seems like there might be a legit issue on orion:
```
m_berror_stats::get_dims: Reading berror from NetCDF file
 *** Finish reading file: .//berror/gsi-coeffs-gfs-global.nc4
 *** Finish reading file: .//berror/gsi-coeffs-gfs-global.nc4
ObsRadianceCRTM channels: [1-15]
ABORT: FieldMetadata::getLongNameFromAnyName: Searching for a field called surface_geometric_height in the long, short and io names but not found anywhere.
       in file '/work2/noaa/stmp/cmartin/CI/GDASApp/workflow/PR/324/global-workflow/sorc/gdas.cd/fv3-jedi/src/fv3jedi/FieldMetadata/FieldsMetadata.cc', line 142
Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
```
I don't think this is an issue with this PR, but it's not that trivial, with all these automated merges, I hope I didn't mess up your test!

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , I checked the log file and the run directory for `test_gdasapp_run_jedi_exe_3dvar`.   This is a false negative.   

The yaml was correctly created and a job submitted.   The check on the jobid failed 
```
++ grep Submitted stdout.txt
++ awk '-F ' '{print $4}'
+ jobid=
+ scancel
scancel: error: No job identification provided
+ rc=1
```

even though the jobid is in `stdout.txt`

```
2023-02-09 00:24:06,580 - INFO - localdb - shared: fetch from /work2/noaa/da/cmartin/GDASApp/R2D2_SHARED/ncdiag/ob/oper_gdas/PT6H/2021-12-21/ncdiag.oper_gdas.ob.PT6H.sondes.2021-12-21T03:00:00Z.nc4 to .//obs/gdas.t06z.sondes.2021122106.nc4
2023-02-09 00:24:06,583 - INFO - r2d2 - Success

Submitted batch job 8915212
```

Was the system still flushing the buffer to file `stdout.txt` when the script checked for the presence of the jobid?   This is certainly possible on Orion which has disk performance issues.

How to fix this:
- execute `sleep 5` before checking `stdout.txt` 
- execute `sync stdout.txt` before checking `stdout.txt`
- other ideas?

**Review by RussTreadon-NOAA — APPROVED** [review]
Changes look OK to me.   Approve.

**Pull request merged**
