### PR TITLE
Feature/add cris

### PR DESCRIPTION
**Pull request by joshk24**
Closes Issue #74 ; required PR #89 in order to work. Update: appeared to work with all obs types running (memory not an issue), so we can now leave the yamls uncommented on gdas_prototype.

crisfsr_n20_jvg
crisfsr_n20_omb

crisfsr_npp_jvg
crisfsr_npp_omb

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
Note to reviewers, we had to turn off all QC because there were some issues where it was looking for 'VarMetaData' variables as part of the QC functions. @emilyhcliu did you add those for CrIS?

**Comment by CoryMartin-NOAA** [comment]
@joshk24 is there a reason why it is marked as draft? Perhaps because `gdas_prototype.yaml` is all commented out?

**Comment by joshk24** [comment]
@CoryMartin-NOAA yep, we're checking to see if the whole thing runs with the cris files include, or if we have to comment them out (leaving the others uncommented)

**Review by ADCollard — APPROVED** [review]

**Review by CoryMartin-NOAA — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
