### PR TITLE
restore ATM local ensemble ctest functionality

### LINKED ISSUE #1002: Define EUPD_CYC for ATM local ensemble ctest
g-w commit [47302153](https://github.com/NOAA-EMC/global-workflow/commit/47302153f13f6b23539be841b78ed78664599c08) replaced 
```
export EUPD_CYC="gdas"
```
in `parm/config/gfs/config.base` with
```
export EUPD_CYC="@EUPD_CYC@"
```
The default value for `EUPD_CYC` is provided in `parm/config/gfs/yaml/defaults.yaml`
```
EUPD_CYC: "gdas"
```
The `config.yaml` used by `test_gdasapp_atm_jjob_ens` needs to be updated accordingly.

This issue is opened to document this update.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
g-w `develop` commit [47302153](https://github.com/NOAA-EMC/global-workflow/commit/47302153f13f6b23539be841b78ed78664599c08) modified how `EUPD_CYC` is set in `config.base`.  This variable is now set in a configuration yaml.   This requires a change in how `test_gdasapp_atm_jjob_ens` is configured.  This PR include the required change.

Fixes #1002

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
The `test_gdasapp_fv3jedi_fv3inc` and `test_gdasapp_atm_jjob_var_run` failures appear to be related to GDASApp hash 18ba5da.  Does this sound reasonable @DavidNew-NOAA ?

**Comment by RussTreadon-NOAA** [comment]
`test_gdasapp_atm_jjob_ens` _Passed_ with the changes in this PR
```
50/53 Test #1773: test_gdasapp_atm_jjob_ens_init ........................   Passed   44.25 sec
      Start 1774: test_gdasapp_atm_jjob_ens_run
51/53 Test #1774: test_gdasapp_atm_jjob_ens_run .........................   Passed  330.24 sec
      Start 1775: test_gdasapp_atm_jjob_ens_final
52/53 Test #1775: test_gdasapp_atm_jjob_ens_final .......................   Passed   42.24 sec
```
As such, I think this PR is ready for review, approval, and merger into GDASApp `develop`.

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA :  I see g-w PR [#2420](https://github.com/NOAA-EMC/global-workflow/pull/2420).  I assume that if I build `RussTreadon-NOAA:feature/eupd_cyc` inside a working copy of `DavidNew-NOAA:feature/jediinc2fv3`, the _Failed_ tests in this PR should change to _Passed_.  Does this sound right?

**Comment by DavidNew-NOAA** [comment]
> @DavidNew-NOAA : I see g-w PR [#2420](https://github.com/NOAA-EMC/global-workflow/pull/2420). I assume that if I build `RussTreadon-NOAA:feature/eupd_cyc` inside a working copy of `DavidNew-NOAA:feature/jediinc2fv3`, the _Failed_ tests in this PR should change to _Passed_. Does this sound right?

@RussTreadon-NOAA Yes, that's correct for the test_gdasapp_fv3jedi_fv3inc test. I assume that's the case for the test_gdasapp_atm_jjob_var_run, but I'm realizing now that I may have needed to modify those jjob tests in the my GDASApp PR, given that g-w PR [#2420](https://github.com/NOAA-EMC/global-workflow/pull/2420) changes the structure and names of two atmanl jobs. I need to investigate.

**Comment by DavidNew-NOAA** [comment]
OK, so JGLOBAL_ATM_ANALYSIS_RUN is now JGLOBAL_ATM_ANALYSIS_VARIATIONAL in g-w branch feature/jediinc2fv3 will break the test_gdasapp_atm_jjob_var_run test. I will need to do a quick bugfix PR into GDASApp develop. Thanks for feedback.

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA , thanks for letting me know.  Instead of you opening a new issue to fix ATM variational ctest functionality, I can modify the description of this issue and make the change in my branch.  Does this work for you?

**Comment by DavidNew-NOAA** [comment]
> @DavidNew-NOAA , thanks for letting me know. Instead of you opening a new issue to fix ATM variational ctest functionality, I can modify the description of this issue and make the change in my branch. Does this work for you?

@RussTreadon-NOAA Sure, that would be great, thank you. However, in addition do modifying the run job test, a new test will need to be made for the new job JGLOBAL_ATM_ANALYSIS_FV3_INCREMENT (gdasatmanlfv3inc), which is added in feature/jediinc2fv3.

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA:  OK, I see.  I jumped before looking.  While the changes for adding an new job step are straight forward, I may not get everything in place and tested before I go on leave COB tomorrow.  Given this, it's preferable to limit this PR to `test_atm_jjob_ens` and open a new issue & PR to expand `test_atm_jjob_var` to with with the new job.

**Comment by DavidNew-NOAA** [comment]
Ok, sounds good.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , @guillaumevernieres , or @DavidNew-NOAA :  would one of you review these changes and approve so we can merge this fix into GDASApp `develop`.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
Thank you @CoryMartin-NOAA .  Merging now.

**Review by RussTreadon-NOAA — COMMENTED** [review]
Simple fix

**Comment by DavidNew-NOAA** [comment]
Hi Russ,

To clarify, do you want me to open this issue and PR since you'll be on
leave?

David

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA :  Yes, please open an issue to document the fact that the `test_gdasapp_atm_jjob_var` suite is now incomplete given the new fv3inc job.

**Pull request merged**
