### PR TITLE
Rename mtiasi to iasi 

### PR DESCRIPTION
**Pull request by emilyhcliu**
1. Rename mtiasi to iasi in GDASApp
2. There is a companion [PR #29](https://github.com/NOAA-EMC/jcb-gdas/pull/29) in jcb-gdas
- rename mtiasi to iasi
- add `reduce obs space`
- remove obsolete QC-flag related variables in filters

This partly resolves Issue #1291

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
This changes in this PR are necessary but not sufficient.  

Build feature/iasi inside g-w PR [#2985](https://github.com/NOAA-EMC/global-workflow/pull/2875).  test_gdasapp works apart from know failures due to g-w PR [#2920](https://github.com/NOAA-EMC/global-workflow/pull/2920) not yet being in `develop`.
```
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/radbcor_iasi/sorc/gdas.cd/build
      Start 1531: test_gdasapp_util_coding_norms
 1/46 Test #1531: test_gdasapp_util_coding_norms .....................................   Passed    2.50 sec
      Start 1532: test_gdasapp_util_ioda_example
 2/46 Test #1532: test_gdasapp_util_ioda_example .....................................   Passed    2.93 sec
      Start 1533: test_gdasapp_util_prepdata
 3/46 Test #1533: test_gdasapp_util_prepdata .........................................   Passed    1.24 sec

...

      Start 1912: test_gdasapp_atm_jjob_ens_final
45/46 Test #1912: test_gdasapp_atm_jjob_ens_final ....................................   Passed   42.36 sec
      Start 1913: test_gdasapp_aero_gen_3dvar_yaml
46/46 Test #1913: test_gdasapp_aero_gen_3dvar_yaml ...................................   Passed    0.80 sec

87% tests passed, 6 tests failed out of 46

Label Time Summary:
gdas-utils    =  10.06 sec*proc (13 tests)
manual        = 1433.11 sec*proc (9 tests)
script        =  10.06 sec*proc (13 tests)

Total Test time (real) = 2666.47 sec

The following tests FAILED:
        1893 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasprepoceanobs_202103241800 (Failed)
        1894 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarinebmat_202103241800 (Failed)
        1895 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlinit_202103241800 (Subprocess killed)
        1896 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlvar_202103241800 (Subprocess killed)
        1897 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlchkpt_202103241800 (Subprocess killed)
        1898 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlfinal_202103241800 (Subprocess killed)
```

Tests with g-w CI adding metop-b iasi fail.  Changes are needed in 
- `parm/jcb-gdas/observation_chronicle`
- `parm/jcb-gdas/observations/atmosphere-lgetkf`
- `parm/jcb-gdas/observations/atmosphere`

These directories contain files named `mtiasi*`  
```
observation_chronicle/atmosphere/mtiasi_metop-a.yaml
observation_chronicle/atmosphere/mtiasi_metop-b.yaml
observations/atmosphere-lgetkf/mtiasi_metop-a.yaml.j2
observations/atmosphere-lgetkf/mtiasi_metop-b.yaml.j2
observations/atmosphere/mtiasi_metop-a.yaml.j2
observations/atmosphere/mtiasi_metop-b.yaml.j2
```

These files need to be git moved to
```
observation_chronicle/atmosphere/iasi_metop-a.yaml
observation_chronicle/atmosphere/iasi_metop-b.yaml
observations/atmosphere-lgetkf/iasi_metop-a.yaml.j2
observations/atmosphere-lgetkf/iasi_metop-b.yaml.j2
observations/atmosphere/iasi_metop-a.yaml.j2
observations/atmosphere/iasi_metop-b.yaml.j2
```

**Comment by RussTreadon-NOAA** [comment]
Attempt to run g-w _C96C48_ufs_hybatmDA_ CI job gdasatmanlvar with Metop-B IASI on Hera.  Job aborted because IASI bias correction files were not present.  Add them to `COMROOT` and reran.  Job failed with OOM error.  Job was running 96 tasks on 8 nodes (12 tasks per node).  Hera compute nodes have 96 Gb.  Increase node count to 48, 2 tasks per node, and rerun.  Job still fails with OOM errors.  

@emilyhcliu , you mentioned _reduced obs space_.  How is this configured in the yaml?

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA I thought no one had reviewed my PR yet.  
Thanks so much for reviewing. 

The `reduce obs space` is added to the thinning filter as the following:
https://github.com/NOAA-EMC/jcb-gdas/blob/4f60151866386c3a61dc53cabad9652b5ebda84c/observations/atmosphere/iasi_metop-b.yaml.j2#L169-L182

It is just adding one line under `action` in the data thinning filter:
```
action:
      name: reject
      name: reduce obs space
```

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA This PR has a companion [PR #29](https://github.com/NOAA-EMC/jcb-gdas/pull/29) in jcb-gdas
@danholdaway had approved the PR but not merged yet.

**Comment by emilyhcliu** [comment]
> This changes in this PR are necessary but not sufficient.
> 
> Build feature/iasi inside g-w PR [#2985](https://github.com/NOAA-EMC/global-workflow/pull/2875). test_gdasapp works apart from know failures due to g-w PR [#2920](https://github.com/NOAA-EMC/global-workflow/pull/2920) not yet being in `develop`.
> 
> ```
> Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/radbcor_iasi/sorc/gdas.cd/build
>       Start 1531: test_gdasapp_util_coding_norms
>  1/46 Test #1531: test_gdasapp_util_coding_norms .....................................   Passed    2.50 sec
>       Start 1532: test_gdasapp_util_ioda_example
>  2/46 Test #1532: test_gdasapp_util_ioda_example .....................................   Passed    2.93 sec
>       Start 1533: test_gdasapp_util_prepdata
>  3/46 Test #1533: test_gdasapp_util_prepdata .........................................   Passed    1.24 sec
> 
> ...
> 
>       Start 1912: test_gdasapp_atm_jjob_ens_final
> 45/46 Test #1912: test_gdasapp_atm_jjob_ens_final ....................................   Passed   42.36 sec
>       Start 1913: test_gdasapp_aero_gen_3dvar_yaml
> 46/46 Test #1913: test_gdasapp_aero_gen_3dvar_yaml ...................................   Passed    0.80 sec
> 
> 87% tests passed, 6 tests failed out of 46
> 
> Label Time Summary:
> gdas-utils    =  10.06 sec*proc (13 tests)
> manual        = 1433.11 sec*proc (9 tests)
> script        =  10.06 sec*proc (13 tests)
> 
> Total Test time (real) = 2666.47 sec
> 
> The following tests FAILED:
>         1893 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasprepoceanobs_202103241800 (Failed)
>         1894 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarinebmat_202103241800 (Failed)
>         1895 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlinit_202103241800 (Subprocess killed)
>         1896 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlvar_202103241800 (Subprocess killed)
>         1897 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlchkpt_202103241800 (Subprocess killed)
>         1898 - test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlfinal_202103241800 (Subprocess killed)
> ```
> 
> Tests with g-w CI adding metop-b iasi fail. Changes are needed in
> 
> * `parm/jcb-gdas/observation_chronicle`
> * `parm/jcb-gdas/observations/atmosphere-lgetkf`
> * `parm/jcb-gdas/observations/atmosphere`
> 
> These directories contain files named `mtiasi*`
> 
> ```
> observation_chronicle/atmosphere/mtiasi_metop-a.yaml
> observation_chronicle/atmosphere/mtiasi_metop-b.yaml
> observations/atmosphere-lgetkf/mtiasi_metop-a.yaml.j2
> observations/atmosphere-lgetkf/mtiasi_metop-b.yaml.j2
> observations/atmosphere/mtiasi_metop-a.yaml.j2
> observations/atmosphere/mtiasi_metop-b.yaml.j2
> ```
> 
> These files need to be git moved to
> 
> ```
> observation_chronicle/atmosphere/iasi_metop-a.yaml
> observation_chronicle/atmosphere/iasi_metop-b.yaml
> observations/atmosphere-lgetkf/iasi_metop-a.yaml.j2
> observations/atmosphere-lgetkf/iasi_metop-b.yaml.j2
> observations/atmosphere/iasi_metop-a.yaml.j2
> observations/atmosphere/iasi_metop-b.yaml.j2
> ```

The [PR #29](https://github.com/NOAA-EMC/jcb-gdas/pull/29) in jcb-gdas should resolve issues you mentioned. 
I issued this PR and the above-mentioned jcb-gdas  PR at the same time.
The jcb PR has been approved but has not been merged yet.

**Review by ADCollard — APPROVED** [review]

**Comment by emilyhcliu** [comment]
@ADCollard  Thanks for reviewing.

**Pull request merged**
