### PR TITLE
Updates `detect_machines.sh` to be consistent with UFSWM

### PR DESCRIPTION
**Pull request by HenryRWinterbottom**
This PR addresses issue #889. The following is accomplished:

- The GDASApp `ush/detect_machine.sh` is replaced by the UFS weather-model `tests/detect_machine.sh` prepared by @BrianCurtis-NOAA;
- The version of `rocoto` has been updated from `1.3.3` to `1.3.6` to allow the build system to complete successfully.

This PR does not modify any applications with the GDASApp, only the determination of the respective host. No CI/CD or regression testing should be required.

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
Changes look good to me.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres and @CoryMartin-NOAA :  This PR contains a critical change to the GDAS hera modulefile.  `rocototo/1.3.3` is no longer accessible.  
```
Hera(hfe05):~$ ls -l /apps/rocoto/
total 64
drwxr-xr-x 10 role.apps apps 2048 Jan 29 14:04 1.3.6
lrwxrwxrwx  1 role.apps apps    5 Jan 29 14:10 default -> 1.3.6
```
We need to move to `rocoto/1.3.6`. on Hera  This PR makes this change.  Thank you @HenryWinterbottom-NOAA !

**Review by guillaumevernieres — APPROVED** [review]
Thanks @HenryWinterbottom-NOAA .

**Comment by RussTreadon-NOAA** [comment]
Clone `HenryWinterbottom-NOAA:feature/gdasapp_issue_889` on Hera, Hercules, and Orion.   Execute `./build.sh -v` on each machine.  `GDAS/$machine.intel` was loaded on each `$machine`.  Build successfully ran to completion on each `$machine`.

**Pull request merged**
