### PR TITLE
Change to use CRTM 2.4

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
As the title says!

### CODE REVIEW

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA Does this mean we have already decided to switch to CRTM 2.4 even though this change would break the current ctests?

**Comment by RussTreadon-NOAA** [comment]
**Hera test**

Install g-w `develop` at [84842f4](https://github.com/NOAA-EMC/global-workflow/commit/84842f455da5dfc976eda21336ae383616ac96d0) and GDASApp `feature/jack-bauer`.   Run ctests.  Four tests fail

```
The following tests FAILED:
        1530 - test_gdasapp_atm_jjob_var_run (Failed)
        1531 - test_gdasapp_atm_jjob_var_final (Failed)
        1533 - test_gdasapp_atm_jjob_ens_run (Failed)
        1534 - test_gdasapp_atm_jjob_ens_final (Failed)
```

The `var_run` and `ens_run` tests failed with CRTM coefficient errors.   
```
1:  AerosolCoeff_ValidRelease(INFORMATION) : A AerosolCoeff data update is needed. AerosolCoeff release is 3. Valid release is 4.
3:  AerosolCoeff_ValidRelease(INFORMATION) : A AerosolCoeff data update is needed. AerosolCoeff release is 3. Valid release is 4.
5:  AerosolCoeff_ValidRelease(INFORMATION) : A AerosolCoeff data update is needed. AerosolCoeff release is 3. Valid release is 4.
0:  AerosolCoeff_ValidRelease(INFORMATION) : A AerosolCoeff data update is needed. AerosolCoeff release is 3. Valid release is 4.
2:  AerosolCoeff_ValidRelease(INFORMATION) : A AerosolCoeff data update is needed. AerosolCoeff release is 3. Valid release is 4.
4:  AerosolCoeff_ValidRelease(INFORMATION) : A AerosolCoeff data update is needed. AerosolCoeff release is 3. Valid release is 4.
5:  AerosolCoeff_ReadFile(Binary)(FAILURE) : AerosolCoeff Release check failed.
5:  CRTM_AerosolCoeff_Load(FAILURE) : Error reading AerosolCoeff file /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/develop/sorc/gdas.cd/build/test/atm/global-workflow/testrun/RUNDIRS/gdas_test/gdasatmanl_18/crtm/AerosolCoeff.bin
3:  AerosolCoeff_ReadFile(Binary)(FAILURE) : AerosolCoeff Release check failed.
3:  CRTM_AerosolCoeff_Load(FAILURE) : Error reading AerosolCoeff file /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/develop/sorc/gdas.cd/build/test/atm/global-workflow/testrun/RUNDIRS/gdas_test/gdasatmanl_18/crtm/AerosolCoeff.bin
3:  CRTM_Init(FAILURE) : Error loading AerosolCoeff data from AerosolCoeff.bin
3:  ufo_radiancecrtm_simobs(FAILURE) :  Error initializing CRTM on rank            3
5:  CRTM_Init(FAILURE) : Error loading AerosolCoeff data from AerosolCoeff.bin
5:  ufo_radiancecrtm_simobs(FAILURE) :  Error initializing CRTM on rank            5
1:  AerosolCoeff_ReadFile(Binary)(FAILURE) : AerosolCoeff Release check failed.
1:  CRTM_AerosolCoeff_Load(FAILURE) : Error reading AerosolCoeff file /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/develop/sorc/gdas.cd/build/test/atm/global-workflow/testrun/RUNDIRS/gdas_test/gdasatmanl_18/crtm/AerosolCoeff.bin
1:  CRTM_Init(FAILURE) : Error loading AerosolCoeff data from AerosolCoeff.bin
3: Abort from ufo_radiancecrtm_simobs
5: Abort from ufo_radiancecrtm_simobs
1:  ufo_radiancecrtm_simobs(FAILURE) :  Error initializing CRTM on rank            1
1: Abort from ufo_radiancecrtm_simobs
```

The `var_final` and `ens_final` tests failed because expected output from the `run` jobs was not available.

The `var_init` and `ens_init` jobs copy CRTM coefficients from g-w directory `$HOMEgfs/fix/gdas/crtm/2.3.0`.   The g-w crtm directory points at `/scratch1/NCEPDEV/global/glopara/fix/gdas/crtm/20220805`.   These are v2.3.0 coefficients.  Looks like we need to copy and use v2.4.0 coefficients.

**Comment by RussTreadon-NOAA** [comment]
Try the following as a test

1. create g-w fix/gdas/crtm/2.4.0 as a link to `/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/crtm/2.4.0/fix` 
2. change `crtm_VERSION=2.3.0` to `crtm_VERSION=2.4.0` in GDASApp `test/atm/global-workflow/config.atmanl`

This failed because I forgot that `gsi.x` reads big endian CRTM coefficient files.  `fv3jedi_var.x` reads little endian CRTMfiles. 

Execute `ufo_get_crtm_test_data` to pull CRTM coefficients from server.   This pulls down crtm tarball with coefficients in distributed format (ie, directories AerosolCoeff,  CloudCoeff,  EmisCoeff,  SpcCoeff,  TauCoeff).   `fv3jedi_var.x` and `gsi.x` expect coefficients to be in single directory containing all coefficient types.

Do we have a script to remap the distributed directory structure to the flat directory?

**Comment by CoryMartin-NOAA** [comment]
@emilyhcliu The develop branch of UFO requires 2.4 to build. We have a few options here, none are ideal in my opinion
1. go to using CRTM 2.4. This is the easiest, but it would require us updating the "Darth Vader" tests ASAP as they would likely fail.
2. keep a branch of UFO that we keep up to date with develop, but manually edit it to support CRTM 2.3. This is somewhat labor intensive.
3. Open a PR to UFO to make the minimum version 2.3. It was 3.0, and Dan changed it to 2.4. We can go to 2.3 (that is my fault for thinking 2.4 would be fine going forward)

Thoughts? As @RussTreadon-NOAA showed we need 2.4 coefficients for 2.4. I forget how the JEDI fix directory was created... GSI had a script to stage the CRTM coefficients, right?

**Comment by RussTreadon-NOAA** [comment]
With the splitting of our single GSI repo into several functional GSI repos it looks like the script to stage crtm fix files got lost ... at least I can't find it yet.   Perhaps the fix file script resides with the NCEPLIBS crtm install scripts.

**Comment by RussTreadon-NOAA** [comment]
`link_crtm_coeffs.sh` found in an old GSI hash.   The script didn't work out of the box.  I needed to comment out special links for airs, cris, and iasi at the end of the script.  Used the revised script to populate flat directory `$HOMEgfs/fix/gdas/crtm/2.4.0` from distributed directory `$HOMEgfs/fix/gdas/crtm/2.4.1_skylab_4.0`.    

Set `crtm_VERSION=2.4.0` in GDASApp `test/atm/global-workflow/config.atmanl` and g-w `parm/config/gfs/config.atmensanl`.   (Yes, changing `crtm_VERSION` in two different locations is problematic.)

```
Reran `test_gdasapp_atm_jjob`.   All 6 jobs completed with _Passed_.
(gdasapp) Hera(hfe11):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/develop/sorc/gdas.cd/build$ ctest -R test_gdasapp_atm_jjob   Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/develop/sorc/gdas.cd/build
    Start 1529: test_gdasapp_atm_jjob_var_init
1/6 Test #1529: test_gdasapp_atm_jjob_var_init ....   Passed   43.16 sec
    Start 1530: test_gdasapp_atm_jjob_var_run
2/6 Test #1530: test_gdasapp_atm_jjob_var_run .....   Passed  140.42 sec
    Start 1531: test_gdasapp_atm_jjob_var_final
3/6 Test #1531: test_gdasapp_atm_jjob_var_final ...   Passed   42.17 sec
    Start 1532: test_gdasapp_atm_jjob_ens_init
4/6 Test #1532: test_gdasapp_atm_jjob_ens_init ....   Passed   44.32 sec
    Start 1533: test_gdasapp_atm_jjob_ens_run
5/6 Test #1533: test_gdasapp_atm_jjob_ens_run .....   Passed  300.45 sec
    Start 1534: test_gdasapp_atm_jjob_ens_final
6/6 Test #1534: test_gdasapp_atm_jjob_ens_final ...   Passed   42.10 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 613.03 sec
```

I advise against using my `$HOMEgfs/fix/gdas/crtm/2.4.0`.  Someone more knowledgeable about the CRTM should set up a little endian crtm/2.4.0 flat directory.

**Comment by CoryMartin-NOAA** [comment]
I'm perhaps wondering if we should instead stick to 2.3 a bit longer with the UFO feature/gdasapp branch so that things can continue to run as intended?

**Pull request closed without merging**
