### PR TITLE
add ctest to create yaml for lgetkf observer ctest

### LINKED ISSUE #1271: Update lgetkf ctests for g-w jedi class
g-w PR [#2805](https://github.com/NOAA-EMC/global-workflow/pull/2805) includes changes which require updates to how the GDASApp lgetkf ctests are run.   

Specifically, the lgetkf init job needs to be run twice.  One run creates the yaml for `test_gdasapp_atm_jjob_ens_letkf` - the combined observer & solver lgetkf test.  The init job needs to be run again to create the yaml used by test `test_gdasapp_atm_jjob_ens_obs` - the observer piece of the split lgetkf tests.

This issue is opened to document these changes.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
This PR adds ctest `test_gdasapp_atm_jjob_ens_init_split` to the atm_jjob suite of ctests.  Test `test_gdasapp_atm_jjob_ens_init_split` creates the yaml file used by `test_gdasapp_atm_jjob_ens_obs` - the observer lgetkf ctest.

Resolves #1271

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Notes:  
1. The changes in this PR must be tested with g-w PR [#2805](https://github.com/NOAA-EMC/global-workflow/pull/2805).  The JEDI class changes in [#2805](https://github.com/NOAA-EMC/global-workflow/pull/2805) necessitate the changes in this GDASApp PR.
2. At a later date the GDASApp team may decide to remove the combined lgetkf ctest, `test_gdasapp_atm_jjob_ens_letkf`.  If this is done new issues and PRs will be opened in multiple repositories to remove the combined lgetkf option.

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA, @CoryMartin-NOAA , and @TravisElless-NOAA :  here's the PR to update GDASApp ctests so that we can run both the combined and split lgetkf tests with g-w PR [#2805](https://github.com/NOAA-EMC/global-workflow/pull/2805).  Without this PR, `test_gdasapp_atm_jjob_ens_obs` and `test_gdasapp_atm_jjob_ens_sol` will fail after g-w PR [#2805](https://github.com/NOAA-EMC/global-workflow/pull/2805) enters g-w `develop`.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
Thank you @CoryMartin-NOAA for the review & approval.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA merge when you're satisfied. We do not need this hash in the g-w PR, right? We just need to accept that tests will fail in GDASApp between the g-w merge and this merge. Is there any harm in this merging early?

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , you are correct.  We can merge this PR into GDASApp `develop` right now.  Doing so will break a few ctests. 
 These failures will go away after JEDI class is in g-w.  I'll go ahead and merge this PR into `develop`.

**Pull request merged**
