### PR TITLE
New B-matrix

### LINKED ISSUE #290: [bug] soca Inverse balance segfaults ...
Segfault while trying to turn back on the balance change of variable ...
```malloc.c:4036: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.```
something not allocated somewhere ...

### LINKED ISSUE #309: Update to the static B
## Description
This is a "slight" change of direction on how we are going to construct our static B. The plan is to not use BUMP for small scales and instead rely on simple filters and use bump for larger scales only. This work is coordinated with @liuxiao37k and @ShastriPaturi 's findings.

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Work done
- Update to the small scale part of the static B (#309)
- Added the possibility of reading the diag of B
- Balance Bugfix 
- Addition of conditionals in the B-matrix `j-job`
- No more piping of the jedi exe to their own output files

### Issues addressed
- fixes #309 
- fixes #290

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
Hera and Orion GW-RT tests pass.   These changes are exercised in these tests.    Since the tests pass and bug #290 is fixed, APPROVE.  

I'll let subject matter experts chime in on the acceptability of the analysis results using the new B-matrix.

**Review by AndrewEichmann-NOAA — COMMENTED** [review]
Looks plausible

**Comment by guillaumevernieres** [comment]
> Looks plausible

I'll take that as a check!

**Comment by liuxiao37k** [comment]
@guillaumevernieres I approve because finally there is a yaml that could give me a red line that is below the black one! This was with 3x of the ensemble-based stddev.
image
image
I need to take a closer look at the results tomorrow but the yaml itself looks fine.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I approve because finally there is a yaml that could give me a red line that is below the black one! This was with 3x of the ensemble-based stddev. image image I need to take a closer look at the results tomorrow but the yaml itself looks fine.

unheard off, doing things right improved the results!!!!

**Pull request merged**
