### PR TITLE
Use skylab v3 modules

### LINKED ISSUE #390: Update modulefiles to use latest JEDI Spack-stack
@CoryMartin-NOAA When building the GDASApp on hera, it crashed with the following errors: 

```
[ 27%] Building Fortran object fms/CMakeFiles/fms.dir/coupler/atmos_ocean_fluxes.F90.o
cd /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fms && /apps/oneapi/mpi/2021.5.1/bin/mpiifort -DGFS_PHYS -DINTERNAL_FILE_NML -DSPMD -Dfms_EXPORTS -Duse_LARGEFILE -Duse_libMPI -Duse_netCDF -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fms/mpp/include -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fms/fms2_io/include -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fms/fms -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fms/include -I/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/netcdf-fortran-4.5.4-6plux7v/include -I/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/netcdf-c-4.8.1-pnwaunu/include -r8 -O2 -g -DNDEBUG  -module module -fPIC -qopenmp -c /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fms/coupler/atmos_ocean_fluxes.F90 -o CMakeFiles/fms.dir/coupler/atmos_ocean_fluxes.F90.o
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E cmake_copy_f90_mod fms/module/atmos_ocean_fluxes_mod.mod fms/CMakeFiles/fms.dir/atmos_ocean_fluxes_mod.mod.stamp Intel
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E touch fms/CMakeFiles/fms.dir/coupler/atmos_ocean_fluxes.F90.o.provides.build
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E cmake_copy_f90_mod fms/module/interpolator_mod.mod fms/CMakeFiles/fms.dir/interpolator_mod.mod.stamp Intel
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E touch fms/CMakeFiles/fms.dir/interpolator/interpolator.F90.o.provides.build
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E cmake_copy_f90_mod fms/module/xgrid_mod.mod fms/CMakeFiles/fms.dir/xgrid_mod.mod.stamp Intel
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E touch fms/CMakeFiles/fms.dir/exchange/xgrid.F90.o.provides.build
[ 27%] Linking Fortran shared library ../lib/libfms.so
cd /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fms && /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E remove /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/lib/libfms.so
cd /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fms && /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E cmake_link_script CMakeFiles/fms.dir/link.txt --verbose=NO
make[2]: Leaving directory `/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build'
[ 27%] Built target fms
make[1]: Leaving directory `/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build'
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
Closes #390 

With the latest merge into develop of OOPS, the JEDI executables no longer build. At the moment, this is due to a feature that requires a newer version of Atlas than what is currently loaded by GDASApp.

This PR updates from SKYLABv2 modulefiles to SKYLABv3

### CODE REVIEW

**Review by guillaumevernieres — APPROVED** [review]
Thanks for doing this @CoryMartin-NOAA .

**Review by jiaruidong2017 — APPROVED** [review]
Thanks for your great efforts.

**Review by RussTreadon-NOAA — COMMENTED** [review]
Assuming the updated modules yield a successful build and ctest pass, approve.   As I wait for the results of automated Hera and Orion RT tests, I am building feature/skylabv3 on Orion and Hera.   I can approve this PR once the changes are confirmed to work,

**Comment by CoryMartin-NOAA** [comment]
Both platforms tests pass, I will merge.

**Pull request merged**
