### PR TITLE
[Bug] BUMP yaml reorg

### LINKED ISSUE #239: [Bug] Changes to BUMP's yaml keys
Just a head's up @RussTreadon-NOAA and @CoryMartin-NOAA ...
See [SABER PR #389](https://github.com/JCSDA-internal/saber/pull/389)

_Merge will happen Jan 5 2023_

### PR DESCRIPTION
**Pull request by guillaumevernieres**
- fixes #239

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@RussTreadon-NOAA , it was a relatively painless change on the soca side. I used Benjamin's script to update the yamls and it tested fine for soca, I did not test the atm but I'm tempted to just run the `CI` ...

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , given your success with soca let's try `CI` and see what happens.

**Comment by RussTreadon-NOAA** [comment]
Orion & Hera g-w tests pass.   This is a good way to end the day!

**Comment by guillaumevernieres** [comment]
> Orion & Hera g-w tests pass. This is a good way to end the day!

Nice!

**Review by RussTreadon-NOAA — APPROVED** [review]
Changes have been tested by CI.  Tests pass on Orion and Hera.   Approve.

**Review by CoryMartin-NOAA — APPROVED** [review]
Merci, G! :-)

**Pull request merged**
