### PR TITLE
Allow for gdas or gfs obs

### LINKED ISSUE #921: Obs YAMLs for SOCA are hard-coded for "gdas"
When running WCDA with `gfs_cyc/=0`, the `gfsprepoceanobs` task creates obs with the prefix `gdas.` instead of `gfs.`.  A look at one of the YAML files confirms that the output files are hardcoded for `gdas`.  For example,  sst_avhrr_mb_l3u2ioda.yaml:
```
name: sst_avhrr_mb_l3u
provider: GHRSST
dmpdir subdir: ocean/sst
output file: gdas.t18z.sst_avhrr_mb_l3u.2021032418.nc4
```

The `gfsprepoceanobs` job succeeds but the `gfsocnanalrun` fails. 

@guillaumevernieres @AndrewEichmann-NOAA @ShastriPaturi @JessicaMeixner-NOAA

### PR DESCRIPTION
**Pull request by guillaumevernieres**
- fixes #921

### CODE REVIEW

**Review by CatherineThomas-NOAA — APPROVED** [review]
I merged the changes into my clone and reran the `gfsprepoceanobs` step.  I now see the gfs files in my `obs` directory:
```
-rw-r--r-- 1 Catherine.Thomas stmp     5456735 Feb 16 12:09 gfs.t18z.sst_abi_g16_l3c.2021032418.nc4
```
Thanks for the quick fix.  Approve.

**Review by ShastriPaturi — APPROVED** [review]

**Comment by guillaumevernieres** [comment]
> I merged the changes into my clone and reran the `gfsprepoceanobs` step. I now see the gfs files in my `obs` directory:
> 
> ```
> -rw-r--r-- 1 Catherine.Thomas stmp     5456735 Feb 16 12:09 gfs.t18z.sst_abi_g16_l3c.2021032418.nc4
> ```
> 
> Thanks for the quick fix. Approve.

Can you let me know how the gfs cycle goes @CatherineThomas-NOAA ? That chunk of code is not covered in our ctest, we only test the gdas cycle for now.

**Comment by CatherineThomas-NOAA** [comment]
> Can you let me know how the gfs cycle goes @CatherineThomas-NOAA ? 

@guillaumevernieres 
Of course.   So far the `gfsocnanalrun` job that failed because of this issue has now passed.  I'll update you once it finishes a full cycle (or it fails because of something else).

**Comment by guillaumevernieres** [comment]
> > Can you let me know how the gfs cycle goes @CatherineThomas-NOAA ?
> 
> @guillaumevernieres Of course. So far the `gfsocnanalrun` job that failed because of this issue has now passed. I'll update you once it finishes a full cycle (or it fails because of something else).

I'll call it good for now then! Merging the fix.

**Pull request merged**
