### PR TITLE
Update wcoss2.intel.lua

### LINKED ISSUE #1139: Update wcoss2.intel.lua
`wcoss2.intel.lua` should be updated for at least two reasons
1. NCO has installed `bufr/12.0.1` in a production location on WCOSS2.  We should load the production module, not the para module.
2. GDASApp build requires `git-lfs`.  To load `git-lfs` on WCOSS2 we must first load `gcc`.  Loading `gcc` unloads the intel environment.  We do not want a gcc build of GDASApp on WCOSS2.  We must use an intel build.  To get around this, add to `wcoss2.intel.lua` a `prepend_path` line with the path to `git-lfs`.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
Make two changes to `wcoss2.intel.lua`
1. replace para `bufr/12.0.1` with prod `bufr/12.0.1`
2. prepend `git-lfs` path to `$PATH`

Resolves #1139

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
This PR will remain in draft mode until NCO installs the production `bufr/12.0.1` on Cactus.  As of 6/3/2024 `bufr/12.0.1` has only been installed in production space on Dogwood.

**Comment by RussTreadon-NOAA** [comment]
`bufr/12.0.1` is on Cactus as of 6/4/2024
```
russ.treadon@clogin02:~> module spider bufr

----------------------------------------------------------------------------------------------------------------------
  bufr:
----------------------------------------------------------------------------------------------------------------------
    Description:
      bufr library

     Versions:
        bufr/11.4.0
        bufr/11.5.0
        bufr/11.6.0
        bufr/11.7.0
        bufr/12.0.0
        bufr/12.0.1
     Other possible modules matches:
        bufr_dump  bufr_tranjb  bufr_util  compiler/intel/19.1.3.304/bufr_dump  core/bufr_dump
```

Therefore, mark this PR as _Ready for review_.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , @CatherineThomas-NOAA , @guillaumevernieres 

We need at least `bufr/12.0.1` to fully build GDASApp.  NCO has installed `bufr/12.0.1` on both Cactus and Dogwood in production directories.  This PR updates `modulefiles/GDAS/wcoss2.intel.lua` to use the production `bufr/12.0.1`.  

Once this PR is merged into `develop`, I will update the `gdas.cd` hash used by g-w PR [#2620](https://github.com/NOAA-EMC/global-workflow/pull/2620)

**Review by CoryMartin-NOAA — APPROVED** [review]
Looks great, thanks @RussTreadon-NOAA !

**Comment by RussTreadon-NOAA** [comment]
Thank you @CoryMartin-NOAA for your approval.  I'll merge the updated `wcoss2.intel.lua` into `develop`

**Review by CatherineThomas-NOAA — COMMENTED** [review]
I know it's already merged, but just confirming that I can see the new module on both Cactus and Dogwood, and I was able to compile GDASApp with Russ's branch on Dogwood.  Approve.

**Comment by RussTreadon-NOAA** [comment]
Thank you @CatherineThomas-NOAA for checking Dogwood and Cactus.  I am currently running g-w CI for C96C48_ufs_hybatmDA on Cactus using the updated `wcoss2.intel.lua`.

**Pull request merged**
