### PR TITLE
Feature/add satwind

### PR DESCRIPTION
**Pull request by joshk24**
Not sure why aircraft and sfcship files are also attached to this pull request...Cory we can probably fix this the same way before when you're out of your meeting! I'll alos try to make this a "draft" for now

### CODE REVIEW

**Comment by joshk24** [comment]
It allows me to delete files on this pull request, but i'm afraid if i do that i'll lose the whole file

**Comment by joshk24** [comment]
eastward_satwind_jvg
eastward_satwind_omb
northward_satwind_jvg
northward_satwind_omb

**Comment by CoryMartin-NOAA** [comment]
@joshk24 you have `aircraft` and `sfcship` in this branch. Just like what we did this morning, we need to merge develop in to get rid of aircraft and temporarily remove the sfcship file.

**Comment by joshk24** [comment]
ompsnp_jvg
ompsnp_omb
ompstc_jvg
ompstc_omb

**Comment by joshk24** [comment]
wait wrong one oops...i'll put those pictures in the other one

**Comment by CoryMartin-NOAA** [comment]
Test fails because it is looking for ozone YAML files which don't yet exist, once #84 is merged in, then this one should pass after merging in develop.

**Review by CatherineThomas-NOAA — APPROVED** [review]
Looks good after the recent ozone merge to develop.  Good catch on adding aircraft and atms to the gdas_prototype list.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
