### PR TITLE
Stage atmospheric backgrounds and UFS cubed-sphere history files

### PR DESCRIPTION
**Pull request by DavidNew-NOAA**
This PR changes the GDASApp so that backgrounds for the atmospheric analyses are staged as UFS cubed-sphere history files rather than FMS restarts. jjob tests and test data are also updated to accommodate these changes. The motivation being that FMS restarts include many data we don't need for the analyses and thus take up too much disk space/bandwidth.

This is a companion PR to Global Workflow [#2792](https://github.com/NOAA-EMC/global-workflow/pull/2792) and JCB-GDAS [#19](https://github.com/NOAA-EMC/jcb-gdas/pull/19).

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
Changes look good.  

Installed `feature/cubed_sphere_bkg` inside g-w `feature/cubed_sphere_bkg` on Hera and ran `test_gdaspp`.  The following tests failed
```
98% tests passed, 1 tests failed out of 43

Label Time Summary:
gdas-utils    =  17.40 sec*proc (11 tests)
script        =  17.40 sec*proc (11 tests)

Total Test time (real) = 2101.56 sec

The following tests FAILED:
        1881 - test_gdasapp_fv3jedi_fv3inc (Failed)
```
Rerun failed test with `-VV`. Failure due to 
```
1881:   Y-AXIS =   12
1881: fv3jedi_io_cube_sphere_history_mod.read_fields.get_field_ncid_varid: Field phis was not found in any files. Should only be present in one file that is read.
1881: fv3jedi_io_cube_sphere_history_mod.read_fields.get_field_ncid_varid: Field phis was not found in any files. Should only be present in one file that is read.
1881: fv3jedi_io_cube_sphere_history_mod.read_fields.get_field_ncid_varid: Field phis was not found in any files. Should only be present in one file that is read.
1881: Abort(1) on node 2 (rank 2 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
1881: Abort(1) on node 4 (rank 4 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 4
1881: fv3jedi_io_cube_sphere_history_mod.read_fields.get_field_ncid_varid: Field phis was not found in any files. Should only be present in one file that is read.
1881: fv3jedi_io_cube_sphere_history_mod.read_fields.get_field_ncid_varid: Field phis was not found in any files. Should only be present in one file that is read.
1881: fv3jedi_io_cube_sphere_history_mod.read_fields.get_field_ncid_varid: Field phis was not found in any files. Should only be present in one file that is read.
1881: Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
1881: Abort(1) on node 3 (rank 3 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3
1881: Abort(1) on node 5 (rank 5 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 5
1881: slurmstepd: error: *** STEP 63904355.0 ON h14c02 CANCELLED AT 2024-07-25T19:28:06 ***
```

**Comment by RussTreadon-NOAA** [comment]
Replace `phis` with `surface_geopotential_height` in `test/fv3jedi/testinput/gdasapp_fv3jedi_fv3inc.yaml`.  
```
   variable change name: Model2GeoVaLs
-  input variables: &bkgvars [ua,va,t,ps,sphum,ice_wat,liq_wat,o3mr,phis]
+  input variables: &bkgvars [ua,va,t,ps,sphum,ice_wat,liq_wat,o3mr,surface_geopotential_height]
   output variables: &fv3incrvars [ua,va,t,sphum,ice_wat,liq_wat,o3mr,delp,hydrostatic_delz]
```
Rerun `test_gdasapp_fv3jedi_fv3inc`.  Test _Passed_
```
Hera(hfe01):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/cube_sphere_bkg/sorc/gdas.cd/build$ ctest -R test_gdasapp_fv3jedi_fv3inc
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/cube_sphere_bkg/sorc/gdas.cd/build
    Start 1881: test_gdasapp_fv3jedi_fv3inc
1/1 Test #1881: test_gdasapp_fv3jedi_fv3inc ......   Passed    6.22 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   6.72 sec
```

**Review by RussTreadon-NOAA — DISMISSED** [review]
Change to `test/fv3jedi/testinput/gdasapp_fv3jedi_fv3inc.yaml` is correct.

Approve.

**Comment by RussTreadon-NOAA** [comment]
Install `feature/cubed_sphere_bkg` at 0cf2015 inside g-w `DavidNew-NOAA:feature/cubed_sphere_bkg` at [`ca54020`](https://github.com/DavidNew-NOAA/global-workflow/commit/ca540209d5014a03d3204b54cc0f8f3f07b74037).  Run `test_gdasapp`.  All tests pass
```
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/cube_sphere_bkg/sorc/gdas.cd/build
      Start 1531: test_gdasapp_util_coding_norms
 1/43 Test #1531: test_gdasapp_util_coding_norms ........................   Passed    2.90 sec
 
...

      Start 1909: test_gdasapp_aero_gen_3dvar_yaml
43/43 Test #1909: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    0.87 sec

100% tests passed, 0 tests failed out of 43

Label Time Summary:
gdas-utils    =   8.47 sec*proc (11 tests)
script        =   8.47 sec*proc (11 tests)

Total Test time (real) = 1315.30 sec
```
```

**Review by CoryMartin-NOAA — DISMISSED** [review]

**Comment by CoryMartin-NOAA** [comment]
This needs to be merged in coordination with the workflow, correct?

**Comment by DavidNew-NOAA** [comment]
@CoryMartin-NOAA correct

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
