### PR TITLE
Use newer spack-stack modules

### LINKED ISSUE #500: Move to newer spack/skylab modules
Develop of oops now requires a newer version of eckit than what we are loading in the modulefiles. We need to move to spack-stack skylab v4 from v3 now because develop will no longer build with v3

In the short term, `feature/stable-nightly` should build but `develop` might not.

Tagging @guillaumevernieres @RussTreadon-NOAA @DavidNew-NOAA @ADCollard @emilyhcliu for awareness. Thanks to @andytangborn for finding the issue.

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
Closes #500 

Solves problems associated with JCSDA now requiring newer version of eckit for develop branch of OOPS

### CODE REVIEW

**Review by BrettHoover-NOAA — APPROVED** [review]
Thank you Cory!

**Review by RussTreadon-NOAA — APPROVED** [review]
Haven't tried building & running `bugfix/new_modules` on Orion or Hera.  Approve assuming that you (@CoryMartin-NOAA ) have run this test and confirm acceptable behavior.

**Comment by CoryMartin-NOAA** [comment]
I have built on both platforms, but not tested. Probably safe to assume that since it compiles it will run, but you know what they say when you assume... 

I probably won't be able to run all 1700 ctests before COB, should this get merged and fix tomorrow if it breaks things or wait to merge until it is tested (develop currently won't build)

**Comment by RussTreadon-NOAA** [comment]
**Hera test**

Clone and build `bugfix/new_modules` inside working copy of g-w develop (at current head).  Run GDASApp ctests.  All 48 `test_gdasapp` _Passed_.

**Review by guillaumevernieres — APPROVED** [review]
Not tested but I crossed my fingers, so all good. Thanks @CoryMartin-NOAA .

**Comment by RussTreadon-NOAA** [comment]
**Orion test**

Clone and install `bugfix/new_modules` in working copy of g-w `develop` (at current head).  Run 48 `test_gdasapp` ctests.  All 48 tests _Passed_.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA thanks for doing the testing, much appreciated! will merge in now

**Pull request merged**
