### PR TITLE
insitu Obsyamls for monthly tank data

### LINKED ISSUE #701: obsspace yamls for monthly insitu
Add obsspace yamls for monthly insitu with Global and Regional Range filters
Currently: 
- [x] subpfl (separated into ARGO and Gliders)
- [x] TESAC
- [x] BATHY

### PR DESCRIPTION
**Pull request by ShastriPaturi**
This PR adds Obsyamls for individual ObsSpaces (temp & salinity)  with "passivate" filter.
The description of the data can be found #701 

This PR closes #701 

The ObsYamls for composite obs will be added in a subsequent PR.

### CODE REVIEW

**Review by apchoiCMD — DISMISSED** [review]
thumbs up @ShastriPaturi

**Review by guillaumevernieres — CHANGES_REQUESTED** [review]
As we discussed yesterday, add the new obs files to the `obs_list.yaml` and comment them out.

**Review by AndrewEichmann-NOAA — DISMISSED** [review]
Looks tenable

**Comment by ShastriPaturi** [comment]
> Looks tenable

@guillaumevernieres will merge when it is plausible :)

**Review by guillaumevernieres — APPROVED** [review]
Thanks @ShastriPaturi

**Pull request merged**
