### PR TITLE
Optional binning of ghrsst

### PR DESCRIPTION
**Pull request by guillaumevernieres**
We can now remove the binning section in the `yaml`. This will skip the binning and just output the original file converted to ioda, which should help testing the code for correctness.

I'm also passing the ```min number of obs``` `yaml` key to the binning function, which I had forgotten to do!

### CODE REVIEW

**Review by apchoiCMD — COMMENTED** [review]
Shame on me, I didn't think of "if" statement before. Looks tenable!!!

**Review by apchoiCMD — APPROVED** [review]

**Comment by guillaumevernieres** [comment]
No rush on approving/merging @apchoiCMD . Please use this branch for the testing of the binning/concatenation of `GHRSST`.

**Review by AndrewEichmann-NOAA — APPROVED** [review]
looks ok

**Comment by guillaumevernieres** [comment]
@ShastriPaturi , @apchoiCMD , @AndrewEichmann-NOAA : As I'm comparing the output of this converter to what the python converter is generating, it turns out that not much was done correctly ...  Oops! I'll push the bug fixes to this pr.

**Comment by guillaumevernieres** [comment]
Closing for now, I'll reopen as a bufix later this week.

**Pull request closed without merging**
