### PR TITLE
Add safeguards against timing problem in run_jedi_exe ctests

### LINKED ISSUE #344: Fix run_jedi ctests
PR #324 flagged a false negative from `test_gdasapp_run_jedi_exe_3dvar`.   [Click here](https://github.com/NOAA-EMC/GDASApp/pull/324#issuecomment-1423477875) for details.   As demonstrated in PR #324 it is possible for the test to query runtime output file `stdout.txt` before all information written to stdout is actually in physical disk file `stdout.txt`.

This issue is opened to document updates to ctest `run_jedi_exe` driver scripts to address the noted problem.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
`run_jedi_exe` ctests can generate a [false negative](https://github.com/NOAA-EMC/GDASApp/pull/324#issuecomment-1423477875) as shown in PR #324.    Runtime file `stdout.txt` may be queried before information written this file is fully flushed to disk.   `sleep` and `sync` are added to the `run_jedi_exe` driver scripts to address this problem.

Fixes #344

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Install `feature/runjedi_fix` on Hera and Orion with `WORKFLOW_BUILD=ON`.  Execute entire suite of `test_gdasapp` tests.  All tests pass.

**Hera**
```
(gdasapp) Hera(hfe11):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/work/sorc/gdas.cd/build$ ctest -R test_gdasapp
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/work/sorc/gdas.cd/build
      Start 1318: test_gdasapp_check_python_norms
 1/42 Test #1318: test_gdasapp_check_python_norms ......................   Passed    0.44 sec
...
      Start 1349: test_gdasapp_run_jedi_exe_3dhofx
32/42 Test #1349: test_gdasapp_run_jedi_exe_3dhofx .....................   Passed   16.73 sec
      Start 1350: test_gdasapp_run_jedi_exe_3dvar
33/42 Test #1350: test_gdasapp_run_jedi_exe_3dvar ......................   Passed   14.06 sec
      Start 1351: test_gdasapp_run_jedi_exe_letkf
34/42 Test #1351: test_gdasapp_run_jedi_exe_letkf ......................   Passed   11.34 sec
...
      Start 1359: test_gdasapp_aero_gen_3dvar_yaml
42/42 Test #1359: test_gdasapp_aero_gen_3dvar_yaml .....................   Passed    0.15 sec

100% tests passed, 0 tests failed out of 42

Total Test time (real) = 717.48 sec
```
**Orion**
```
(gdasapp) Orion-login-4:/work/noaa/da/rtreadon/git/global_workflow/work/sorc/gdas.cd/build$ ctest -R test_gdasapp
Test project /work/noaa/da/rtreadon/git/global_workflow/work/sorc/gdas.cd/build
      Start 1318: test_gdasapp_check_python_norms
 1/42 Test #1318: test_gdasapp_check_python_norms ......................   Passed    2.59 sec
...
       Start 1349: test_gdasapp_run_jedi_exe_3dhofx
32/42 Test #1349: test_gdasapp_run_jedi_exe_3dhofx .....................   Passed   22.28 sec
      Start 1350: test_gdasapp_run_jedi_exe_3dvar
33/42 Test #1350: test_gdasapp_run_jedi_exe_3dvar ......................   Passed   11.52 sec
      Start 1351: test_gdasapp_run_jedi_exe_letkf
34/42 Test #1351: test_gdasapp_run_jedi_exe_letkf ......................   Passed    8.92 sec
...
      Start 1359: test_gdasapp_aero_gen_3dvar_yaml
42/42 Test #1359: test_gdasapp_aero_gen_3dvar_yaml .....................   Passed    0.13 sec

100% tests passed, 0 tests failed out of 42

Total Test time (real) = 835.13 sec
```

**Review by guillaumevernieres — APPROVED** [review]
Looks good, thanks for the quick fix.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by CoryMartin-NOAA** [comment]
I went ahead and merged, if for some reason the tests come back with failures, we can revert.

**Comment by RussTreadon-NOAA** [comment]
Sounds good.   Thank you, @CoryMartin-NOAA for approving & merging.   Thanks @guillaumevernieres for the approval.

**Comment by RussTreadon-NOAA** [comment]
Automated Hera and Orion GW-RT tests pass.   Given this, I'll delete `feature/runjedi_fix`.

**Pull request merged**
