### PR TITLE
Feature/soca ana prep update

### PR DESCRIPTION
**Pull request by AndrewEichmann-NOAA**
Adds existing observations sources to soca test ana prep stage.

These are all the sources produced by the db stage except for the two that turned out to be for the date 2018-04-01  instead of 2018-04-15 (bufr_tesacprof and bufr_trkobprof).

Unresolved question: Should the obs sources that start with bufr_ be changed?

Files modified:
parm/soca/obs/obs_list.yaml

Files added:
parm/soca/obs/config/bufr_dbuoyprof.yaml
parm/soca/obs/config/bufr_mbuoybprof.yaml
parm/soca/obs/config/bufr_sfcships.yaml
parm/soca/obs/config/bufr_sfcshipsu.yaml
parm/soca/obs/config/icec_emc.yaml
parm/soca/obs/config/icefb_gdr.yaml
parm/soca/obs/config/salt_profile_fnmoc.yaml
parm/soca/obs/config/sss_smap.yaml
parm/soca/obs/config/temp_profile_fnmoc.yaml

This runs the test without errors and produces the following files in build/test/soca/3dvar:

bkg_list.yaml
exgdas_global_marine_analysis_prep.log
gdas.t12z.adt_j3.2018041512.nc4
gdas.t12z.bufr_dbuoyprof.2018041512.nc4
gdas.t12z.bufr_mbuoybprof.2018041512.nc4
gdas.t12z.bufr_sfcships.2018041512.nc4
gdas.t12z.bufr_sfcshipsu.2018041512.nc4
gdas.t12z.icec_emc.2018041512.nc4
gdas.t12z.icefb_gdr.2018041512.nc4
gdas.t12z.salt_profile_fnmoc.2018041512.nc4
gdas.t12z.sss_smap.2018041512.nc4
gdas.t12z.sst_noaa19_l3u.2018041512.nc4
gdas.t12z.temp_profile_fnmoc.2018041512.nc4
r2d2_config.yaml

### CODE REVIEW

**Review by guillaumevernieres — COMMENTED** [review]
Thanks for doing this @AndrewEichmann-NOAA . Could you `ncview` the increment, make sure it's not all `NaNs`, which might be likely considering there are no qc filters in the obs `yaml`. Sorry, the implemented test is quite dumb at this point and is perfectly fine with NaN output.  Looks good otherwise, and we can add QC filters later.

**Review by ShastriPaturi — CHANGES_REQUESTED** [review]
The bufr_<dbuoy,,mbuoyb>prof.YYYYMMDD.nc has both sea_water_temperature and sea_water_salinity. Since the composite obsspace yaml is not implemented yet, I would suggest to rename the yamls as:
temp_bufr_<dbuoy,mbuoyb>prof.YYYYMMDD.nc with sea_water_temperature &
salt_bufr_<dbuoy,mbuoyb>prof.YYYYMMDD.nc with sea_water_salinity

add the salt_bufr_*prof yamls

**Comment by ShastriPaturi** [comment]
> Thanks for doing this @AndrewEichmann-NOAA . Could you `ncview` the increment, make sure it's not all `NaNs`, which might be likely considering there are no qc filters in the obs `yaml`. Sorry, the implemented test is quite dumb at this point and is perfectly fine with NaN output. Looks good otherwise, and we can add QC filters later.

@guillaumevernieres @AndrewEichmann-NOAA how is the dimension name "Location" being handled in SOCA?

**Comment by guillaumevernieres** [comment]
> > Thanks for doing this @AndrewEichmann-NOAA . Could you `ncview` the increment, make sure it's not all `NaNs`, which might be likely considering there are no qc filters in the obs `yaml`. Sorry, the implemented test is quite dumb at this point and is perfectly fine with NaN output. Looks good otherwise, and we can add QC filters later.
> 
> @guillaumevernieres @AndrewEichmann-NOAA how is the dimension name "Location" being handled in SOCA?

It's a `ioda` thing @ShastriPaturi , not a `soca` thing.

**Comment by AndrewEichmann-NOAA** [comment]
@ShastriPaturi @guillaumevernieres 
Are the contents of build/test/soca/3dvar the increments? 
No nans in there, but:
./soca/test/Data/obs/icefb.nc and its offspring have strange observation values (blanks, negatives), and no units (for freeboard).
The lat/lons for bufr_dbuoyprof are all -90,0 which seems improbable.
And what are PreQc values and should they be preserved?

**Review by guillaumevernieres — CHANGES_REQUESTED** [review]
Ha! I wasn't paying attention again. @AndrewEichmann-NOAA , to properly trigger the `ci` you need to add the `Hera-RT` and `Orion-RT` labels and wait patiently ... You're not supposed to be the one adding the `passed` labels :) . Nice try though!

I'm pretty sure the `ci` will fail:
1. I have not implemented sea-ice DA yet, so the seaice `ufo` should fail
2. What @ShastriPaturi pointed at, `Location` vs `nlocs` should be a failure point as well 

Where did you run the `ctest` @AndrewEichmann-NOAA ?

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Ah, I thought that was too easy.

I ran the ctest on hera, only through the prep.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Ah, I thought that was too easy.
> 
> I ran the ctest on hera, only through the prep.

No worries @AndrewEichmann-NOAA , but you definitely need to run `soca_run` since it depends on `soca_prep`

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Comment by ShastriPaturi** [comment]
> The bufr_<dbuoy,,mbuoyb>prof.YYYYMMDD.nc has both sea_water_temperature and sea_water_salinity. Since the composite obsspace yaml is not implemented yet, I would suggest to rename the yamls as: temp_bufr_<dbuoy,mbuoyb>prof.YYYYMMDD.nc with sea_water_temperature & salt_bufr_<dbuoy,mbuoyb>prof.YYYYMMDD.nc with sea_water_salinity
> 
> add the salt_bufr_*prof yamls

@AndrewEichmann-NOAA are you planning to do the above?
@guillaumevernieres is the above something that needs to be done?

**Comment by guillaumevernieres** [comment]
> > The bufr_<dbuoy,,mbuoyb>prof.YYYYMMDD.nc has both sea_water_temperature and sea_water_salinity. Since the composite obsspace yaml is not implemented yet, I would suggest to rename the yamls as: temp_bufr_<dbuoy,mbuoyb>prof.YYYYMMDD.nc with sea_water_temperature & salt_bufr_<dbuoy,mbuoyb>prof.YYYYMMDD.nc with sea_water_salinity
> > add the salt_bufr_*prof yamls
> 
> @AndrewEichmann-NOAA are you planning to do the above? @guillaumevernieres is the above something that needs to be done?

Eventually @ShastriPaturi , but not as part of this pr.

**Review by ShastriPaturi — APPROVED** [review]
Thanks

**Comment by AndrewEichmann-NOAA** [comment]
@ShastriPaturi @guillaumevernieres Do we want to put the renaming in a different issue with whatever else along those lines belongs there?

**Comment by guillaumevernieres** [comment]
> @ShastriPaturi @guillaumevernieres Do we want to put the renaming in a different issue with whatever else along those lines belongs there?

Yes @AndrewEichmann-NOAA .

**Pull request merged**
