### PR TITLE
Changes nc4 file suffix to nc on IODA observation files

### LINKED ISSUE #1215: Change IODA observation filename suffixes from nc4 to nc
There is rumored to be a directive to have all IODA observation files have the suffix `nc`, as opposed to `nc4`

### PR DESCRIPTION
**Pull request by AndrewEichmann-NOAA**
Tested with SOCA ctest on Hera

Resolves https://github.com/NOAA-EMC/GDASApp/issues/1215

### CODE REVIEW

**Review by guillaumevernieres — CHANGES_REQUESTED** [review]
it's a bit more involved than this @AndrewEichmann-NOAA , prep and post will probably be affected and probably the archiving task in the g-w.

**Comment by AndrewEichmann-NOAA** [comment]
> it's a bit more involved than this @AndrewEichmann-NOAA , prep and post will probably be affected and probably the archiving task in the g-w.

Is there a test (a manual one, a condition to be met) that would satisfy these issues?

**Comment by guillaumevernieres** [comment]
> > it's a bit more involved than this @AndrewEichmann-NOAA , prep and post will probably be affected and probably the archiving task in the g-w.
> 
> Is there a test (a manual one, a condition to be met) that would satisfy these issues?

beyond the ctests that we already have?

**Comment by guillaumevernieres** [comment]
my grepping says you missed "nc4" in `exgdas...post.py`

**Comment by AndrewEichmann-NOAA** [comment]
The ctests work without the change in post, so maybe there should be something else considered, assuming this goes forward

**Comment by guillaumevernieres** [comment]
> The ctests work without the change in post, so maybe there should be something else considered, assuming this goes forward

that's a problem for sure, our ctest only check if stuff ran without failure, it's useful but a bit primitive!

**Review by apchoiCMD — APPROVED** [review]

**Comment by CoryMartin-NOAA** [comment]
Do we still need this PR when we are in the process of going to JCB?

**Pull request closed without merging**
