### PR TITLE
Feature/sprint ioda converters

### PR DESCRIPTION
**Pull request by ADCollard**
Merge changes from `Feature/sprint_ioda_converters` into `develop`.

This will change the [CMakeLists.txt](https://github.com/NOAA-EMC/GDASApp/blob/feature/sprint-ioda-converters/CMakeLists.txt) to point to develop versions of the JEDI repositories and changes the yamls in [parm/atm/obs/testing](https://github.com/NOAA-EMC/GDASApp/tree/feature/sprint-ioda-converters/parm/atm/obs/testing) (as well as some in [parm/atm/obs/config](https://github.com/NOAA-EMC/GDASApp/tree/feature/sprint-ioda-converters/parm/atm/obs/config) to use the new IODA format.

The benchmark tests will still fail for these test YAMLs (to be addressed this week!) but there should be no failures because of IODA naming convention issues.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@ADCollard , looks like the conflict is on the marine DA side. I'll push the fix.

**Comment by ADCollard** [comment]
> @ADCollard , looks like the conflict is on the marine DA side. I'll push the fix.

@guillaumevernieres Sorry just saw this.  I think I already fixed it.

**Comment by guillaumevernieres** [comment]
I'm looking at the issue today @ADCollard but I might have to build from scratch, I don't think I have a recent-ish develop build on hpc.

**Comment by guillaumevernieres** [comment]
@jiaruidong2017 , could you look at the snow DA issue?

**Comment by jiaruidong2017** [comment]
> @jiaruidong2017 , could you look at the snow DA issue?

@guillaumevernieres Do I need to build the GDASApp from scratch for testing the snow DA ctests? Thanks.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 you'd have to build from scratch starting with this branch, not develop

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA Okay, I will do it.

**Comment by ADCollard** [comment]
> @CoryMartin-NOAA Okay, I will do it.

@jiaruidong2017 In case you have not found this yet, I think the issue is that the variable names in `adpsfc_snow.nc4` need to be updated.   This is failing because `nlocs` should be `Location`

**Comment by jiaruidong2017** [comment]
> > @CoryMartin-NOAA Okay, I will do it.
> 
> @jiaruidong2017 In case you have not found this yet, I think the issue is that the variable names in `adpsfc_snow.nc4` need to be updated. This is failing because `nlocs` should be `Location`

Thanks @ADCollard I will make the changes and test it.

**Comment by guillaumevernieres** [comment]
@ADCollard , I can't replicate the `hera` `ci` error from above ... If it fails the next time around, I'll just comment out the `soca` test and submit a separate bugfix later. 

We should ignore `orion` `ci` for now. I suspect that some of the test that failed just ran out of time.

**Comment by guillaumevernieres** [comment]
I don't like these big interconnected pr's ....
@ADCollard , @RussTreadon-NOAA , @CoryMartin-NOAA , @jiaruidong2017 : I'm planning to comment out the failing test and create issues for each of the failure. We could then merge that branch and resolve the individual issues separately later.
I'm stuck in meetings 'till 12, so if any of you is in a "commenting out mood", go for it! The list is above.

I actually have ~40mn ... doing it now.

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres my first guess is this is an input obs issue. Namely `location` vs `nlocs`

**Comment by jiaruidong2017** [comment]
> @guillaumevernieres my first guess is this is an input obs issue. Namely `location` vs `nlocs`

@CoryMartin-NOAA I totally agree with you. I am working on the input obs data by changing the dimension from `nlocs` to `Location`. Does anybody have any tools to do this? Thanks.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres my first guess is this is an input obs issue. Namely `location` vs `nlocs`

Could be for some @CoryMartin-NOAA , but it's not the issue for soca. Testing my `#` and I'll push the "fix" before 9am.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 There is an ioda-upgrader utility that is built as part of IODA. I think it is called ioda-upgrade-v2-v3.x or something similar to that.

**Comment by guillaumevernieres** [comment]
The power of # :) ... Well, maybe, the earlier failure was different ...

@CoryMartin-NOAA , @ADCollard , @RussTreadon-NOAA  and @jiaruidong2017 , I commented out these ctests:
```
	1346 - test_gdasapp_land_letkfoi_snowda (Failed)
	1352 - test_gdasapp_atm_jjob_var_run (Failed)
	1355 - test_gdasapp_atm_jjob_ens_run (Failed)
```
and removed the problematic obs op for these guys:
```
	1335 - test_gdasapp_soca_ana_run (Failed)
	1340 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN (Failed)
	1342 - test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY (Failed)
```

**Comment by guillaumevernieres** [comment]
> > @guillaumevernieres my first guess is this is an input obs issue. Namely `location` vs `nlocs`
> 
> @CoryMartin-NOAA I totally agree with you. I am working on the input obs data by changing the dimension from `nlocs` to `Location`. Does anybody have any tools to do this? Thanks.

@jiaruidong2017 , create a new issue and a new branch. You'll issue a pr bug fix after this one is merged. I commented out some of our failing tests (it's not just you :) ). It just isn't practical to be 3-4 developers trying to fix bugs in the same branch.

**Comment by jiaruidong2017** [comment]
@guillaumevernieres Okay, and I will create a bugfix issue and pr for snow DA application. Thanks.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by CoryMartin-NOAA** [comment]
One another code manager approves, this can be merged in with the understanding that @guillaumevernieres @jiaruidong2017 and others (@ADCollard @RussTreadon-NOAA @CoryMartin-NOAA ) will resolve the failing tests ASAP in bugfix branches over the coming few days.

**Comment by RussTreadon-NOAA** [comment]
Check `test_gdasapp_atm_jjob_var_run` failure.   This job only processes `amsua_n19`.   Two problems identified:

- `parm/atm/obs/config/amsua_n19.yaml` uses `brightness_temperature` instead of `brightnessTemperature`
- `/work2/noaa/da/cmartin/GDASApp/R2D2_SHARED/ncdiag/ob/oper_gdas/PT6H/2021-03-23/ncdiag.oper_gdas.ob.PT6H.amsua_n19.2021-03-23T15:00:00Z.nc4` contains `brightness_temperature`

The first is easily fixed.  We simply replace `brightness_temperature` with `brightnessTemperature` in `amsua_n19.yaml`.   I'm not sure how to change the `brightness_temperature` string in the amsua_n19.nc4 file.

Fixing amsua_n19 for the var_run test will help the ens_run test.   The ens test processes amsua_n19 data.   However, it uses a different observation yaml, `parm/atm/obs/config/lgetkf_amsua_n19.yaml`.    This file needs updating.   

The ens_run test also proceses sondes.    File `lgetkf_sondes.yaml` likely needs updating.   The input sondes.nc4 file  (`/work2/noaa/da/cmartin/GDASApp/R2D2_SHARED/ncdiag/ob/oper_gdas/PT6H/2021-03-23/ncdiag.oper_gdas.ob.PT6H.sondes.2021-03-23T15:00:00Z.nc4`) also needs updating.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I think there should be a utility in the build/bin directory, something like `ioda-upgrade-v2-v3.x` (not sure of the exact name currently), it can 'upgrade' the IODA ob to use the new names and conventions. Feel free to give it a try, otherwise I can work to 'upgrade' the data on orion later this afternoon.

**Review by guillaumevernieres — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
> * /work2/noaa/da/cmartin/GDASApp/R2D2_SHARED/ncdiag/ob/oper_gdas/PT6H/2021-03-23/ncdiag.oper_gdas.ob.PT6H.amsua_n19.2021-03-23T15:00:00Z.nc4

Thanks @CoryMartin-NOAA.  I executed `./ioda-upgrade-v2-to-v3.x` on above mentioned amsua_n19.nc4.   The new amsua_n19.nc4 file differs from the original but `brightness_temperature` remains in a ncdump listing.    A rerun of `test_gdasapp_atm_jjob_var_run` failed with 
```
1363: 0: amsua_n19 processed vars: 15 variables: brightness_temperature_1, brightness_temperature_2, brightness_temperature_3, brightness_temperature_4, brightness_temperature_5, brightness_temperature_6, brightness_temperature_7, brightness_temperature_8, brightness_temperature_9, brightness_temperature_10, brightness_temperature_11, brightness_temperature_12, brightness_temperature_13, brightness_temperature_14, brightness_temperature_15
1363: 0: amsua_n19 assimilated vars: 15 variables: brightnessTemperature_1, brightnessTemperature_2, brightnessTemperature_3, brightnessTemperature_4, brightnessTemperature_5, brightnessTemperature_6, brightnessTemperature_7, brightnessTemperature_8, brightnessTemperature_9, brightnessTemperature_10, brightnessTemperature_11, brightnessTemperature_12, brightnessTemperature_13, brightnessTemperature_14, brightnessTemperature_15
1363: 2: Exception: UserError: brightnessTemperature_1 is specified as a simulated variable but it has not been specified as an observed or a derived variable.  (/work/noaa/da/rtreadon/git/global_workflow/pr328/sorc/gdas.cd/ioda/src/ObsSpace.cc +212 ObsSpace)
```
 I don't think I used the correct yaml file with `ioda-upgrade-v2-to-v3.x`.  I used a copy of `parm/atm/obs/config/amsua_n19.yaml` with `brightnessTemperature` replacing `brightness_temperature`.  Which yaml file should I use?

**Comment by ADCollard** [comment]
@RussTreadon-NOAA The syntax is `ioda-upgrade-v2-to-v3.x input_file output_file ObsSpace.yaml`

The `ObsSpace.yaml` is [here](https://github.com/JCSDA-internal/ioda/blob/develop/share/ioda/yaml/validation/ObsSpace.yaml)

**Comment by RussTreadon-NOAA** [comment]
> @RussTreadon-NOAA The syntax is `ioda-upgrade-v2-to-v3.x input_file output_file ObsSpace.yaml`
> 
> The `ObsSpace.yaml` is [here](https://github.com/JCSDA-internal/ioda/blob/develop/share/ioda/yaml/validation/ObsSpace.yaml)

Thank you very much @ADCollard!   The converted amsua_n19.nc4 file contains `brightnessTemperature`.   `test_gdasapp_atm_jjob_var_run` successfully ran to completion.

```
1/1 Test #1363: test_gdasapp_atm_jjob_var_run ....   Passed  169.71 sec

The following tests passed:
        test_gdasapp_atm_jjob_var_run

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 170.47 sec
```

**Comment by guillaumevernieres** [comment]
> Automated Global-Workflow GDASApp Testing Results: Machine: orion
> 
> ```
> Start: Tue Feb  7 08:31:01 CST 2023 on Orion-login-1.HPC.MsState.Edu
> ---------------------------------------------------
> Build:                                 *SUCCESS*
> Build: Completed at Tue Feb  7 09:26:58 CST 2023
> ---------------------------------------------------
> Tests:                                  *Failed*
> Tests: Failed at Tue Feb  7 09:34:30 CST 2023
> Tests: 97% tests passed, 1 tests failed out of 37
> 	1346 - test_gdasapp_soca_ana_bmat (Failed)
> Tests: see output at /work2/noaa/stmp/cmartin/CI/GDASApp/workflow/PR/328/global-workflow/sorc/gdas.cd/build/log.ctest
> ```

ha ... That's a new one!

**Comment by CoryMartin-NOAA** [comment]
I will merge this at 1830z if no objections and we will deal with the failures in bugfixes/updated input files ASAP

**Pull request merged**
