### PR TITLE
Add observation YAMLs for AMSU-A, ATMS, SSMIS, SEVIRI, and AVHRR

### PR DESCRIPTION
**Pull request by emilyhcliu**
Add observation YAMLs for AMSU-A, ATMS, SSMIS, SEVIRI, and AVHRR
Pass benchmarks are provided in the YAMLs for unit tests.

Please see the following JEDI-T2O issues for documentation and validation results:
[JEDI-T2O#42](https://github.com/NOAA-EMC/JEDI-T2O/issues/42) --- AMSU-A  (100% match)
[JEDI-T2O#44](https://github.com/NOAA-EMC/JEDI-T2O/issues/44) --- ATMS (Difference: 1 point for NPP and 5 points for N20)over south sea ice area from hydrometer check)
[JEDI-T2O#55](https://github.com/NOAA-EMC/JEDI-T2O/issues/55) --- SSMIS with Azadeh (100% match)
[JEDI-T2O#53](https://github.com/NOAA-EMC/JEDI-T2O/issues/53) --- AVHRR with Azadeh ( Difference: 1 point for  N19)
[JEDI-T2O#52](https://github.com/NOAA-EMC/JEDI-T2O/issues/52) --- SEVIRI with Xuanli (100% match)

Summary plots for validation will be posted later.

### CODE REVIEW

**Comment by ADCollard** [comment]
@emilyhcliu Apparently the develop version was not pointing to the right UFO build after all.   I just pushed a commit to update `CMakeLists.txt` to point at:
```
  ecbuild_bundle( PROJECT ufo   GIT "https://github.com/jcsda/ufo.git" BRANCH feature/gdasapp_ufo )
```

**Comment by ADCollard** [comment]
@emilyhcliu `run_ufo_hofx_test.sh` appears to still be pointing at Cory's data directories.   Can you update, please, for both Hera and Orion (there are failures for AVHRR and Seviri).

**Comment by ADCollard** [comment]
@emilyhcliu I'll work on the final AMSU-A/ATMS QC in the morning.   There will not be exact agreement, but we should be screening out obs with missing values anyway.   We don't want to be pointing to a version of CRTM that is not under change control.

**Comment by ADCollard** [comment]
> @emilyhcliu I'll work on the final AMSU-A/ATMS QC in the morning. There will not be exact agreement, but we should be screening out obs with missing values anyway. We don't want to be pointing to a version of CRTM that is not under change control.

.... actually I am going to see if I can make a modified CRTM tag....

**Comment by emilyhcliu** [comment]
> @emilyhcliu `run_ufo_hofx_test.sh` appears to still be pointing at Cory's data directories. Can you update, please, for both Hera and Orion (there are failures for AVHRR and Seviri).

Yes

**Comment by ADCollard** [comment]
With the latest changes, I get the relevant tests to pass on Hera.  I will look in detail at the summary output plots and will also test on Orion:

```
> export machine=hera
> export GDASApp=/scratch1/NCEPDEV/da/Andrew.Collard/git/GDASApp_Emily 
> ./test_yamls.sh 
aircraft.yaml Fails (boo!)
amsua_metop-a.yaml Passes (yay!)
amsua_metop-b.yaml Passes (yay!)
amsua_metop-c.yaml Passes (yay!)
amsua_n15.yaml Passes (yay!)
amsua_n18.yaml Passes (yay!)
amsua_n19.yaml Passes (yay!)
atms_n20.yaml Passes (yay!)
atms_npp.yaml Passes (yay!)
avhrr3_metop-a.yaml Passes (yay!)
avhrr3_metop-b.yaml Passes (yay!)
avhrr3_n18.yaml Passes (yay!)
avhrr3_n19.yaml Passes (yay!)
satwind.yaml Fails (boo!)
seviri_m08.yaml Passes (yay!)
seviri_m11.yaml Passes (yay!)
sfcship.yaml Fails (boo!)
sfc.yaml Fails (boo!)
sondes_ps.yaml Fails (boo!)
sondes.yaml Fails (boo!)
ssmis_f17.yaml Passes (yay!)
ssmis_f18.yaml Passes (yay!)
```

**Review by CoryMartin-NOAA — APPROVED** [review]
Did not test, but assuming it will be all good once @ADCollard finishes his tests. Thanks a lot @emilyhcliu for all of your hard work on this and getting it in GDASApp!

**Comment by ADCollard** [comment]
[This IODA PR ](https://github.com/JCSDA-internal/ioda/pull/901) broke the eva scripts which meant I could not produce the output plots.  A one line change to `ush/eva/gen_eva_obs.yaml' fixes this and was pushed [here](https://github.com/NOAA-EMC/GDASApp/pull/360/commits/99107fd1332466f90474acb6e340dbef759b13aa).

**Comment by ADCollard** [comment]
@emilyhcliu @CoryMartin-NOAA 

I am happy with the PR now.  I am including the plots that show the biggest discrepancies below, but I think these are all within reasonable bounds.
ObsErr_Difference_diag_amsua_metop-a

ObsErr_Difference_diag_amsua_n18

ObsErr_Difference_diag_amsua_n19

QCCount_Diff_diag_atms_n20

QCCount_Diff_diag_atms_npp

QCCount_Diff_diag_avhrr3_n19

**Comment by ADCollard** [comment]
@CoryMartin-NOAA I approve this request but to be doubly sure (as I have been making multiple changes to this PR myself) can you do a clean checkout and build of this branch and run `ush/ufoeval/test_yamls.sh` as in [this comment](https://github.com/NOAA-EMC/GDASApp/pull/360#issuecomment-1433259909).

Note that there should be no need to change any files as long as the `GDASApp` and `machine` environment variables are set correctly.

**Review by ADCollard — APPROVED** [review]
@CoryMartin-NOAA I approve this request but to be doubly sure (as I have been making multiple changes to this PR myself) can you do a clean checkout and build of this branch and run `ush/ufoeval/test_yamls.sh` as in [this comment](https://github.com/NOAA-EMC/GDASApp/pull/360#issuecomment-1433259909)?

Note that there should be no need to change any files as long as the `GDASApp` and `machine` environment variables are set correctly.

**Comment by CoryMartin-NOAA** [comment]
note that I also had to set `$STMP` to get this to run but so far it says:
```
./test_yamls.sh 
aircraft.yaml Fails (boo!)
amsua_metop-a.yaml Passes (yay!)
amsua_metop-b.yaml Passes (yay!)
amsua_metop-c.yaml Passes (yay!)
amsua_n15.yaml Passes (yay!)
amsua_n18.yaml Passes (yay!)
amsua_n19.yaml Passes (yay!)
atms_n20.yaml Passes (yay!)
```
I'm impatient and going home now but I think this is sufficient to say it is ready to merge, thus I will do so :-)

**Pull request merged**
