### PR TITLE
Make cloning JCSDA test data repositories optional

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
In anticipation of the ability to make the building of JEDI ctests optional, this PR adds the cloning of the JCSDA test data repositories (ufo-data, fv3-jedi-data, etc.) optional.

### CODE REVIEW

**Comment by aerorahul** [comment]
It is likely the tests will be enabled/disabled by the conventional CMake option `-DENABLE_TESTS=ON|OFF`.
Can one not cue from that? i.e. if `-DENABLE_TESTS=ON`, then download the test data?

Other than that, I have no opinion.  The changes seem to do the same thing, albeit introduces a `CLONE_JCSDADATA` option.

**Comment by CoryMartin-NOAA** [comment]
@aerorahul I want to distinguish between their tests and ours though, because I suspect we may want ~50 ctests for GDAS that we write that are not the 1500 bundle tests. I feel like ENABLE_TESTS is too generic and wanted to avoid that

**Review by guillaumevernieres — APPROVED** [review]
Approving your PR preemptively @CoryMartin-NOAA to jinx the `ci`!

**Comment by guillaumevernieres** [comment]
Great ... So I can jinx myself but not others ... A good addition to my list of useless powers.
Thanks for doing that work @CoryMartin-NOAA .

**Pull request merged**
