### PR TITLE
Plot marine DA stuff

### LINKED ISSUE #453: First step towards monitoring the DA cycle within the g-w
Add a j-job/script that will allow plotting a few basic figures of the background error and increment.

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
- Addition of a verification script for the marine DA. It does very little for now. I'd like to keep the state space plotting a simple and low level as possible.
- No more linking of the DA output in the `COM` directly. Instead post does the copying of the stuff we want to keep from the cycle and :bomb: 's  `DATA`.
- Don't get to hung-up on the plotting scripts, it will be revisited. It's not great but it does things like plotting slices (horizontal/zonal) of the background error and increment. We'll add EVA stuff later.

fixes [godas/453](https://github.com/noaa-emc/godas/issues/453)

## Testing
- [x] JCSDA container
- [x] Hera
- [x] ~~Orion~~ <--- **BAD BAD uncooperative MACHINE**
We need a dedicated plotting environment for HPC ...  And the `EVA` module (at least on hera) is missing some dependencies requiered by `ufsda`.

## Dependencies
waiting for its companion PR [g-w/1270](https://github.com/NOAA-EMC/global-workflow/pull/1270) to be merged before I un-draft this PR.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
## Build issue on Orion:

### This is what the `CI` reports
```
Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be removed \
from $MODULEPATH.
 .... Building gfs_utils ....
 .... Building WW3 pre and post execs ....
Fatal error in building WW3 pre/post processing.
The log file is in /work2/noaa/stmp/cmartin/CI/GDASApp/workflow/PR/286/global-workflow/sorc/logs/build_ww3_prepost.log
 .... Building forecast model ....
Fatal error in building UFS model.
The log file is in /work2/noaa/stmp/cmartin/CI/GDASApp/workflow/PR/286/global-workflow/sorc/logs/build_ufs.log
 .... Skip building gsi and enkf ....
 .... Building gsi utilities ....
 .... Building GDASApp  ....
 .... Building gsi monitor ....
 .... Building UPP ....
 .... Building ufs_utils ....
 .... Building gldas ....
BUILD ERROR: One or more components failed to build
  Check the associated build log(s) for details.
```
### My own testing
```
Building GDASApp on orion
Lmod has detected the following error:  Unable to load module because of error when evaluating modulefile:
     /work2/noaa/da/gvernier/pr/global-workflow/sorc/gdas.cd/modulefiles/GDAS/orion.lua: /apps/lmod/lmod/libexec/DirTree.lua:183: interrupted!
     Please check the modulefile and especially if there is a the line number specified in the above message 
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    GDAS/orion       /work2/noaa/da/gvernier/pr/global-workflow/sorc/gdas.cd/modulefiles/GDAS/orion.lua
```

## Bye bye Orion!!!
I'm marking that PR as ready and ignoring orion.

**Comment by guillaumevernieres** [comment]
It works on orion. 
See figures here:
```
/work2/noaa/da/gvernier/pr/global-workflow/sorc/gdas.cd/build/test/soca/gw/testrun/testjjobs/ROTDIRS/gdas_test/gdas.20180415/12/ocean/vrfy
```

And here's the chunck of tests relevant to this pr:
```
(gdasapp) Orion-login-4:/work2/noaa/da/gvernier/pr/global-workflow/sorc/gdas.cd/build/test$ ctest -I 22,27
Test project /work2/noaa/da/gvernier/pr/global-workflow/sorc/gdas.cd/build/test
    Start 22: test_gdasapp_soca_run_clean
1/6 Test #22: test_gdasapp_soca_run_clean ..........................   Passed    0.02 sec
    Start 23: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
2/6 Test #23: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP ...   Passed  106.56 sec
    Start 24: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT
3/6 Test #24: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT ...   Passed   74.18 sec
    Start 25: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN
4/6 Test #25: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN ....   Passed   42.17 sec
    Start 26: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST
5/6 Test #26: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST ...   Passed   10.22 sec
    Start 27: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY
6/6 Test #27: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY ...   Passed  138.38 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 371.54 sec
```
... resubmitting the automated `ci`.

**Comment by guillaumevernieres** [comment]
... last try on orion ...

**Review by RussTreadon-NOAA — APPROVED** [review]
Hera and Orion GW-RT tests pass.   Approve.

**Review by ShastriPaturi — APPROVED** [review]
Tests pass on hera.
Orion super slow... giving up.

**Comment by guillaumevernieres** [comment]
Thanks for the reviews!

**Pull request merged**
