### PR TITLE
Update ozone YAML files

### PR DESCRIPTION
**Pull request by emilyhcliu**
Ozone data evaluation for UFO is re-accessed.  In the previous assessment, the input test data files contained only data assimilated.  

See[ Issue#85 ](https://github.com/NOAA-EMC/JEDI-T2O/issues/85)
 - Test dataset for ozone updated
 - Modify existing YAMLs to match GSI results
 - Benchmarks are added
 - Add both HofX  and QC tests

These YAMLs can 100% replicate GSI results.

### CODE REVIEW

**Comment by emilyhcliu** [comment]
### OMI AURA
gsi_hofx_vs_jedi_hofx_omi_aura_diag_2021080100_omi_aura_ozoneTotal
hofxdiff_histogram_omi_aura_diag_2021080100_omi_aura_ozoneTotal
errordiff_histogram_omi_aura_diag_2021080100_omi_aura_ozoneTotal
hofxdiff_vs_qcdiff_omi_aura_diag_2021080100_omi_aura_ozoneTotal

**Comment by emilyhcliu** [comment]
### OMPSNP NPP
gsi_hofx_vs_jedi_hofx_ompsnp_npp_diag_2021080100_ompsnp_npp_ozoneLayer
hofxdiff_histogram_ompsnp_npp_diag_2021080100_ompsnp_npp_ozoneLayer
-7cbc-4fb0-99f2-51ef08a17561)
hofxdiff_vs_qcdiff_ompsnp_npp_diag_2021080100_ompsnp_npp_ozoneLayer

**Comment by emilyhcliu** [comment]
### OMPSTC8 NPP
 
gsi_hofx_vs_jedi_hofx_ompstc8_npp_diag_2021080100_ompstc8_npp_ozoneTotal
hofxdiff_histogram_ompstc8_npp_diag_2021080100_ompstc8_npp_ozoneTotal
errordiff_histogram_ompstc8_npp_diag_2021080100_ompstc8_npp_ozoneTotal
hofxdiff_vs_qcdiff_ompstc8_npp_diag_2021080100_ompstc8_npp_ozoneTotal

**Review by CoryMartin-NOAA — APPROVED** [review]
Looks good, thanks @emilyhcliu . Any reason why this should not go into develop instead of the `conv_ps` feature branch?

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA No specific reason.   Once the feature/conv_ps is merged, I will merge the develop into feature/conv_ps_o3.  
My other feature branches in the PR are based on the develop.

**Review by CoryMartin-NOAA — DISMISSED** [review]
Approved. Note to rebase and merge to develop once #628 is merged

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
