### PR TITLE
Bring jcb into GDASapp and use version of jcb not using submodules

### PR DESCRIPTION
**Pull request by danholdaway**
Bring jcb into the GDASapp repo and use the versions of jcb that do not use submodules:

- https://github.com/NOAA-EMC/jcb/pull/9
- https://github.com/NOAA-EMC/jcb-gdas/pull/16

There is a GW branch of the same name and I will make a PR there once this is merged. https://github.com/danholdaway/global-workflow/tree/feature/move_jcb

### CODE REVIEW

**Review by CoryMartin-NOAA — DISMISSED** [review]

**Comment by RussTreadon-NOAA** [comment]
@danholdaway , the changes in GDASApp branch [`feature/move_jcb`](https://github.com/NOAA-EMC/GDASApp/tree/feature/move_jcb) have been tested in g-w PR [#2665](https://github.com/NOAA-EMC/global-workflow/pull/2665).  Everything looks _good_.   g-w PR [#2655](https://github.com/NOAA-EMC/global-workflow/pull/2665/files) has been approved by Cory, Rahul, and me.  Another _good_.

However, I now see a problem.   

g-w PR [#2655](https://github.com/NOAA-EMC/global-workflow/pull/2665) merges your forked g-w branch [danholdaway:feature/move_jcb](https://github.com/danholdaway/global-workflow/tree/feature/move_jcb) into g-w `develop`.  The forked g-w `feature/move_jcb` currently points at [gdas.cd @ 0cda73b](https://github.com/NOAA-EMC/GDASApp/tree/0cda73bab89af06fa9fccd172cad43fb04e5281c).   This is problematic.  This hash is GDASApp branch `feature/move_jcb`.  

I think we want g-w `develop` to point at GDASApp `develop`, right? If so, we need to merge this PR into `develop` and then update the `gdas.cd` hash in [danholdaway:feature/move_jcb](https://github.com/danholdaway/global-workflow/tree/feature/move_jcb) accordingly.

**Comment by danholdaway** [comment]
That is correct @RussTreadon-NOAA. But as soon as we merge GDASapp everything will be broken while we wait for the GW PR to be merged. Alternatively we can merge G-W and then GDASapp and then make another g-w PR changing the hash to develop. That’s the only way that everything continues to work. What do you think? Is that acceptable?

**Review by RussTreadon-NOAA — APPROVED** [review]
Tested as part of g-w [#2565](https://github.com/NOAA-EMC/global-workflow/pull/2665).  Looks good.

Approve.

**Comment by RussTreadon-NOAA** [comment]
@danholdaway , OK.  I see your logic.  I never thought of having g-w point at a GDASApp branch instead of `develop`.  This works. 
 g-w `gdas.cd` points at a GDASApp hash.  g-w doesn't care if that hash is GDASApp `develop`, a branch, or a tag.

Your approach allows us to bypass the sequential method I've been using:  GDASApp first and then g-w.  

g-w PR [#2665](https://github.com/NOAA-EMC/global-workflow/pull/2665) can move ahead _as is_.  After this GDASApp PR is merged into GDASApp `develop` we can decide if we want to open a new g-w PR to point at the updated GDASApp `develop` or let one of our other GDASApp-based g-w PRs (e.g., #[2654](https://github.com/NOAA-EMC/global-workflow/pull/2654), [#2641](https://github.com/NOAA-EMC/global-workflow/pull/2641)) do this.

**Comment by danholdaway** [comment]
@RussTreadon-NOAA perhaps in this instance we merge down from g-w to gdas to jcb. Just because it takes longest to get something into g-w wheres we can more quickly merge the others. And in terms of the code pointed to in the hashes it would be equivalent

**Comment by CoryMartin-NOAA** [comment]
if it's an unchanged squash commit, is the hash identical in the branch and after merged to develop?

**Comment by RussTreadon-NOAA** [comment]
Works for me.  Just want to get as many of your changes into `develop` as soon as possible.

**Comment by danholdaway** [comment]
> if it's an unchanged squash commit, is the hash identical in the branch and after merged to develop?

No because you have to squash all the commits with a new hash. But the code that gets run would be identical I think.

**Comment by danholdaway** [comment]
Lets say we merge g-w, then gdas then jcb. Then immediately merged upward jcb, gdas, g-w so that the hashes were the hashes develop points to for each repo...I think the latter would be a sequence of empty PRs. In the g-w case they might even reject the PR, as Rahul did when I tried to bump the hash of GSI utils despite no changes. I might actually try that to see if that theory is correct after these are merged. For non-breaking changes it wouldn't matter which way you merged.

**Comment by RussTreadon-NOAA** [comment]
g-w PR [#2665](https://github.com/NOAA-EMC/global-workflow/pull/2665) was merged into g-w [develop](https://github.com/NOAA-EMC/global-workflow/commits/develop/) at [5af325a](https://github.com/NOAA-EMC/global-workflow/commit/5af325a6a4e0a14d180514a418603ca79fada487) (6/13/2024).  g-w PR [#2665](https://github.com/NOAA-EMC/global-workflow/pull/2665) points g-w `gdas.cd` at GDASApp branch `feature/move_jcb` at [368c9c5](https://github.com/NOAA-EMC/GDASApp/commit/368c9c5db9b5ea62e72937b6d1b0f753adb9be40).  

We should merge this PR into GDASApp `develop` and update the g-w `gdas.cd` hash to point at the updated GDASApp `develop`.

**Comment by RussTreadon-NOAA** [comment]
**Orion test**
Install `feature/move_jcb` on Orion in g-w `develop`.  Run `test_gdasapp`.  48 out of 48 tests pass
```
Test project /work2/noaa/da/rtreadon/git/global-workflow/test/sorc/gdas.cd/build
      Start 1489: test_gdasapp_util_coding_norms
 1/48 Test #1489: test_gdasapp_util_coding_norms ........................   Passed    5.24 sec
      Start 1490: test_gdasapp_util_ioda_example
 2/48 Test #1490: test_gdasapp_util_ioda_example ........................   Passed    4.55 sec

...

      Start 1869: test_gdasapp_atm_jjob_ens_final
47/48 Test #1869: test_gdasapp_atm_jjob_ens_final .......................   Passed   42.23 sec
      Start 1870: test_gdasapp_aero_gen_3dvar_yaml
48/48 Test #1870: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    0.77 sec

100% tests passed, 0 tests failed out of 48

Label Time Summary:
gdas-utils    =  17.38 sec*proc (11 tests)
script        =  17.38 sec*proc (11 tests)

Total Test time (real) = 1675.41 sec
```

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , given successful CI on Hera (automated tests) and Orion, I'd like to merge this PR into `develop`.  Any objections?

**Review by guillaumevernieres — APPROVED** [review]

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres , given successful CI on Hera (automated tests) and Orion, I'd like to merge this PR into `develop`. Any objections?

sounds good @RussTreadon-NOAA

**Comment by RussTreadon-NOAA** [comment]
This PR has two companion PRs
- jcb [#9](https://github.com/NOAA-EMC/jcb/pull/9)
- jcb-gdas [#16](https://github.com/NOAA-EMC/jcb-gdas/pull/16)

Both have already been approved by @CoryMartin-NOAA.  Given this, we should merge these jcb PRs as part of merging this PR.  Note that `feature/move_jcb` already points at the appropriate jcb hashes so we don't need to update jcb hashes used by this PR.

**Pull request merged**
