### PR TITLE
Modify the yamltools to enable for generating yaml file for land DA.

### PR DESCRIPTION
**Pull request by jiaruidong2017**
The bugfix in PR #185 broke the land DA in generating the yaml file. The proposed PR with the minor fixes enable the capability to generate the yaml file for land DA tests.

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]
This looks good, but we should test to make sure :-)

**Comment by jiaruidong2017** [comment]
Sure. Thanks @CoryMartin-NOAA

**Review by RussTreadon-NOAA — COMMENTED** [review]
Change is straightforward.  Agree with @CoryMartin-NOAA .  This needs to be tested in various DA modes to ensure no unintended consequences.

**Comment by guillaumevernieres** [comment]
@jiaruidong2017 , click on the 2 RT labels (one for Hera and one for Orion):

hera-rt

This will trigger the build and test of your branch on both machines.

**Comment by jiaruidong2017** [comment]
@guillaumevernieres Just added two RT labels. Thank you.

**Review by guillaumevernieres — APPROVED** [review]
All good, thanks for fixing the issue @jiaruidong2017 .

**Comment by jiaruidong2017** [comment]
Thanks @guillaumevernieres

**Pull request merged**
