### PR TITLE
The DA only uses the gdas bkg ... fixing again ...

### LINKED ISSUE #1078: The gfs is not used as background (yet)
https://github.com/NOAA-EMC/GDASApp/blob/7ecfc17f9df39859b340c8ba81c3c27bfb5f18ac/ush/soca/bkg_utils.py#L104

Looks like I missed this when @AndrewEichmann-NOAA cleaned-up the background staging utility. The background for the DA should come from the `gdas` fcst, always.

### PR DESCRIPTION
**Pull request by guillaumevernieres**
- fixes #1078

### CODE REVIEW

**Review by AndrewEichmann-NOAA — DISMISSED** [review]

**Review by CatherineThomas-NOAA — DISMISSED** [review]
Looks good to me, pending successful testing.

**Comment by JessicaMeixner-NOAA** [comment]
I'll point to this branch and restart the C384 tests i was running

**Review by AndrewEichmann-NOAA — DISMISSED** [review]
looks even better

**Review by AndrewEichmann-NOAA — APPROVED** [review]
still looks good

**Pull request merged**
