### PR TITLE
Update atmospheric var and lgetkf ctests to use radiance bias correction tarball

### LINKED ISSUE #1264: Modify atm_jjob_var and atm_jjob_ens ctests to work with radiance bias correction tarballs
Global-workflow issue [#2862](https://github.com/NOAA-EMC/global-workflow/issues/2862) modifies g-w `ush/python/pygfs/task` scripts `analysis.py` and `atm_analysis.py` to move, copy, and link JEDI radiance bias correction files as a single tarball instead of multiple _satellite_sensor_ based files.   This change necessitates changes to the atmospheric variational and local ensemble atmospheric DA ctests.

This issue is opened to document the required changes to these ctests.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
This PR updates the drivers for the atmospheric local ensemble (lgetff) and variational DA ctests to populate the test `ROTDIR` with a tarball containing radiance bias correction files.  Previously the drivers copied radiance bias correction files for individual _satellite_sensors_.  

This PR requires the atmospheric radiance bias corrections files used in the ctests be collected into a tarball.  This needs to be done on Hera, Hercules, Cactus, and Dogwood.  For the time being both the individual _satellite_sensor_ bias correction and tarball remain in `GDASAPP_TESTDATA`.  The _satellite_sensor_ files may be removed at  a later date.

The full suite of `test_gdasapp` tests were executed on Hera and results reported in #1264.  All tests _Passed_.

Resolves #1264

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Given [conversation](https://github.com/NOAA-EMC/global-workflow/pull/2875#pullrequestreview-2267242429) in g-w PR [#2875](https://github.com/NOAA-EMC/global-workflow/pull/2875), rename `radbcor` radiance bias correction tarball as `rad_varbc_params.tar`.  Filename change made to JEDI atmospheric ctests `jjob_ens_init.sh` and `jjob_var_init.sh`.  Done at c9c5955.

**Comment by RussTreadon-NOAA** [comment]
GDASApp `feature/radbcor` at 554c55a was built on Hera inside g-w `feature/radbcor` at [`5985e9f`](https://github.com/RussTreadon-NOAA/global-workflow/commit/5985e9f718ded5316007f6d38ac16b5abb2c9649).  

All 48 `test_gdasapp` tests _Passed_.
```
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/radbcor/sorc/gdas.cd/build
      Start 1531: test_gdasapp_util_coding_norms
 1/48 Test #1531: test_gdasapp_util_coding_norms ........................   Passed    2.38 sec
      Start 1532: test_gdasapp_util_ioda_example
 2/48 Test #1532: test_gdasapp_util_ioda_example ........................   Passed    3.94 sec
      Start 1533: test_gdasapp_util_prepdata
 3/48 Test #1533: test_gdasapp_util_prepdata ............................   Passed    1.21 sec
      Start 1534: test_gdasapp_util_rads2ioda
 4/48 Test #1534: test_gdasapp_util_rads2ioda ...........................   Passed    0.18 sec
      Start 1535: test_gdasapp_util_ghrsst2ioda
 5/48 Test #1535: test_gdasapp_util_ghrsst2ioda .........................   Passed    0.14 sec
      Start 1536: test_gdasapp_util_rtofstmp
 6/48 Test #1536: test_gdasapp_util_rtofstmp ............................   Passed    0.99 sec
      Start 1537: test_gdasapp_util_rtofssal
 7/48 Test #1537: test_gdasapp_util_rtofssal ............................   Passed    0.77 sec
      Start 1538: test_gdasapp_util_smap2ioda
 8/48 Test #1538: test_gdasapp_util_smap2ioda ...........................   Passed    0.14 sec
      Start 1539: test_gdasapp_util_smos2ioda
 9/48 Test #1539: test_gdasapp_util_smos2ioda ...........................   Passed    0.14 sec
      Start 1540: test_gdasapp_util_viirsaod2ioda
10/48 Test #1540: test_gdasapp_util_viirsaod2ioda .......................   Passed    0.16 sec
      Start 1541: test_gdasapp_util_icecamsr2ioda
11/48 Test #1541: test_gdasapp_util_icecamsr2ioda .......................   Passed    0.15 sec
      Start 1542: test_gdasapp_util_icecmirs2ioda
12/48 Test #1542: test_gdasapp_util_icecmirs2ioda .......................   Passed    0.15 sec
      Start 1543: test_gdasapp_util_icecjpssrr2ioda
13/48 Test #1543: test_gdasapp_util_icecjpssrr2ioda .....................   Passed    0.14 sec
      Start 1881: test_gdasapp_check_python_norms
14/48 Test #1881: test_gdasapp_check_python_norms .......................   Passed    2.90 sec
      Start 1882: test_gdasapp_check_yaml_keys
15/48 Test #1882: test_gdasapp_check_yaml_keys ..........................   Passed    0.17 sec
      Start 1883: test_gdasapp_jedi_increment_to_fv3
16/48 Test #1883: test_gdasapp_jedi_increment_to_fv3 ....................   Passed    0.61 sec
      Start 1884: test_gdasapp_fv3jedi_fv3inc
17/48 Test #1884: test_gdasapp_fv3jedi_fv3inc ...........................   Passed   16.00 sec
      Start 1885: test_gdasapp_soca_nsst_increment_to_mom6
18/48 Test #1885: test_gdasapp_soca_nsst_increment_to_mom6 ..............   Passed    4.33 sec
      Start 1886: test_gdasapp_soca_prep
19/48 Test #1886: test_gdasapp_soca_prep ................................   Passed    4.81 sec
      Start 1887: test_gdasapp_soca_run_clean
20/48 Test #1887: test_gdasapp_soca_run_clean ...........................   Passed    0.21 sec
      Start 1888: test_gdasapp_soca_setup_obsprep
21/48 Test #1888: test_gdasapp_soca_setup_obsprep .......................   Passed   20.58 sec
      Start 1889: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS
22/48 Test #1889: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS ..............   Passed   43.28 sec
      Start 1890: test_gdasapp_soca_JGLOBAL_MARINE_BMAT
23/48 Test #1890: test_gdasapp_soca_JGLOBAL_MARINE_BMAT .................   Passed   74.36 sec
      Start 1891: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
24/48 Test #1891: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP ....   Passed   42.83 sec
      Start 1892: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN
25/48 Test #1892: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN .....   Passed   42.48 sec
      Start 1893: test_gdasapp_soca_copy_scratch
26/48 Test #1893: test_gdasapp_soca_copy_scratch ........................   Passed    0.50 sec
      Start 1894: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
27/48 Test #1894: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT ...   Passed   42.45 sec
      Start 1895: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST
28/48 Test #1895: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST ....   Passed   42.36 sec
      Start 1896: test_gdasapp_snow_create_ens
29/48 Test #1896: test_gdasapp_snow_create_ens ..........................   Passed    1.44 sec
      Start 1897: test_gdasapp_snow_imsproc
30/48 Test #1897: test_gdasapp_snow_imsproc .............................   Passed    3.74 sec
      Start 1898: test_gdasapp_snow_apply_jediincr
31/48 Test #1898: test_gdasapp_snow_apply_jediincr ......................   Passed    5.33 sec
      Start 1899: test_gdasapp_snow_letkfoi_snowda
32/48 Test #1899: test_gdasapp_snow_letkfoi_snowda ......................   Passed    7.75 sec
      Start 1900: test_gdasapp_convert_bufr_adpsfc_snow
33/48 Test #1900: test_gdasapp_convert_bufr_adpsfc_snow .................   Passed    3.57 sec
      Start 1901: test_gdasapp_convert_bufr_adpsfc
34/48 Test #1901: test_gdasapp_convert_bufr_adpsfc ......................   Passed    3.82 sec
      Start 1902: test_gdasapp_convert_gsi_satbias
35/48 Test #1902: test_gdasapp_convert_gsi_satbias ......................   Passed    5.13 sec
      Start 1903: test_gdasapp_setup_atm_cycled_exp
36/48 Test #1903: test_gdasapp_setup_atm_cycled_exp .....................   Passed    1.45 sec
      Start 1904: test_gdasapp_atm_jjob_var_init
37/48 Test #1904: test_gdasapp_atm_jjob_var_init ........................   Passed   47.84 sec
      Start 1905: test_gdasapp_atm_jjob_var_run
38/48 Test #1905: test_gdasapp_atm_jjob_var_run .........................   Passed  106.70 sec
      Start 1906: test_gdasapp_atm_jjob_var_inc
39/48 Test #1906: test_gdasapp_atm_jjob_var_inc .........................   Passed   78.78 sec
      Start 1907: test_gdasapp_atm_jjob_var_final
40/48 Test #1907: test_gdasapp_atm_jjob_var_final .......................   Passed   42.99 sec
      Start 1908: test_gdasapp_atm_jjob_ens_init
41/48 Test #1908: test_gdasapp_atm_jjob_ens_init ........................   Passed   79.47 sec
      Start 1909: test_gdasapp_atm_jjob_ens_letkf
42/48 Test #1909: test_gdasapp_atm_jjob_ens_letkf .......................   Passed  458.54 sec
      Start 1910: test_gdasapp_atm_jjob_ens_init_split
43/48 Test #1910: test_gdasapp_atm_jjob_ens_init_split ..................   Passed   47.80 sec
      Start 1911: test_gdasapp_atm_jjob_ens_obs
44/48 Test #1911: test_gdasapp_atm_jjob_ens_obs .........................   Passed   74.26 sec
      Start 1912: test_gdasapp_atm_jjob_ens_sol
45/48 Test #1912: test_gdasapp_atm_jjob_ens_sol .........................   Passed   42.36 sec
      Start 1913: test_gdasapp_atm_jjob_ens_inc
46/48 Test #1913: test_gdasapp_atm_jjob_ens_inc .........................   Passed  106.26 sec
      Start 1914: test_gdasapp_atm_jjob_ens_final
47/48 Test #1914: test_gdasapp_atm_jjob_ens_final .......................   Passed   42.28 sec
      Start 1915: test_gdasapp_aero_gen_3dvar_yaml
48/48 Test #1915: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    0.81 sec

100% tests passed, 0 tests failed out of 48

Label Time Summary:
gdas-utils    =  10.50 sec*proc (13 tests)
script        =  10.50 sec*proc (13 tests)

Total Test time (real) = 1509.64 sec
```

The changes in this PR are ready for review.

**Comment by RussTreadon-NOAA** [comment]
Question for @ADCollard , @emilyhcliu , @ypwang19 , @azadeh-gh , @xincjin-NOAA , and others working on JEDI radiance assimilation.  

This PR names the radiance bias correction tarball `gdas.t${cyc}z.rad_varbc_params.tar`.  Are we OK with `rad_varbc_params.tar` or do we want a different name?

**Comment by RussTreadon-NOAA** [comment]
The changes in this PR have been tested via GDASApp ctests and g-w CI.  All tests pass.  See g-w PR [#2875](https://github.com/NOAA-EMC/global-workflow/pull/2875) for details.

The changes in the GDASApp PR replace a list of _satellite_sensor_ radiance bias correction files with a tarball.  This PR uses `rad_varbc_params.tar` as the basename for this tarball.   **_Is this name OK with those working on radiance assimilation?_**   

If **yes**, would some of you approve this PR.  This allows the `sorc/gdas.cd` hash in g-w PR [#2875](https://github.com/NOAA-EMC/global-workflow/pull/2875) to be updated and get PR [#2875](https://github.com/NOAA-EMC/global-workflow/pull/2875) one step closer to merger into g-w `develop`

If **no**, what name do you prefer we use?

**Review by xincjin-NOAA — APPROVED** [review]
This name looks good to me.

**Comment by RussTreadon-NOAA** [comment]
Thank you @xincjin-NOAA for your review and approval.

**Review by ADCollard — APPROVED** [review]
This looks fine to me.  Thanks, Russ.

Approve

**Comment by RussTreadon-NOAA** [comment]
Thank you @ADCollard for looking over the change and approving.

**Pull request merged**
