### PR TITLE
generalize layout for reading GSI static-B

### LINKED ISSUE #680: generalize layout for reading GSI static-B
`parm/atm/berror/staticb_gsibec.yaml` is currently hardwired to read gsibec using a layout of {3,2}.   
```
    processor layout x direction: &layout_gsib_x 3
    processor layout y direction: &layout_gsib_y 2
```
This only works when `fv3jedi_var.x` is run with {`layout_x`,`layout_y`) = {`1`,`1`}.   

As more developers run `fv3jedi_var.x`, they will do so with a various {`layout_x`,`layout_y`}.   Some of these runs will use gsibec for the static background error.   As such, there is is need to generalize the {3,2} configuration in `parm/atm/berror/staticb_gsibec.yaml`.

This issue is opened to document this generalization.   

For the generalization to be functional within g-w, changes need to be made to g-w `parm/config/gfs/config.atmanl`.   See g-w issue [#1936](https://github.com/NOAA-EMC/global-workflow/issues/1936) for details regarding the associated g-w changes.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
This PR replaces the hardwired {3,2} layout for reading the GSI static-B with variables {`layout_gsib_x`, `layout_gsib_y`}.   Modifications are made to g-w `config.resources` to set the new variables. 

Fixes #680
Depends on g-w issue [#1936](https://github.com/NOAA-EMC/global-workflow/issues/1936)

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
**Orion ctests**
Install `RussTreadon-NOAA:feature/gsibec` inside a clone of g-w `RussTreadon-NOAA:feature/gsibec` (see g-w PR [#1945](https://github.com/NOAA-EMC/global-workflow/pull/1945)).   Execute `test_gdasapp`.    

```
(gdasapp) Orion-login-3:/work2/noaa/da/rtreadon/git/global-workflow/pr1945/sorc/gdas.cd/build$ ctest -R test_gdasapp
Test project /work2/noaa/da/rtreadon/git/global-workflow/pr1945/sorc/gdas.cd/build
      Start 1292: test_gdasapp_util_coding_norms
 1/57 Test #1292: test_gdasapp_util_coding_norms ........................   Passed    1.56 sec
      Start 1293: test_gdasapp_util_ioda_example
 2/57 Test #1293: test_gdasapp_util_ioda_example ........................   Passed    4.31 sec
      Start 1294: test_gdasapp_util_prepdata
 3/57 Test #1294: test_gdasapp_util_prepdata ............................   Passed    3.49 sec
      Start 1295: test_gdasapp_util_rads2ioda
 4/57 Test #1295: test_gdasapp_util_rads2ioda ...........................   Passed    0.54 sec
      Start 1296: test_gdasapp_util_ghrsst2ioda
 5/57 Test #1296: test_gdasapp_util_ghrsst2ioda .........................   Passed    0.16 sec
      Start 1297: test_gdasapp_util_smap2ioda
 6/57 Test #1297: test_gdasapp_util_smap2ioda ...........................   Passed    0.16 sec
      Start 1298: test_gdasapp_util_smos2ioda
 7/57 Test #1298: test_gdasapp_util_smos2ioda ...........................   Passed    0.18 sec
      Start 1299: test_gdasapp_util_icecamsr2ioda
 8/57 Test #1299: test_gdasapp_util_icecamsr2ioda .......................   Passed    0.15 sec
      Start 1627: test_gdasapp_check_python_norms
 9/57 Test #1627: test_gdasapp_check_python_norms .......................   Passed    1.05 sec
      Start 1628: test_gdasapp_check_yaml_keys
10/57 Test #1628: test_gdasapp_check_yaml_keys ..........................   Passed    0.09 sec
      Start 1629: test_gdasapp_jedi_increment_to_fv3
11/57 Test #1629: test_gdasapp_jedi_increment_to_fv3 ....................   Passed    9.96 sec
      Start 1630: test_gdasapp_convert_ewok_yaml
12/57 Test #1630: test_gdasapp_convert_ewok_yaml ........................   Passed    0.21 sec
      Start 1631: test_gdasapp_setup_cycled_exp
13/57 Test #1631: test_gdasapp_setup_cycled_exp .........................   Passed    0.44 sec
      Start 1632: test_gdasapp_convert_bufr_temp_dbuoy
14/57 Test #1632: test_gdasapp_convert_bufr_temp_dbuoy ..................   Passed    0.60 sec
      Start 1633: test_gdasapp_convert_bufr_salt_dbuoy
15/57 Test #1633: test_gdasapp_convert_bufr_salt_dbuoy ..................   Passed    0.24 sec
      Start 1634: test_gdasapp_convert_bufr_temp_mbuoyb
16/57 Test #1634: test_gdasapp_convert_bufr_temp_mbuoyb .................   Passed    0.32 sec
      Start 1635: test_gdasapp_convert_bufr_salt_mbuoyb
17/57 Test #1635: test_gdasapp_convert_bufr_salt_mbuoyb .................   Passed    0.30 sec
      Start 1636: test_gdasapp_convert_bufr_tesacprof
18/57 Test #1636: test_gdasapp_convert_bufr_tesacprof ...................   Passed    0.27 sec
      Start 1637: test_gdasapp_convert_bufr_trkobprof
19/57 Test #1637: test_gdasapp_convert_bufr_trkobprof ...................   Passed    0.25 sec
      Start 1638: test_gdasapp_convert_bufr_sfcships
20/57 Test #1638: test_gdasapp_convert_bufr_sfcships ....................   Passed    0.31 sec
      Start 1639: test_gdasapp_convert_bufr_sfcshipsu
21/57 Test #1639: test_gdasapp_convert_bufr_sfcshipsu ...................   Passed    0.27 sec
      Start 1640: test_gdasapp_soca_obsdb
22/57 Test #1640: test_gdasapp_soca_obsdb ...............................   Passed   12.82 sec
      Start 1641: test_gdasapp_soca_nsst_increment_to_mom6
23/57 Test #1641: test_gdasapp_soca_nsst_increment_to_mom6 ..............   Passed   45.55 sec
      Start 1642: test_gdasapp_soca_prep
24/57 Test #1642: test_gdasapp_soca_prep ................................   Passed    4.18 sec
      Start 1643: test_gdasapp_soca_concatioda
25/57 Test #1643: test_gdasapp_soca_concatioda ..........................   Passed    1.71 sec
      Start 1644: test_gdasapp_soca_run_clean
26/57 Test #1644: test_gdasapp_soca_run_clean ...........................   Passed    0.03 sec
      Start 1645: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
27/57 Test #1645: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP ....   Passed   42.83 sec
      Start 1646: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT
28/57 Test #1646: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT ....   Passed   74.25 sec
      Start 1647: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN
29/57 Test #1647: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN .....   Passed   42.35 sec
      Start 1648: test_gdasapp_soca_copy_scratch
30/57 Test #1648: test_gdasapp_soca_copy_scratch ........................   Passed    3.87 sec
      Start 1649: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
31/57 Test #1649: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT ...   Passed   74.44 sec
      Start 1650: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST
32/57 Test #1650: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST ....   Passed   42.28 sec
      Start 1651: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY
33/57 Test #1651: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY ....   Passed  362.55 sec
      Start 1652: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS
34/57 Test #1652: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS ..............   Passed   10.29 sec
      Start 1653: test_gdasapp_soca_socahybridweights
35/57 Test #1653: test_gdasapp_soca_socahybridweights ...................   Passed   74.26 sec
      Start 1654: test_gdasapp_soca_incr_handler
36/57 Test #1654: test_gdasapp_soca_incr_handler ........................   Passed   42.48 sec
      Start 1655: test_gdasapp_soca_ens_handler
37/57 Test #1655: test_gdasapp_soca_ens_handler .........................   Passed   42.20 sec
      Start 1656: test_gdasapp_land_create_ens
38/57 Test #1656: test_gdasapp_land_create_ens ..........................   Passed    2.22 sec
      Start 1657: test_gdasapp_land_imsproc
39/57 Test #1657: test_gdasapp_land_imsproc .............................   Passed    4.90 sec
      Start 1658: test_gdasapp_land_apply_jediincr
40/57 Test #1658: test_gdasapp_land_apply_jediincr ......................   Passed    8.97 sec
      Start 1659: test_gdasapp_land_letkfoi_snowda
41/57 Test #1659: test_gdasapp_land_letkfoi_snowda ......................   Passed   18.80 sec
      Start 1660: test_gdasapp_convert_bufr_adpsfc_snow
42/57 Test #1660: test_gdasapp_convert_bufr_adpsfc_snow .................   Passed    5.98 sec
      Start 1661: test_gdasapp_convert_bufr_adpsfc
43/57 Test #1661: test_gdasapp_convert_bufr_adpsfc ......................   Passed    5.64 sec
      Start 1662: test_gdasapp_convert_gsi_satbias
44/57 Test #1662: test_gdasapp_convert_gsi_satbias ......................   Passed    4.53 sec
      Start 1663: test_gdasapp_store_gsi_satbias
45/57 Test #1663: test_gdasapp_store_gsi_satbias ........................   Passed    1.20 sec
      Start 1664: test_gdasapp_setup_atm_cycled_exp
46/57 Test #1664: test_gdasapp_setup_atm_cycled_exp .....................   Passed    0.69 sec
      Start 1665: test_gdasapp_atm_jjob_var_init
47/57 Test #1665: test_gdasapp_atm_jjob_var_init ........................   Passed   77.09 sec
      Start 1666: test_gdasapp_atm_jjob_var_run
48/57 Test #1666: test_gdasapp_atm_jjob_var_run .........................   Passed  106.17 sec
      Start 1667: test_gdasapp_atm_jjob_var_final
49/57 Test #1667: test_gdasapp_atm_jjob_var_final .......................   Passed   42.17 sec
      Start 1668: test_gdasapp_atm_jjob_ens_init
50/57 Test #1668: test_gdasapp_atm_jjob_ens_init ........................   Passed   44.79 sec
      Start 1669: test_gdasapp_atm_jjob_ens_run
51/57 Test #1669: test_gdasapp_atm_jjob_ens_run .........................   Passed  298.50 sec
      Start 1670: test_gdasapp_atm_jjob_ens_final
52/57 Test #1670: test_gdasapp_atm_jjob_ens_final .......................   Passed   42.18 sec
      Start 1671: test_gdasapp_aero_gen_3dvar_yaml
53/57 Test #1671: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    6.18 sec
      Start 1672: test_gdasapp_setup_aero_cycled_exp
54/57 Test #1672: test_gdasapp_setup_aero_cycled_exp ....................   Passed    0.72 sec
      Start 1673: test_gdasapp_aero_jjob_var_init
55/57 Test #1673: test_gdasapp_aero_jjob_var_init .......................   Passed   55.86 sec
      Start 1674: test_gdasapp_aero_jjob_var_run
56/57 Test #1674: test_gdasapp_aero_jjob_var_run ........................***Failed   42.37 sec
      Start 1675: test_gdasapp_aero_jjob_var_final
57/57 Test #1675: test_gdasapp_aero_jjob_var_final ......................***Failed   42.23 sec

96% tests passed, 2 tests failed out of 57

Label Time Summary:
gdas-utils    =  10.56 sec*proc (8 tests)
script        =  10.56 sec*proc (8 tests)

Total Test time (real) = 1712.89 sec

The following tests FAILED:
        1674 - test_gdasapp_aero_jjob_var_run (Failed)
        1675 - test_gdasapp_aero_jjob_var_final (Failed)
```

Test `aero_jjob_var_final` failed because expected output from test `aero_jjob_var_run` was not created.  Test `aero_jjob_var_run` failed with
```
1:  CRTM_Atmosphere_IsValid(INFORMATION) : Negative level pressure found
1:  CRTM_Atmosphere_IsValid(INFORMATION) : Negative layer pressure found
1:  CRTM_Atmosphere_IsValid(INFORMATION) : Negative layer temperature found
1:  CRTM_Atmosphere_IsValid(INFORMATION) : Negative layer absorber found
1:  CRTM_AOD(FAILURE) : Input data check failed for profile #5
1:  ufo_aodcrtm_mod.F90(FAILURE) : Error calling CRTM Forward Model for v.viirs-m_npp
```
Rerun jobs `setup_aero_cycled_exp`, `aero_jjob_var_init`, and `aero_jjob_var_run`.   Job `aero_jjob_var_run` failed again in the same manner.

This PR does not alter files used by the `aero_jjob_var` tests.   Not clear why `aero_jjob_var` fails on Orion.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA this is an issue that will be fixed in an OOPS PR, we can revert the switch to linear time interpolation in GDASApp, or wait until OOPS's PR is merged. But this is a known issue right now regardless of platform.

**Comment by RussTreadon-NOAA** [comment]
Thank you @CoryMartin-NOAA for explaining why the `aero_jjob_var` test fails.   Since we know why the test fails and a fix is forthcoming via an OOPS PR, I'm OK with leaving `aero_jjob_var` test unaltered.  I'm also OK with you or @andytangborn doing whatever you feel is best a present.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I think we give it a couple of days and if it is still not merged, then we can come up with an interim solution.

**Comment by RussTreadon-NOAA** [comment]
**Hera ctests**
Install `RussTreadon-NOAA:feature/gsibec` inside a clone of g-w `RussTreadon-NOAA:feature/gsibec` (see g-w PR https://github.com/NOAA-EMC/global-workflow/pull/1945). Execute `test_gdasapp` ctests.

```
(gdasapp) Hera(hfe10):/scratch1/NCEPDEV/stmp2/Russ.Treadon/git/global-workflow/pr1945/sorc/gdas.cd/build$ ctest -R test_gdasapp
Test project /scratch1/NCEPDEV/stmp2/Russ.Treadon/git/global-workflow/pr1945/sorc/gdas.cd/build
      Start 1293: test_gdasapp_util_coding_norms
 1/57 Test #1293: test_gdasapp_util_coding_norms ........................   Passed    1.44 sec
      Start 1294: test_gdasapp_util_ioda_example
 2/57 Test #1294: test_gdasapp_util_ioda_example ........................   Passed    4.39 sec
      Start 1295: test_gdasapp_util_prepdata
 3/57 Test #1295: test_gdasapp_util_prepdata ............................   Passed    0.68 sec
      Start 1296: test_gdasapp_util_rads2ioda
 4/57 Test #1296: test_gdasapp_util_rads2ioda ...........................   Passed    0.44 sec
      Start 1297: test_gdasapp_util_ghrsst2ioda
 5/57 Test #1297: test_gdasapp_util_ghrsst2ioda .........................   Passed    0.18 sec
      Start 1298: test_gdasapp_util_smap2ioda
 6/57 Test #1298: test_gdasapp_util_smap2ioda ...........................   Passed    0.19 sec
      Start 1299: test_gdasapp_util_smos2ioda
 7/57 Test #1299: test_gdasapp_util_smos2ioda ...........................   Passed    0.31 sec
      Start 1300: test_gdasapp_util_icecamsr2ioda
 8/57 Test #1300: test_gdasapp_util_icecamsr2ioda .......................   Passed    0.16 sec
      Start 1628: test_gdasapp_check_python_norms
 9/57 Test #1628: test_gdasapp_check_python_norms .......................   Passed    0.79 sec
      Start 1629: test_gdasapp_check_yaml_keys
10/57 Test #1629: test_gdasapp_check_yaml_keys ..........................   Passed    0.16 sec
      Start 1630: test_gdasapp_jedi_increment_to_fv3
11/57 Test #1630: test_gdasapp_jedi_increment_to_fv3 ....................   Passed    0.92 sec
      Start 1631: test_gdasapp_convert_ewok_yaml
12/57 Test #1631: test_gdasapp_convert_ewok_yaml ........................   Passed    0.23 sec
      Start 1632: test_gdasapp_setup_cycled_exp
13/57 Test #1632: test_gdasapp_setup_cycled_exp .........................   Passed    0.51 sec
      Start 1633: test_gdasapp_convert_bufr_temp_dbuoy
14/57 Test #1633: test_gdasapp_convert_bufr_temp_dbuoy ..................   Passed    3.10 sec
      Start 1634: test_gdasapp_convert_bufr_salt_dbuoy
15/57 Test #1634: test_gdasapp_convert_bufr_salt_dbuoy ..................   Passed    0.38 sec
      Start 1635: test_gdasapp_convert_bufr_temp_mbuoyb
16/57 Test #1635: test_gdasapp_convert_bufr_temp_mbuoyb .................   Passed    0.26 sec
      Start 1636: test_gdasapp_convert_bufr_salt_mbuoyb
17/57 Test #1636: test_gdasapp_convert_bufr_salt_mbuoyb .................   Passed    0.24 sec
      Start 1637: test_gdasapp_convert_bufr_tesacprof
18/57 Test #1637: test_gdasapp_convert_bufr_tesacprof ...................   Passed    0.27 sec
      Start 1638: test_gdasapp_convert_bufr_trkobprof
19/57 Test #1638: test_gdasapp_convert_bufr_trkobprof ...................   Passed    0.23 sec
      Start 1639: test_gdasapp_convert_bufr_sfcships
20/57 Test #1639: test_gdasapp_convert_bufr_sfcships ....................   Passed    0.37 sec
      Start 1640: test_gdasapp_convert_bufr_sfcshipsu
21/57 Test #1640: test_gdasapp_convert_bufr_sfcshipsu ...................   Passed    0.23 sec
      Start 1641: test_gdasapp_soca_obsdb
22/57 Test #1641: test_gdasapp_soca_obsdb ...............................   Passed    2.17 sec
      Start 1642: test_gdasapp_soca_nsst_increment_to_mom6
23/57 Test #1642: test_gdasapp_soca_nsst_increment_to_mom6 ..............   Passed   10.92 sec
      Start 1643: test_gdasapp_soca_prep
24/57 Test #1643: test_gdasapp_soca_prep ................................   Passed    3.52 sec
      Start 1644: test_gdasapp_soca_concatioda
25/57 Test #1644: test_gdasapp_soca_concatioda ..........................   Passed    4.60 sec
      Start 1645: test_gdasapp_soca_run_clean
26/57 Test #1645: test_gdasapp_soca_run_clean ...........................   Passed    0.11 sec
      Start 1646: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
27/57 Test #1646: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP ....   Passed   42.87 sec
      Start 1647: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT
28/57 Test #1647: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT ....   Passed   43.03 sec
      Start 1648: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN
29/57 Test #1648: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN .....   Passed   42.45 sec
      Start 1649: test_gdasapp_soca_copy_scratch
30/57 Test #1649: test_gdasapp_soca_copy_scratch ........................   Passed    0.63 sec
      Start 1650: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
31/57 Test #1650: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT ...   Passed   42.32 sec
      Start 1651: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST
32/57 Test #1651: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_POST ....   Passed   10.35 sec
      Start 1652: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY
33/57 Test #1652: test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY ....   Passed  298.34 sec
      Start 1653: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS
34/57 Test #1653: test_gdasapp_soca_JGLOBAL_PREP_OCEAN_OBS ..............   Passed   42.41 sec
      Start 1654: test_gdasapp_soca_socahybridweights
35/57 Test #1654: test_gdasapp_soca_socahybridweights ...................   Passed   42.28 sec
      Start 1655: test_gdasapp_soca_incr_handler
36/57 Test #1655: test_gdasapp_soca_incr_handler ........................   Passed   10.26 sec
      Start 1656: test_gdasapp_soca_ens_handler
37/57 Test #1656: test_gdasapp_soca_ens_handler .........................   Passed   10.24 sec
      Start 1657: test_gdasapp_land_create_ens
38/57 Test #1657: test_gdasapp_land_create_ens ..........................   Passed    8.65 sec
      Start 1658: test_gdasapp_land_imsproc
39/57 Test #1658: test_gdasapp_land_imsproc .............................   Passed    5.74 sec
      Start 1659: test_gdasapp_land_apply_jediincr
40/57 Test #1659: test_gdasapp_land_apply_jediincr ......................   Passed    3.22 sec
      Start 1660: test_gdasapp_land_letkfoi_snowda
41/57 Test #1660: test_gdasapp_land_letkfoi_snowda ......................   Passed   12.08 sec
      Start 1661: test_gdasapp_convert_bufr_adpsfc_snow
42/57 Test #1661: test_gdasapp_convert_bufr_adpsfc_snow .................   Passed    4.69 sec
      Start 1662: test_gdasapp_convert_bufr_adpsfc
43/57 Test #1662: test_gdasapp_convert_bufr_adpsfc ......................   Passed    5.90 sec
      Start 1663: test_gdasapp_convert_gsi_satbias
44/57 Test #1663: test_gdasapp_convert_gsi_satbias ......................   Passed    4.36 sec
      Start 1664: test_gdasapp_store_gsi_satbias
45/57 Test #1664: test_gdasapp_store_gsi_satbias ........................   Passed    1.77 sec
      Start 1665: test_gdasapp_setup_atm_cycled_exp
46/57 Test #1665: test_gdasapp_setup_atm_cycled_exp .....................   Passed    0.93 sec
      Start 1666: test_gdasapp_atm_jjob_var_init
47/57 Test #1666: test_gdasapp_atm_jjob_var_init ........................   Passed   44.37 sec
      Start 1667: test_gdasapp_atm_jjob_var_run
48/57 Test #1667: test_gdasapp_atm_jjob_var_run .........................   Passed  106.10 sec
      Start 1668: test_gdasapp_atm_jjob_var_final
49/57 Test #1668: test_gdasapp_atm_jjob_var_final .......................   Passed   42.12 sec
      Start 1669: test_gdasapp_atm_jjob_ens_init
50/57 Test #1669: test_gdasapp_atm_jjob_ens_init ........................   Passed   44.06 sec
      Start 1670: test_gdasapp_atm_jjob_ens_run
51/57 Test #1670: test_gdasapp_atm_jjob_ens_run .........................   Passed  266.13 sec
      Start 1671: test_gdasapp_atm_jjob_ens_final
52/57 Test #1671: test_gdasapp_atm_jjob_ens_final .......................   Passed   42.19 sec
      Start 1672: test_gdasapp_aero_gen_3dvar_yaml
53/57 Test #1672: test_gdasapp_aero_gen_3dvar_yaml ......................   Passed    0.51 sec
      Start 1673: test_gdasapp_setup_aero_cycled_exp
54/57 Test #1673: test_gdasapp_setup_aero_cycled_exp ....................   Passed    0.70 sec
      Start 1674: test_gdasapp_aero_jjob_var_init
55/57 Test #1674: test_gdasapp_aero_jjob_var_init .......................   Passed   52.45 sec
      Start 1675: test_gdasapp_aero_jjob_var_run
56/57 Test #1675: test_gdasapp_aero_jjob_var_run ........................***Failed   74.11 sec
      Start 1676: test_gdasapp_aero_jjob_var_final
57/57 Test #1676: test_gdasapp_aero_jjob_var_final ......................***Failed   10.12 sec

96% tests passed, 2 tests failed out of 57

Label Time Summary:
gdas-utils    =   7.79 sec*proc (8 tests)
script        =   7.79 sec*proc (8 tests)

Total Test time (real) = 1353.75 sec

The following tests FAILED:
        1675 - test_gdasapp_aero_jjob_var_run (Failed)
        1676 - test_gdasapp_aero_jjob_var_final (Failed)
```

These results mirror those obtained on Orion.  The `aero_jjob_var_run` failure is expected at present.  The `aero_jjob_var_final` failure is due to the fact that the `aero_jjob_var_run` job did not generate expected output.

**Comment by RussTreadon-NOAA** [comment]
The associated g-w PR [#1945](https://github.com/NOAA-EMC/global-workflow/pull/1945) has been merged into g-w `develop`.   Once this GDASApp PR is reviewed, approved, and merged into GDASApp `develop`, the changes can get into `feature/stable-nightly`.   After this I will open a new g-w issue and PR to update the GDASApp hash in g-w `Externals.cfg` and `checkout.sh`.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , would you like to review this PR again or can we go ahead and merge?   

No new changes have been committed to `RussTreadon-NOAA:feature/gsibec` since your initial approval apart from synch'ing my fork with the authoritative `develop`.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @CoryMartin-NOAA.

**Pull request merged**
