### PR TITLE
Enable run_jedi_exe.py to run 3dvar

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
`ush/run_jedi_exe.py` no longer successfully executes `fv3jedi_var.x` using the 3dvar yamls in `ush/examples/run_jedi_exe`.    This functionality is restored in branch `feature/runjedi`.  This PR is opened to get the required changes into `develop`

### CODE REVIEW

**Review by guillaumevernieres — DISMISSED** [review]
:+1: 
I haven't tested the application, but I assume it's all good!

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA and @guillaumevernieres , I don't think one of the changes in this PR is the best way to do things.

I cut-n-pasted functions `genYAML` and `get_runtime_config` from `genYAML`  into `run_jedi_exe.py`   I execute `genYAML` from `run_jedi_exe.py` to create the yaml file used by `fv3jedi_var.x`.    

I modified the `genYAML` which I added to `run_jedi_exe.py`.    It now has two arguments:  `yamlconfig` and `output_file`.   `output_file` is the yaml which `fv3jedi_var.x` reads.  I need to experiment to see if this addition is really necessary.

Is there a way to reference the external `genYAML` from `run_jedi_exe.py`?   This is a cleaner solution.   Replicating 99% of the functions from one file in another file isn't good software design.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA the easiest thing to do is probably move those two functions into a file in  `ush/ufsda`, then both the `ush/genYAML` and `run_jedi_exe.py` scripts can do something like `from ufsda.newfile import genYAML, get_runtime_config`

**Comment by RussTreadon-NOAA** [comment]
Thank you @CoryMartin-NOAA .  Let me try this.

**Comment by RussTreadon-NOAA** [comment]
Automated execution of `test_gdasapp_genYAML_run ` fails.  Traceback reads ([click here](https://github.com/NOAA-EMC/GDASApp/actions/runs/3954122646/jobs/6771127436) for all output)
```
6/8 Test #6: test_gdasapp_genYAML_run .............***Failed    1.77 sec
Traceback (most recent call last):
  File "/home/runner/work/GDASApp/GDASApp/GDASApp/ush/genYAML", line 12, in <module>
    from ufsda.genYAML import genYAML
  File "/home/runner/work/GDASApp/GDASApp/GDASApp/ush/ufsda/__init__.py", line 3, in <module>
    import ufsda.stage
  File "/home/runner/work/GDASApp/GDASApp/GDASApp/ush/ufsda/stage.py", line 32, in <module>
    import ioda_conv_engines as iconv
ModuleNotFoundError: No module named 'ioda_conv_engines'
```

Executing ctests from Orion command line results in 100% pass.   In particular, `test_gdasapp_genYAML_run` passes.
```
(gdasapp) Orion-login-3:/work2/noaa/da/rtreadon/git/GDASApp/iss223/build$ ctest -R test_gdasapp
Test project /work2/noaa/da/rtreadon/git/GDASApp/iss223/build
      Start 1295: test_gdasapp_check_python_norms
 1/28 Test #1295: test_gdasapp_check_python_norms .........   Passed    2.26 sec
      Start 1296: test_gdasapp_check_yaml_keys
 2/28 Test #1296: test_gdasapp_check_yaml_keys ............   Passed    1.25 sec
      Start 1297: test_gdasapp_check_valid_yaml
 3/28 Test #1297: test_gdasapp_check_valid_yaml ...........   Passed    2.40 sec
      Start 1298: test_gdasapp_jedi_increment_to_fv3
 4/28 Test #1298: test_gdasapp_jedi_increment_to_fv3 ......   Passed   15.34 sec
      Start 1299: test_gdasapp_genYAML_prep
 5/28 Test #1299: test_gdasapp_genYAML_prep ...............   Passed    0.03 sec
      Start 1300: test_gdasapp_genYAML_run
 6/28 Test #1300: test_gdasapp_genYAML_run ................   Passed   38.65 sec
      Start 1301: test_gdasapp_convert_ewok_yaml
 7/28 Test #1301: test_gdasapp_convert_ewok_yaml ..........   Passed    0.21 sec
      Start 1302: test_gdasapp_convert_bufr_temp_dbuoy
 8/28 Test #1302: test_gdasapp_convert_bufr_temp_dbuoy ....   Passed    3.61 sec
      Start 1303: test_gdasapp_convert_bufr_salt_dbuoy
 9/28 Test #1303: test_gdasapp_convert_bufr_salt_dbuoy ....   Passed    0.23 sec
      Start 1304: test_gdasapp_convert_bufr_temp_mbuoyb
10/28 Test #1304: test_gdasapp_convert_bufr_temp_mbuoyb ...   Passed    0.24 sec
      Start 1305: test_gdasapp_convert_bufr_salt_mbuoyb
11/28 Test #1305: test_gdasapp_convert_bufr_salt_mbuoyb ...   Passed    0.23 sec
      Start 1306: test_gdasapp_convert_bufr_tesacprof
12/28 Test #1306: test_gdasapp_convert_bufr_tesacprof .....   Passed    0.25 sec
      Start 1307: test_gdasapp_convert_bufr_trkobprof
13/28 Test #1307: test_gdasapp_convert_bufr_trkobprof .....   Passed    0.23 sec
      Start 1308: test_gdasapp_convert_bufr_sfcships
14/28 Test #1308: test_gdasapp_convert_bufr_sfcships ......   Passed    0.25 sec
      Start 1309: test_gdasapp_convert_bufr_sfcshipsu
15/28 Test #1309: test_gdasapp_convert_bufr_sfcshipsu .....   Passed    0.24 sec
      Start 1310: test_gdasapp_soca_obsdb
16/28 Test #1310: test_gdasapp_soca_obsdb .................   Passed    1.41 sec
      Start 1311: test_gdasapp_soca_ana_prep
17/28 Test #1311: test_gdasapp_soca_ana_prep ..............   Passed    3.72 sec
      Start 1312: test_gdasapp_soca_ana_bmat
18/28 Test #1312: test_gdasapp_soca_ana_bmat ..............   Passed  124.62 sec
      Start 1313: test_gdasapp_soca_ana_run
19/28 Test #1313: test_gdasapp_soca_ana_run ...............   Passed   58.21 sec
      Start 1314: test_gdasapp_soca_ana_bmat_vrfy
20/28 Test #1314: test_gdasapp_soca_ana_bmat_vrfy .........   Passed   47.95 sec
      Start 1315: test_gdasapp_land_create_ens
21/28 Test #1315: test_gdasapp_land_create_ens ............   Passed    1.16 sec
      Start 1316: test_gdasapp_land_imsproc
22/28 Test #1316: test_gdasapp_land_imsproc ...............   Passed    9.87 sec
      Start 1317: test_gdasapp_land_apply_jediincr
23/28 Test #1317: test_gdasapp_land_apply_jediincr ........   Passed    4.29 sec
      Start 1318: test_gdasapp_land_letkfoi_snowda
24/28 Test #1318: test_gdasapp_land_letkfoi_snowda ........   Passed    9.05 sec
      Start 1319: test_gdasapp_convert_bufr_adpsfc
25/28 Test #1319: test_gdasapp_convert_bufr_adpsfc ........   Passed    9.05 sec
      Start 1320: test_gdasapp_convert_gsi_satbias
26/28 Test #1320: test_gdasapp_convert_gsi_satbias ........   Passed    4.34 sec
      Start 1321: test_gdasapp_store_gsi_satbias
27/28 Test #1321: test_gdasapp_store_gsi_satbias ..........   Passed    6.35 sec
      Start 1322: test_gdasapp_aero_gen_3dvar_yaml
28/28 Test #1322: test_gdasapp_aero_gen_3dvar_yaml ........   Passed    0.20 sec

100% tests passed, 0 tests failed out of 28

Total Test time (real) = 346.02 sec
```
Not sure what's going on.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA and @guillaumevernieres , is there a way to manually run the `Unit Tests / Run Unit Tests with ctest (push)`?   I would like to debug and fix what's wrong without cluttering branch `feature/runjedi` with _debug_ commits.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA this failure is because there is a dependence on IODA in that routine that @guillaumevernieres put in...   Not immediately sure what the best solution here is though. And manually running it on Github actions? You can re-run on the same commit manually from the actions page.

**Comment by RussTreadon-NOAA** [comment]
Thanks @CoryMartin-NOAA .    

If I revert `ush/genYAML` back to what we currently have in `develop`, all automated test pass.   This is now the current head of `feature/runjedi` (c78f588).  

The problem with this is duplication of 99% of `ush/genYAML` in `ush/ufsda/genYAML.py`.   It would be nice to remove the duplication by having `ush/genYAML` reference `ush/ufsda/genYAML.py`.   This was attempted in previous commits to `feature/runjedi`.   These attempts results in the automated `test_gdasapp_genYAML_run` failing even though it passes when executed from the Orion command line.   

I'm not sure where to go from here.

**Comment by CoryMartin-NOAA** [comment]
The easiest (not best?) solution is to not run that test unless the full JEDI build of GDASApp exists. I don't like this solution but it would be one that would cause things to pass. The better solution is to remove the dependency of IODA in `import ufsda`, perhaps there is a way we can make it only import the specific function we need? How were you importing them in the previous commit?

**Comment by RussTreadon-NOAA** [comment]
That's the strange thing.  I do not see how anything I am doing touches IODA.  Commit [d306591](https://github.com/NOAA-EMC/GDASApp/pull/278/commits/d306591e833fb53162edaac0501a78b3280a61ca) reduced  `ush/genYAML` to 

```
#!/usr/bin/env python3
# genYAML
# generate YAML using ufsda python module,
# current runtime env, and optional input YAML
import argparse
import datetime as dt
import logging
import os
import re
import yaml

from ufsda.genYAML import genYAML

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--config', type=str, help='Input YAML Configuration', required=True)
    args = parser.parse_args()
    genYAML(args.config)
```

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA does the `ufsda.genYAML` have something like `import ufsda` in it? or `ufsda.stage`? I think stage is the culprit here.

**Comment by CoryMartin-NOAA** [comment]
Ah, it's the `__init__.py` file... not sure how to fix it at the moment but for some reason it is importing everything whenever it is in use. Perhaps we can remove `import ufsda.stage` from that file and with some other minor corrections to other functions resolve this?

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , removing stage from `__init__.py` worked ... at least in the automated tests.

**Comment by RussTreadon-NOAA** [comment]
`run_jedi_exe.py` failed on Hera with 
```
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=41388793.0. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: h34m39: task 4: Out Of Memory
srun: launch/slurm: _step_signal: Terminating StepId=41388793.0
```
December 8, 2022 email from Hera admins alerted users to the need to include `--mem=0` on `srun` commands.    Instead of doing this, replace `#SBATCH --exclusive` in `ush/ufsda/misc_utils.py` with `#SBATCH --mem=0`.   

With this change `run_jedi_exe.py` successfully ran 3dvar case on Hera.

**Comment by RussTreadon-NOAA** [comment]
Removal of `ufsda.stage` from `__init__.py` in `feature/runjedi` requires adding `from ufsda.stage import ...` lines to the following scripts:
- GDASApp `scripts/exgdas_global_marine_analysis_prep.py`
- g-w `scripts/exgdas_global_atmos_analysis_prep.py`

**Comment by guillaumevernieres** [comment]
FYI @RussTreadon-NOAA , I'm going to deprecate the section I added to `run_jedi_exe.py` that allowed us to run the soca script, so don't worry about soca within that application. I should have removed that section when I added that script `https://github.com/NOAA-EMC/GDASApp/blob/develop/ush/soca/run_jjobs.py`

**Comment by RussTreadon-NOAA** [comment]
Automated tests hera-GW-RT and orion-GW-RT fail because g-w `scripts/exgdas_global_atmos_analysis_prep.py` does not import the specific ufsda.stage functions used by the script.   g-w PR [#1265](https://github.com/NOAA-EMC/global-workflow/pull/1265) has been opened to get the required one line addition into `exgdas_global_atmos_analysis_prep.py`.

The following exercise was completed on Orion to demonstrate that the modified `exgdas_global_atmos_analysis_prep.py` allows the failed GDASApp tests to pass.
1. clone [RussTreadon-NOAA/global-workflow/feature/ufsda_stage](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/ufsda_stage)
2. `cd sorc`
3. change `checkout.sh` to clone the head of GDASApp branch `feature/runjedi`
4. execute `checkout.sh -u`
5. `export WORKFLOW_BUILD=ON` 
6. execute `build_all.sh`
7. execute `link_workflow.sh`
8. `cd gdas.cd`
9. `module use $path_to_clone/gdas.cd/modulefiles`
10. `module load GDAS/orion`
11. `ulimit -s unlimited`
12. `export OMP_NUM_THREADS=1`
13. `export SLURM_ACCOUNT=da-cpu`
14. `export SALLOC_ACCOUNT=$SLURM_ACCOUNT`
15. `export SBATCH_ACCOUNT=$SLURM_ACCOUNT`
16. `export SLURM_QOS=debug`
17. `cd build`
18. execute `ctest -N test_gdasapp`

All 39 `test_gdasapp` ctests passed on Orion.   Specifically here is confirmation that the atm var and ens ctests pass

```
      Start 1332: test_gdasapp_atm_jjob_var_prep
33/39 Test #1332: test_gdasapp_atm_jjob_var_prep ..........   Passed    6.65 sec
      Start 1333: test_gdasapp_atm_jjob_var_run
34/39 Test #1333: test_gdasapp_atm_jjob_var_run ...........   Passed   96.01 sec
      Start 1334: test_gdasapp_atm_jjob_var_post
35/39 Test #1334: test_gdasapp_atm_jjob_var_post ..........   Passed    5.27 sec
      Start 1335: test_gdasapp_atm_jjob_ens_prep
36/39 Test #1335: test_gdasapp_atm_jjob_ens_prep ..........   Passed    6.20 sec
      Start 1336: test_gdasapp_atm_jjob_ens_run
37/39 Test #1336: test_gdasapp_atm_jjob_ens_run ...........   Passed  1162.34 sec
      Start 1337: test_gdasapp_atm_jjob_ens_post
38/39 Test #1337: test_gdasapp_atm_jjob_ens_post ..........   Passed    9.31 sec

```

**Comment by RussTreadon-NOAA** [comment]
Manual confirmation that `test_gdasapp_atm` ctests pass is a valid test but it does not confirm that the automated tests pass.   

To test automated jobs modify `.github/workflows/unittest*` in `feature/runjedi` to point at g-w branch containing changes in g-w PR [#1265](https://github.com/NOAA-EMC/global-workflow/pull/1265), namely [RussTreadon-NOAA/global-workflow/feature/ufsda](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/ufsda_stage).  This change was committed at 3c828e2.   After this, restart automated GW-RT tests.

**Comment by RussTreadon-NOAA** [comment]
[3c828e2](https://github.com/NOAA-EMC/GDASApp/pull/278/commits/3c828e2695b4e5eaa00dc77a8b56999c14c83089) did not have the desired effect.   The automated GW-RT tests still fail.  

A check of the indicated log files show that the Orion run used g-w branch `dev/gdasapp` while the Hera run used g-w branch `develop`.   Neither use the forked `feature/ufsda_stage`.   This is puzzling since `unittests_g-w.yaml` and `unittests.yaml` point at the forked branch for the global-workflow.

Eventually 3c828e2 needs to be reverted.   I'll leave it for now until I get guidance from @CoryMartin-NOAA or @guillaumevernieres on how to execute hera-GW-RT and orion-GW-RT using my forked g-w branch `feature/ufsda_stage`.

Manually installing GDASApp branch `feature/runjedi` inside g-w `feature/ufsda_stage` and then executing GDASApp ctests from the command line works.   I'd like to see the same behavior in the automated hera-GW-RT and orion-GW-RT tests.   Is this possible?

**Comment by guillaumevernieres** [comment]
@RussTreadon-NOAA , we updated the `global-workflow` `dev/gdasapp` branch last night. It should be identical to develop now.

**Comment by CoryMartin-NOAA** [comment]
I might have to manually update that branch on the local machine? I don't remember. I didn't want everything 100% automated for the CI because of security concerns.

**Comment by RussTreadon-NOAA** [comment]
> I might have to manually update that branch on the local machine? I don't remember. I didn't want everything 100% automated for the CI because of security concerns.

OK.  The fact that manually executing `ctest -R test_gdasapp` yields 100% pass may need to be sufficient for the time being.   I'll revert [3c828e2](https://github.com/NOAA-EMC/GDASApp/pull/278/commits/3c828e2695b4e5eaa00dc77a8b56999c14c83089).

**Comment by guillaumevernieres** [comment]
> > I might have to manually update that branch on the local machine? I don't remember. I didn't want everything 100% automated for the CI because of security concerns.
> 
> OK. The fact that manually executing `ctest -R test_gdasapp` yields 100% pass may need to be sufficient for the time being. I'll revert [3c828e2](https://github.com/NOAA-EMC/GDASApp/pull/278/commits/3c828e2695b4e5eaa00dc77a8b56999c14c83089).

Sounds good to me @RussTreadon-NOAA . I did all my testing on `orion` and that's the automated `ci` that's failing :p ...
What was the reason for pointing to dev/gdasapp on orion and develop on hera?

**Comment by CoryMartin-NOAA** [comment]
Looks like the automated testing *should* checkout the `dev/gdasapp` branch each time it runs... perhaps I need to delete the PR directory and have it re-run from scratch now that the branch is updated?

**Comment by CoryMartin-NOAA** [comment]
I can confirm that Hera's run is `develop` and Orion's is `dev/gdasapp`. Which do we want @guillaumevernieres @RussTreadon-NOAA ? Develop seems like the safer option but I know we wanted the dev branch to exercise more control. Whichever we decide I will modify to be consistent across both platforms. I think we only changed it on Orion and never on Hera due to it not being fully tested. https://github.com/NOAA-EMC/GDASApp/blob/55c2deebf22a5b9b6fa9673a8cdf6c2ca29542ce/ci/gw_driver.sh#L76 the develop branch of GDASApp has `develop` and not `dev/gdasapp` in the CI script.

**Comment by RussTreadon-NOAA** [comment]
Working from g-w `dev/gdasapp` has the benefit of greater control but requires us to monitor g-w `develop` and decide when / how to merge updates from `develop` into `dev/gdasapp`.   On the flip side we also need to periodically merge updates from `dev/gdasapp` into `develop`.   

I opt for working from g-w `develop`.   Having said that, I understand that at this point of rapid development GFS v17 marine DA may need the flexibility `dev/gdasapp` permits.

**Comment by guillaumevernieres** [comment]
We should point to develop on both. What we need really is to be able to point to a fork/branch of the gw within the ci since quite a few of our branches depend on a gw branch. But a problem for an other day.

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres I'm hesitant to do that automatically because I fear that could be a security risk. But we can discuss that later. I'll change Orion to be develop, we can re-run the CI (if you want) and then this will be ready to review/merge.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I didn't clearly read the comments above earlier... do I need to checkout that specific branch of global workflow to run the CI or are we going to assume that it worked as you tested it manually? I'm happy to do it I just wanted to check that this is the correct thing to do.

**Comment by RussTreadon-NOAA** [comment]
> @RussTreadon-NOAA I didn't clearly read the comments above earlier... do I need to checkout that specific branch of global workflow to run the CI or are we going to assume that it worked as you tested it manually? I'm happy to do it I just wanted to check that this is the correct thing to do.

We need to use the updated `scripts/exgdas_global_atmos_analysis_prep.py` from my forked g-w branch [feature/ufsda_stage](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/ufsda_stage) to get GDASApp `test_gdasapp_atm_jjob_var_prep` and `test_gdasapp_atm_jjob_ens_prep` to pass.   Once the prep steps pass the corresponding run steps will also pass.  

Once this PR, #278, is approved & merged into GDASApp `develop`, I'll update the GDASApp hash in g-w `Externals.cfg` and `sorc/checkout.sh` in g-w PR [#1265](https://github.com/NOAA-EMC/global-workflow/pull/1265).   Once g-w PR [#1265](https://github.com/NOAA-EMC/global-workflow/pull/1265) is merged into g-w develop, the GDASApp GW-RT tests should work.   This is messy.

**Comment by CoryMartin-NOAA** [comment]
Yeah I see it is a bit of a chicken and egg problem. The danger of having it use your forked branch is that I have to remember to change it back to develop :-). Do we think I should do that or run it manually and trust it will work?

**Comment by RussTreadon-NOAA** [comment]
> Yeah I see it is a bit of a chicken and egg problem. The danger of having it use your forked branch is that I have to remember to change it back to develop :-). Do we think I should do that or run it manually and trust it will work?

I really like to cross all the _t's_ and dot all the _i's_, but doing so is probably overkill in this case.  You, @CoryMartin-NOAA , have more important things to do than keep changing the g-w branch used by GW-RT.

**Comment by CoryMartin-NOAA** [comment]
I agree, while it's important to be thorough, we are still in active development, and the danger of this breaking something seems low. We can always revert if that is not the case.

**Comment by RussTreadon-NOAA** [comment]
As an aside, do we know if `3dhofx` and `4dhofx` works with `run_jedi_exe.py`?   A quick test using `feature/runjedi` says _**no**_. 

Do we want to maintain the 3dhofx and 4dhofx capability with `run_jedi_exe.py` moving forward?  If **_yes_**, this can be the scope of a new issue.

**Comment by CoryMartin-NOAA** [comment]
We will need this capability for JEDI evaluation when we are ready to use FV3 cube sphere backgrounds and not GSI provided interpolated values. However, I don't know if we will want it as part of run_jedi_exe or part of the j-job approach. I'm inclined to say the former, but depending on how the EnKF is structured, perhaps we will need to run H(x) as stand alone in the workflow?

**Comment by RussTreadon-NOAA** [comment]
At present `JGDAS_GLOBAL_ATMOS_ENSANAL_RUN` runs the observer and solver in a single execution of `fv3jedi_letkf.x`.   This was the easiest way to implement `fv3jedi_letkf.x` for prototype cycling.  This approach is very slow.   The next iteration should refactor g-w to mimic the operational GFS where we have eobs (observer) and eupd (solver).    

Given this we should ensure `run_jedi_exe.py` can run `fv3jedi_hofx.x`, `fv3jedi_letkf.x`, and `fv3jedi_var.x` in standalone mode.   Sometimes we want to work with executables and yamls without the g-w infrastructure.

**Comment by RussTreadon-NOAA** [comment]
Complete the following:
- sync GDASApp `feature/runjedi` and g-w `feature/ufsda_stage` with head of their respective `develop`
- rebuild and install g-w with GDASApp workflow tests enabled 
- manually execute `ctest -R test_gdasapp`.   All tests pass on Hera
```
100% tests passed, 0 tests failed out of 40

Total Test time (real) = 683.75 sec
(gdasapp) Hera(hfe09):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/pr1265/sorc/gdas.cd/build$
```
and Orion
```
100% tests passed, 0 tests failed out of 40

Total Test time (real) = 925.02 sec
(gdasapp) Orion-login-3:/work2/noaa/da/rtreadon/git/global-workflow/pr1265/sorc/gdas.cd/build$
```


- execute `ush/run_jedi_exe.py` for 3dvar.  `fv3jedi_var.x` successfully runs to completion with the caveat that the number of observations types in `parm/atm/obs/lists/gdas_prototype.yaml` is reduced to allow the job to complete within the 30 minute debug queue wall clock limit.
Hera
```
OOPS_STATS ---------------------------------- Parallel Timing Statistics (   6 MPI tasks) -----------------------------------

OOPS_STATS Run end                                  - Runtime:    401.87 sec,  Memory: total:    56.03 Gb, per task: min =     9.25 Gb, max =     9.43 Gb
Run: Finishing oops::Variational<FV3JEDI, UFO and IODA observations> with status = 0
OOPS Ending   2023-01-23 18:50:42 (UTC+0000)
(gdasapp) Hera(hfe09):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/pr1265/sorc/gdas.cd/ush$
```
and Orion
```
OOPS_STATS ---------------------------------- Parallel Timing Statistics (   6 MPI tasks) -----------------------------------

OOPS_STATS Run end                                  - Runtime:    428.68 sec,  Memory: total:    55.39 Gb, per task: min =     9.08 Gb, max =     9.41 Gb
Run: Finishing oops::Variational<FV3JEDI, UFO and IODA observations> with status = 0
OOPS Ending   2023-01-23 19:07:38 (UTC+0000)
(gdasapp) Orion-login-3:/work2/noaa/da/rtreadon/git/global-workflow/pr1265/sorc/gdas.cd/ush$
```

Given the above change this PR from draft to active.

**Review by CoryMartin-NOAA — APPROVED** [review]
Everything here looks good to me, thanks @RussTreadon-NOAA !

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , would you like to take another look at this PR or are you OK with your previous approval?   

I'd like to merge this PR into GDASApp `develop` today (1/24) so I can update the GDASApp hash in g-w PR [#1265](https://github.com/NOAA-EMC/global-workflow/pull/1265) and get that PR into g-w `develop`.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres , would you like to take another look at this PR or are you OK with your previous approval?
> 
> I'd like to merge this PR into GDASApp `develop` today (1/24) so I can update the GDASApp hash in g-w PR [#1265](https://github.com/NOAA-EMC/global-workflow/pull/1265) and get that PR into g-w `develop`.

All good @RussTreadon-NOAA ! Sorry for holding up the merge.

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Comment by RussTreadon-NOAA** [comment]
Thank you @guillaumevernieres!

**Pull request merged**
