### PR TITLE
Converter script to change/add to EWOK YAMLs for use in GDASApp

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
This script will:

- Change paths where appropriate
- Remove CO2 from the obs operator where appropriate
- Add a standard covariance section

so that EWOK YAMLs for each ob type (e.g. in ufo/ewok/jedi-gdas) can be translated for use here in GDASApp with minimal user intervention.

### CODE REVIEW

**Review by ADCollard — DISMISSED** [review]

**Review by emilyhcliu — DISMISSED** [review]

**Review by guillaumevernieres — COMMENTED** [review]
How about adding a simple test @CoryMartin-NOAA ?

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres can do, soon, you and your good testing practices!

**Review by RussTreadon-NOAA — COMMENTED** [review]
Changes look good.   Tested `ush/covert_yaml_ewok2gdas.py` with several `ufo/ewok/jedi-gdas` yaml files.   Script seems to work as advertised.    

`yaml.dump` appears to write the output yaml in alphabetical order.   This is OK but it complicates comparing the `jedi-gdas` yaml with the converted yaml.   I added `sort_keys=False` to the `yaml.dump` arguments.    With this change the order remains the same between the two.   The converted yaml replaces horizontal `[  ]` lists into vertical `- ` lists. 

Ideally I'd like to see an output yaml which is identical to the input yaml except for lines which were removed, added, or modified.   Is this possible?   This isn't a requirement for this PR.  Just curious.

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA I don't think it is possible unless we parse the text file manually and find/replace, which I was hoping to avoid as that can get messy. However, I have found that there is `default_flow_style=None` (which I think is default) which will determine whether to make the lists on one or multiple lines depending on the size of the list. Would that be preferred?

**Comment by FanHan-NOAA** [comment]
> Changes look good. Tested `ush/covert_yaml_ewok2gdas.py` with several `ufo/ewok/jedi-gdas` yaml files. Script seems to work as advertised.
> 
> `yaml.dump` appears to write the output yaml in alphabetical order. This is OK but it complicates comparing the `jedi-gdas` yaml with the converted yaml. I added `sort_keys=False` to the `yaml.dump` arguments. With this change the order remains the same between the two. The converted yaml replaces horizontal `[ ]` lists into vertical `- ` lists.
> 
> Ideally I'd like to see an output yaml which is identical to the input yaml except for lines which were removed, added, or modified. Is this possible? This isn't a requirement for this PR. Just curious.

I know that yaml parsing tools (and yaml itself in design) generally do not care the order of mappings (except list order is preserved), so @CoryMartin-NOAA do you know of any utility tool (e.g., yamldiff a.yaml b.yaml) that compares two yamls and print out inconsistencies? I recall you had such tool and it would be handy in this case.

**Comment by CoryMartin-NOAA** [comment]
@FanHan-NOAA there is https://github.com/NOAA-EMC/GDASApp/blob/develop/ush/check_yaml_keys.py, combined with its driver test script, theoretically this could do the trick but I would need to test it to see how robust it is.

**Review by guillaumevernieres — APPROVED** [review]
Thanks for addressing this reviewer's tantrum @CoryMartin-NOAA !

**Comment by RussTreadon-NOAA** [comment]
> @RussTreadon-NOAA I don't think it is possible unless we parse the text file manually and find/replace, which I was hoping to avoid as that can get messy. However, I have found that there is `default_flow_style=None` (which I think is default) which will determine whether to make the lists on one or multiple lines depending on the size of the list. Would that be preferred?

Thank you, @CoryMartin-NOAA , for trying different options.  

I ran `sondes.yaml`, `omi_arua.yaml`, and `amsua_n19.yaml through `convert_yaml_ewok2gdas.py` with various options for `yaml.dump`.  

With `default_flow_style=None` the original section of `ufo/ewok/jedi-gdas/sondes.yaml` 
```
  - filter: Bounds Check
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    minvalue: -130
    maxvalue: 130
    action:
      name: reject
```
is converted to  
```
- action: {name: reject}
  filter: Bounds Check
  filter variables:
  - {name: eastward_wind}
  - {name: northward_wind}
  maxvalue: 130
  minvalue: -130
```
I can easily see the addition of `{ }` pairs tripping me up if I were to take a converted yaml and start editing it. 

`convert_yaml_ewok2gdas.py` without any changes (retain `default_flow_style=False`) yields
```
- action:
    name: reject
  filter: Bounds Check
  filter variables:
  - name: eastward_wind
  - name: northward_wind
  maxvalue: 130
  minvalue: -130
```
This is OK but it reordered the section alphabetically:  `action`, `filter`, `maxvalue`, `minvalue`.

Retaining `default_flow_style=False` and adding `sort_keys=False` yields
```
- filter: Bounds Check
  filter variables:
  - name: eastward_wind
  - name: northward_wind
  minvalue: -130
  maxvalue: 130
  action:
    name: reject
```
This retains the order of the original input `ufo/ewok/jedi-gdas/sondes.yaml`.

Yaml files can be complicated.  There are likely cases for which `sort_keys=False` doesn't yield _pretty_ output.   Whatever options we use on the `yaml.dump` line, the converted should be readable by JEDI apps.   Don't let my comments slow the addition of `convert_yaml_ewok2gdas.py` to GDASApp.

**Review by RussTreadon-NOAA — APPROVED** [review]
Thank you, @CoryMartin-NOAA , for adding a ctest.

**Pull request merged**
