### PR TITLE
Move the variational scripts to the g-w

### PR DESCRIPTION
**Pull request by guillaumevernieres**
This PR needs to be merged before
 - [https://github.com/NOAA-EMC/global-workflow/pull/2920](https://github.com/NOAA-EMC/global-workflow/pull/2920)
 
It depends on 
- [https://github.com/NOAA-EMC/jcb-gdas/pull/26](https://github.com/NOAA-EMC/jcb-gdas/pull/26)

and will require an update to the `jcb-gdas` submodules.

It will break the GDASApp marine CI until the `g-w` pr is merged.

### CODE REVIEW

**Review by AndrewEichmann-NOAA — COMMENTED** [review]
This looks very satisfying

**Review by apchoiCMD — DISMISSED** [review]
Looks great!

**Comment by RussTreadon-NOAA** [comment]
Compare `/scratch1/NCEPDEV/da/role.jedipara/CI/GDASApp/workflow/PR/1282/global-workflow/sorc/logs/build_gdas.log` with `/scratch1/NCEPDEV/da/role.jedipara/git/global-workflow/radbcor/sorc/logs/build_gdas.log`.  

The `PR/1282` `build_gdas.log` contains
```
-- Adding bundle project gdas
-- ---------------------------------------------------------
-- [GDASApp] (1.0.0)
-- Feature TESTS enabled
-- Found Python3: /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/intel/2021.5.0/python-3.10.13-2p2rady/bin/python3.10 (found version "3.10.13") found components: Interpreter
CMake Error at gdas/test/gw-ci/CMakeLists.txt:7 (set_tests_properties):
  set_tests_properties Can not find test to add properties to:
  WCDA-3DVAR-C48mx500
Call Stack (most recent call first):
  gdas/test/gw-ci/CMakeLists.txt:62 (add_cycling_tests)
```
whereas `radbcor` `build_gdas.log` has
```
-- Adding bundle project gdas
-- ---------------------------------------------------------
-- [GDASApp] (1.0.0)
-- Feature TESTS enabled
-- Found Python3: /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/intel/2021.5.0/python-3.10.13-2p2rady/bin/python3.10 (found version "3.10.13") found components: Interpreter
ctest for JGLOBAL_PREP_OCEAN_OBS
ctest for JGLOBAL_MARINE_BMAT
ctest for JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
ctest for JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN
ctest for JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
ctest for JGDAS_GLOBAL_OCEAN_ANALYSIS_POST
-- ---------------------------------------------------------
```

I see the comment _It will break the GDASApp marine CI until the g-w pr is merged._ [above](https://github.com/NOAA-EMC/GDASApp/pull/1282#issue-2525370156).  

 - Does this mean the hera-GW-RT failure is expected until g-w PR [#2920](https://github.com/NOAA-EMC/global-workflow/pull/2920) is merged?
 - Until then, do we need to run GDASApp CI inside a working copy of the PR [#2920](https://github.com/NOAA-EMC/global-workflow/pull/2920) branch, [`guillaumevernieres:feature/marinevar`](https://github.com/guillaumevernieres/global-workflow/tree/feature/marinevar)?

**Comment by guillaumevernieres** [comment]
Thanks for checking @RussTreadon-NOAA . The CI for this PR should work, it's built/tested against the g-w feature/marinevar branch from [NOAA-EMC/global-workflow/pull/2920](https://github.com/NOAA-EMC/global-workflow/pull/2920).
I'll fix the issue this am.

**Review by JohnSteffen-NOAA — APPROVED** [review]
Looks good.

**Review by apchoiCMD — APPROVED** [review]
Looks promising!

**Comment by guillaumevernieres** [comment]
1/2 :tada: 

```
...
      Start 1890: test_gdasapp_WCDA-3DVAR-C48mx500
23/46 Test #1890: test_gdasapp_WCDA-3DVAR-C48mx500 ...................................   Passed    9.41 sec
      Start 1891: test_gdasapp_WCDA-3DVAR-C48mx500_gdasstage_ic_202103241200
24/46 Test #1891: test_gdasapp_WCDA-3DVAR-C48mx500_gdasstage_ic_202103241200 .........   Passed  1095.50 sec
      Start 1892: test_gdasapp_WCDA-3DVAR-C48mx500_gdasfcst_202103241200
25/46 Test #1892: test_gdasapp_WCDA-3DVAR-C48mx500_gdasfcst_202103241200 .............   Passed  432.87 sec
      Start 1893: test_gdasapp_WCDA-3DVAR-C48mx500_gdasprepoceanobs_202103241800
26/46 Test #1893: test_gdasapp_WCDA-3DVAR-C48mx500_gdasprepoceanobs_202103241800 .....   Passed  545.51 sec
      Start 1894: test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarinebmat_202103241800
27/46 Test #1894: test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarinebmat_202103241800 .......   Passed  430.77 sec
      Start 1895: test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlinit_202103241800
28/46 Test #1895: test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlinit_202103241800 ....   Passed   81.69 sec
      Start 1896: test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlvar_202103241800
29/46 Test #1896: test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlvar_202103241800 .....   Passed  200.57 sec
      Start 1897: test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlchkpt_202103241800
30/46 Test #1897: test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlchkpt_202103241800 ...   Passed  124.72 sec
      Start 1898: test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlfinal_202103241800
31/46 Test #1898: test_gdasapp_WCDA-3DVAR-C48mx500_gdasmarineanlfinal_202103241800 ...   Passed  106.90 sec
...
```
 
Should I ignore the atmos tests @RussTreadon-NOAA ? They are all failing, I hope I didn't delete something I shouldn't have during my ```rm *``` frenzy.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres:  Yes, we expect atmanlinit and atmensanlinit to fail because GDASApp has been updated to process a radiance bias correction tarball.  g-w still assumes we are dealing with _satellite_sensor_ specific radiance bias correction files.  

g-w PR [#2875](https://github.com/NOAA-EMC/global-workflow/pull/2875) has the fix but this PR has not yet been approved and merged into g-w `develop`.  

I looked at `/scratch1/NCEPDEV/da/role.jedipara/CI/GDASApp/workflow/PR/1282/global-workflow/sorc/gdas.cd/build/gdas/test/atm/global-workflow/testrun/atmanlinit-66754880.out` and confirmed that the failure is  due to the radiance bias correction file disconnect.

**Comment by guillaumevernieres** [comment]
I'm going to merge this, which will break the marine DA ctest. Ignore until [NOAA-EMC/global-workflow/pull/2920](https://github.com/NOAA-EMC/global-workflow/pull/2920) is merged.

**Pull request merged**
