### PR TITLE
Make use of BUMP (again) in soca B

### PR DESCRIPTION
**Pull request by guillaumevernieres**
The saber block for bump is outdated.
I added it back to the background error so it is again part of the ci.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Orion:
The build crashed trying to clone `saber`
```
fatal: unable to access 'https://github.com/jcsda/saber.git/': Failed to connect to github.com port 443 after 40 ms: Connection refused
```
Hera:
Is there an issue with `test_gdasapp_atm_jjob_var_run` @RussTreadon-NOAA or is it just timing out?

The test relevant to this PR are OK on Hera.

**Comment by RussTreadon-NOAA** [comment]
The log file
`/scratch1/NCEPDEV/da/Cory.R.Martin/CI/GDASApp/workflow/PR/361/global-workflow/sorc/gdas.cd/build/test/atm/global-workflow/testrun/slurm-42090147.out` contains
```
0: amsua_n19: save database to /scratch1/NCEPDEV/da/Cory.R.Martin/CI/GDASApp/workflow/PR/361/global-workflow/sorc/gdas.cd/build/test/atm/gl\
obal-workflow/testrun/RUNDIR/87147/diags/diag_amsua_n19_2021032318.nc4 (io pool size: 1)
1: Bad parameter: /: Mandatory parameter 'obserr_function' not found caught in  (/scratch1/NCEPDEV/da/Cory.R.Martin/CI/GDASApp/workflow/PR/\
361/global-workflow/sorc/gdas.cd/oops/src/oops/runs/Run.cc +193 execute)
1: Exception: oops::Variational<FV3JEDI, UFO and IODA observations> terminating...
1: Exception stack:
1: Bad parameter: /: Mandatory parameter 'obserr_function' not found
```
The input yaml 
`/scratch1/NCEPDEV/da/Cory.R.Martin/CI/GDASApp/workflow/PR/361/global-workflow/sorc/gdas.cd/build/test/atm/global-workflow/testrun/RUNDIR/87147/fv3jedi_var.yaml`

contains `obserr_function` twice so I don't know what the problem is.

**Comment by RussTreadon-NOAA** [comment]
Ran `test_gdasapp_atm_jjob_var_run` from Hera installation of the current heads of g-w develop ([`383c8c3a`](https://github.com/NOAA-EMC/global-workflow/commit/383c8c3a25dbeedb3a4892d22d2531286e87389f)) and GDASApp develop ([`13e3951`](https://github.com/NOAA-EMC/GDASApp/commit/13e3951a116338e7d6b727332145b80d9da00293)).    The test passed

```
(gdasapp) Hera(hfe11):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/workatm/sorc/gdas.cd/build$ ctest -R test_gdasapp_atm_jjob_var_run
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/workatm/sorc/gdas.cd/build
    Start 1355: test_gdasapp_atm_jjob_var_run
1/1 Test #1355: test_gdasapp_atm_jjob_var_run ....   Passed   75.06 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =  75.38 sec
```

**Comment by guillaumevernieres** [comment]
> Ran `test_gdasapp_atm_jjob_var_run` from Hera installation of the current heads of g-w develop ([`383c8c3a`](https://github.com/NOAA-EMC/global-workflow/commit/383c8c3a25dbeedb3a4892d22d2531286e87389f)) and GDASApp develop ([`13e3951`](https://github.com/NOAA-EMC/GDASApp/commit/13e3951a116338e7d6b727332145b80d9da00293)). The test passed
> 
> ```
> (gdasapp) Hera(hfe11):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/workatm/sorc/gdas.cd/build$ ctest -R test_gdasapp_atm_jjob_var_run
> Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/workatm/sorc/gdas.cd/build
>     Start 1355: test_gdasapp_atm_jjob_var_run
> 1/1 Test #1355: test_gdasapp_atm_jjob_var_run ....   Passed   75.06 sec
> 
> 100% tests passed, 0 tests failed out of 1
> 
> Total Test time (real) =  75.38 sec
> ```

I'll just resubmit both again @RussTreadon-NOAA . Thanks for looking into it.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres and @CoryMartin-NOAA 

I reproduced the `test_gdasapp_atm_jjob_var_run` failure.   I forgot that `CMakeLists.txt` now pulls from the head of `develop` for several JCSDA repos.  Before we cloned specific hashes.  

The `Passed` result for `test_gdasapp_atm_jjob_var_run` was from a 2/14 build of GDASApp `develop`.   While I updated GDASApp `develop` to the 2/17 head, I did not update the JEDI components to the head of their develop branches.   The `Failed` result I just got is from a 5 pm 2/17 installation of GDASApp `develop`.   The head of develop for several JEDI repos changed between 2/14 and 2/17

The 2/14 GDASApp build for which ``test_gdasapp_atm_jjob_var_run` passes used the following hashes:
- oops at `c0584673`
- vader at `425fbab`
- saber at `519fa414`
- ioda at `8b18263`
- femps at `cb39681`
- fv3-jedi at `2774804d`

The 2/17 GDASApp build for which `test_gdasapp_atm_jjob_var_run` fails used the following hashes:
- oops at `6b493620`
- vader at `5b289d4`
- saber at `3a247238`
- ioda at `552bc75`
- femps at `cb39681`
- fv3-jedi at 79101d2c`.

Only the `femps` hash is identical between 2/14 and 2/17.   All other hashes changed over the past 3 days.  

Something going into the `fv3jedi_var.x` build changed between 2/14 and 2/17.  This change or set of changes is causing `test_gdasapp_atm_jjob_var_run` to fail.   It seems something is now missing from the GDASApp `parm/atm/obs/config/amsua_n19.yaml`.   This is the obs file `test_gdasapp_atm_jjob_var_run` processes.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres and @CoryMartin-NOAA
> 
> I reproduced the `test_gdasapp_atm_jjob_var_run` failure. I forgot that `CMakeLists.txt` now pulls from the head of `develop` for several JCSDA repos. Before we cloned specific hashes.
> 
> The `Passed` result for `test_gdasapp_atm_jjob_var_run` was from a 2/14 build of GDASApp `develop`. While I updated GDASApp `develop` to the 2/17 head, I did not update the JEDI components to the head of their develop branches. The `Failed` result I just got is from a 5 pm 2/17 installation of GDASApp `develop`. The head of develop for several JEDI repos changed between 2/14 and 2/17
> 
> The 2/14 GDASApp build for which ``test_gdasapp_atm_jjob_var_run` passes used the following hashes:
> 
> * oops at `c0584673`
> * vader at `425fbab`
> * saber at `519fa414`
> * ioda at `8b18263`
> * femps at `cb39681`
> * fv3-jedi at `2774804d`
> 
> The 2/17 GDASApp build for which `test_gdasapp_atm_jjob_var_run` fails used the following hashes:
> 
> * oops at `6b493620`
> * vader at `5b289d4`
> * saber at `3a247238`
> * ioda at `552bc75`
> * femps at `cb39681`
> * fv3-jedi at 79101d2c`.
> 
> Only the `femps` hash is identical between 2/14 and 2/17. All other hashes changed over the past 3 days.
> 
> Something going into the `fv3jedi_var.x` build changed between 2/14 and 2/17. This change or set of changes is causing `test_gdasapp_atm_jjob_var_run` to fail. It seems something is now missing from the GDASApp `parm/atm/obs/config/amsua_n19.yaml`. This is the obs file `test_gdasapp_atm_jjob_var_run` processes.

Thanks for looking into it @RussTreadon-NOAA . Sounds like a non-urgent problem for next week!

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres and @CoryMartin-NOAA , the missing `obserr_function` section has been identified.   The corrected `amsua_n19.yaml` is on Hera in `/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/test/sorc/gdas.cd/parm/atm/obs/config`.   A `git diff` of the updated `amsua_n19.yaml` returns

```
diff --git a/parm/atm/obs/config/amsua_n19.yaml b/parm/atm/obs/config/amsua_n19.yaml
index f0708ac..0096f2f 100644
--- a/parm/atm/obs/config/amsua_n19.yaml
+++ b/parm/atm/obs/config/amsua_n19.yaml
@@ -250,6 +250,29 @@ obs filters:
             clwret_clearsky: [0.050, 0.030, 0.030, 0.020, 0.000,
                               0.100, 0.000, 0.000, 0.000, 0.000,
                               0.000, 0.000, 0.000, 0.000, 0.030]
+        obserr_function:
+          name: ObsFunction/ObsErrorModelRamp
+          channels: *amsua_n19_channels
+          options:
+            channels: *amsua_n19_channels
+            xvar:
+              name: ObsFunction/CLWRetSymmetricMW
+              options:
+                clwret_ch238: 1
+                clwret_ch314: 2
+                clwret_types: [ObsValue, HofX]
+            x0:    [ 0.050,  0.030,  0.030,  0.020,  0.000,
+                     0.100,  0.000,  0.000,  0.000,  0.000,
+                     0.000,  0.000,  0.000,  0.000,  0.030]
+            x1:    [ 0.600,  0.450,  0.400,  0.450,  1.000,
+                     1.500,  0.000,  0.000,  0.000,  0.000,
+                     0.000,  0.000,  0.000,  0.000,  0.200]
+            err0:  [ 2.500,  2.200,  2.000,  0.550,  0.300,
+                     0.230,  0.230,  0.250,  0.250,  0.350,
+                     0.400,  0.550,  0.800,  3.000,  3.500]
+            err1:  [20.000, 18.000, 12.000,  3.000,  0.500,
+                     0.300,  0.230,  0.250,  0.250,  0.350,
+                     0.400,  0.550,  0.800,  3.000, 18.000]
         obserr_clearsky: [2.500, 2.200, 2.000, 0.550, 0.300,
                           0.230, 0.230, 0.250, 0.250, 0.350,
                           0.400, 0.550, 0.800, 3.000, 3.500]
```

With this addition `test_gdasapp_atm_jjob_var_run` passed when using the 2/17 GDASApp build.

**Comment by RussTreadon-NOAA** [comment]
Hera and Orion GW-RT now pass.  _Yeah!_

**Review by andytangborn — APPROVED** [review]
It's passing all the tests, so it looks fine to me.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
