### PR TITLE
simplify wxflowpath in ctest scripts

### LINKED ISSUE #1196: Clean up wxflow references in test scripts
Several scripts used in ctests add `wxflow` to `PYTHONPATH` via
```
wxflowPATH="${HOMEgfs}/ush/python:${HOMEgfs}/ush/python/wxflow"
```
`${HOMEgfs}/ush/python` contains `wxflow`.  It is not necessary to also specify `${HOMEgfs}/ush/python/wxflow`.   

This issue is opened to simplify the `wxflowPATH`.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
This PR simplifies the setting of `wxflowPATH` in ctest scripts.

Resolves #1196

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , @guillaumevernieres , & @DavidNew-NOAA 

g-w PR [#2700](https://github.com/NOAA-EMC/global-workflow/pull/2700) depends on this PR.   The `gdas.cd` hash will be updated in PR [#2700](https://github.com/NOAA-EMC/global-workflow/pull/2700) once this PR is merged into `develop`.

If any you you have time a review and approval would be much appreciated.

**Review by CoryMartin-NOAA — APPROVED** [review]
Look good, thanks @RussTreadon-NOAA

**Review by guillaumevernieres — APPROVED** [review]
Thanks @RussTreadon-NOAA . I'm guessing the ci against the dev/gdasapp is broken?

**Comment by RussTreadon-NOAA** [comment]
Thank you @CoryMartin-NOAA

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , I did not try ci against `dev/gdasapp`.  I simply ran ctests inside the pre-built working copy I had on Hera. This PR does not alter CI behavior.  What we had previously works.  This PR only removes redundancy in getting `wxflow` into `PYTHONPATH`.

**Pull request merged**
