### PR TITLE
Get rid of DRIPCG

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
A little (tall?) birdie has informed us that we apparently should not be using DRIPCG, and seems we are using DRIPCG in our tests. This PR removes that. Note that the global-workflow will likely need modified in `config.atmanl` to use the different YAML name.

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
Changes are straight forward.  Yes, g-w `parm/config.gfs/config.atmanl` will need to replace
```
export ATMVARYAML=${HOMEgfs}/sorc/gdas.cd/parm/atm/variational/3dvar_dripcg.yaml
```
with 
```
export ATMVARYAML=${HOMEgfs}/sorc/gdas.cd/parm/atm/variational/3dvar_pcg.yaml
```

One question.  Why do we switch to `PCG` instead of `DRPCG`.   I thought the problem was with the `I` (inexact) part of the PCG.  What do JCSDA and GMAO use for the variational DA runs?

**Comment by CoryMartin-NOAA** [comment]
Good question @RussTreadon-NOAA , and I have no good answer! I don't even know why we started with DRIPCG besides that is what a lot of the JCSDA test YAMLs use.

**Comment by RussTreadon-NOAA** [comment]
@shoyokota may have some insights regarding which minimizer, among [various options](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/jedi-components/oops/applications/variational.html), we should consider using.  Of course, we should test various minimizers in single obs, stand-alone, and cycled modes.  Doing so is not a pre-requisite for this PR.

**Comment by CoryMartin-NOAA** [comment]
@DavidNew-NOAA is going to test a few in the next week or so for his AMS poster. But that will be single analysis testing and not cycling. I think GMAO is using DRPCG, or at least Ricardo has a PR to OOPS to fix DRPCG and DRIPCG.

**Review by andytangborn — DISMISSED** [review]
Seems simple enough. I can run a single analysis time experiment to see what the impact is going to be for aerosol DA.

**Comment by RussTreadon-NOAA** [comment]
FYI:  Ricardo's [OOPS](https://github.com/JCSDA-internal/oops) issue is [#2475](https://github.com/JCSDA-internal/oops/issues/2475).  The corresponding PR is [#2476](https://github.com/JCSDA-internal/oops/pull/2476).

**Review by DavidNew-NOAA — DISMISSED** [review]
Seems pretty straightforward. I'll get some data on algorithm performance next week with the experiments for my AMS poster.

**Comment by CoryMartin-NOAA** [comment]
@DavidNew-NOAA found that PCG is slow, and NRL is apparently using DRPCG, so I've updated to use DRPCG.

**Review by RussTreadon-NOAA — COMMENTED** [review]
Looks good to me.  Approve.

**Review by RussTreadon-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
g-w PR [#2225](https://github.com/NOAA-EMC/global-workflow/pull/2225) was just opened to update the GDASApp hash cloned by g-w.  If this PR is merged into `develop` before [#2225](https://github.com/NOAA-EMC/global-workflow/pull/2225) is acted upon, I'll update the GDASApp hash to include changes from this PR.

**Comment by CoryMartin-NOAA** [comment]
Thanks @RussTreadon-NOAA you beat me to it! I think there may be some minor changes that will need to be made to g-w config files when this PR is merged. Like the 3dvar YAML template for example.

I'll merge this now.

**Pull request merged**
