### PR TITLE
Update JEDI hashes to include Model Variable Renaming Sprint

### LINKED ISSUE #1313: Resume nightly testing of GDASApp
Directory `ci` contains the following scripts
```
driver.sh  gw_driver.sh  hera.sh  orion.sh  run_ci.sh  run_gw_ci.sh  stable_driver.sh
```
along with directory `validation`.  

`stable_driver.sh` was previously run via cron to 
- clone global-workflow `develop`
- update jedi hashes in `sorc/gdas.cd`
-  build g-w with updated `sorc/gdas.cd`
- run GDASApp ctests
- if all tests _Passed_ push updated `sorc/gdas.cd` to GDASApp `feature/stable-nightly`

The nightly cron was turned off after several failures.

This issue is opened to document the work needed to resume nightly testing of GDASApp.

### LINKED ISSUE #1362: Integrate Model Variable Renaming Sprint changes in to GDASApp yamls and templates
Several JEDI repositories have been updated with changes from the Model Variable Renaming Sprint.  Updating JEDI hashes in `sorc/` requires changes in GDASApp and jcb-gdas yamls and templates.  This issue is opened to document these changes.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
This PR updates JEDI hashes in `sorc/` to bring in changes associated with the Model Variable Renaming Sprint.  This is required to fully resolve #1313.

Resolves #1313
Resolves #1362

Depends:  jcb-gdas [#45](https://github.com/NOAA-EMC/jcb-gdas/pull/45)

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Create dummy g-w PR [#3052](https://github.com/NOAA-EMC/global-workflow/pull/3052) with branch name `feature/resume_nightly`.  hera-GW-RT should detect that this g-w branch exists and clone it instead of g-w `develop`.

**Comment by RussTreadon-NOAA** [comment]
Test was successful in that the dummy g-w PR [#3052](https://github.com/NOAA-EMC/global-workflow/pull/3052) was installed with GDAApp branch `feature/resume_nightly` cloned inside `sorc/gdas.cd`.

**Comment by RussTreadon-NOAA** [comment]
Close g-w PR [#3052](https://github.com/NOAA-EMC/global-workflow/pull/3052) upon completion of successful test.

**Comment by RussTreadon-NOAA** [comment]
Remove **Dummy** from title and place in draft mode.  

Execute [`ush/submodules/update_develop.sh`](https://github.com/NOAA-EMC/GDASApp/blob/feature/resume_nightly/ush/submodules/update_develop.sh) in working copy of `feature/resume_nightly`.  Working through yaml and template changes required by JEDI model variable renaming sprint.

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA , I am getting the error
```
ValueError: The dictionary of templates must have an algorithm key
```
when running `test_gdasapp_atm_jjob_var_init` using GDASApp branch `feature/resume_nightly_mod` inside g-w `develop` at [152bb45](https://github.com/NOAA-EMC/global-workflow/commit/152bb45041ff7b69d14db98648b351a8f527e8d5).  

I'm thinking that I need to update my copy of g-w to your `DavidNew-NOAA:feature/jcb-obsbias` from g-w PR [#2992](https://github.com/NOAA-EMC/global-workflow/pull/2992).  I wanted to run this by you before updating and rebuilding.

**Comment by DavidNew-NOAA** [comment]
Hi Russ,

Hmmm. Because #2992 <https://github.com/NOAA-EMC/global-workflow/pull/2992> is
still in review but its companion PR in GDASApp was merged, the jjob tests
shouldn't pass. That was the one thing that that GDASApp PR did break,
though I would expect a slightly different error.

I would first try reverting test/atm/global-workflow/config.yaml to the
follow hash and let me know what happens:

9d95c9d0cff5de0567885a9aa045ec35fd436bb1

I have a meeting with Rahul and Walter at 11 AM to get this #2992
<https://github.com/NOAA-EMC/global-workflow/pull/2992> business sorted
out, so hopefully this problem will soon be irrelevant.

David

**Comment by RussTreadon-NOAA** [comment]
Will keep this PR in draft mode until GDASApp and jcb-gdas yamls and templates work with updated JEDI hashes.

**Comment by RussTreadon-NOAA** [comment]
The changes in this PR have been tested in g-w PR [#2992](https://github.com/NOAA-EMC/global-workflow/pull/2992). 

Tests completed include:
1. test_gdasapp 
   - 64/64 tests pass on Hera, Hercules, and Orion
2. g-w DA CI 
   - four configurations tested: GSI, JEDI ATM, JEDI Aerosol/Snow, JEDI WCDA
   - all four configurations successfully run all jobs on Hera, Hercules, and Orion
   - GSI and JED ATM CI work _as is" on Dogwood (WCOSS2)
   - JEDI Aerosol/Snow DA and JEDI WCDA work on Dogwood when GDASApp branch `feature/resume_nightly' (this PR) is built with `spack-stack/1.6.0`

**Comment by RussTreadon-NOAA** [comment]
This PR **SHOULD NOT** be merged into `develop` until jcb-gdas PR [#45](https://github.com/NOAA-EMC/jcb-gdas/pull/45) is approved and merged into jcb-gdas `develop`.  Once this is done, the `parm/jcb-gdas` hash in `feature/resume_nightly` should be updated to the new jcb-gdas `develop` hash.

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , @AndrewEichmann-NOAA , @DavidNew-NOAA, @CoryMartin-NOAA  - this PR is ready for final review.  It's been tested in g-w [#2992](https://github.com/NOAA-EMC/global-workflow/pull/2992).

**Review by DavidNew-NOAA — APPROVED** [review]
Looks good, especially given all the testing. Nice work, @RussTreadon-NOAA

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
Thank you @DavidNew-NOAA and @CoryMartin-NOAA for the quick approvals.  I'll go ahead and merge.

**Pull request merged**
