### PR TITLE
Quick indentation bugfix

### PR DESCRIPTION
**Pull request by DavidNew-NOAA**
Title says it all

### CODE REVIEW

**Comment by DavidNew-NOAA** [comment]
I'm actually getting an error trying to run with this ob. Anyone know the deal with it? Can I just comment it out for the sake of develop not breaking?

**Comment by RussTreadon-NOAA** [comment]
Does the error look like the [traceback reported](https://github.com/NOAA-EMC/GDASApp/issues/1362#issuecomment-2460531911) in issue #1362?

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA , the `- abi_g16` line in `parm/atm/jcb-prototype_3dvar.yaml.j2` has an extra space before the hyphen.  I removed the extra space and 2024022400 `gfs_atmanlinit` ran to completion
```
hercules-login-4:/work/noaa/da/rtreadon/git/global-workflow/pr2992/sorc/gdas.cd/parm/atm$ git diff jcb-prototype_3dvar.yaml.j2
diff --git a/parm/atm/jcb-prototype_3dvar.yaml.j2 b/parm/atm/jcb-prototype_3dvar.yaml.j2
index 1975c1f..c90b747 100644
--- a/parm/atm/jcb-prototype_3dvar.yaml.j2
+++ b/parm/atm/jcb-prototype_3dvar.yaml.j2
@@ -29,4 +29,4 @@ observations:
 #  - satwnd.viirs_npp
 #  - scatwind_ascat_metop-a
 #  - snowcvr
-   - abi_g16
+  - abi_g16
```

**Review by RussTreadon-NOAA — DISMISSED** [review]
This change works.

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA My PR adds that space and indeed that atmanlinit job runs to completion, but that atmanlvar job fails now

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA I don't have the output in front of me right now. I'll have to look later, but it's related to that particular ob

**Comment by RussTreadon-NOAA** [comment]
2024022400 gfs_atmanlvar failed because abi_g16 bias correction files are not present in the job run directory.  The radiance bias correction tarball for g-w CI C96C48_ufs_hybatmDA only contains bias correction files for atms_n20 and atms_npp.

Two options:
1. comment out `abi_g16` in `parm/atm/jcb-prototype_3dvar.yaml.j2`
2. add abi_g16 radiance correction files to g-w `$ICSDIR/C96C48/gdas.20240223/18/analysis/atmos/gdas.t18z.rad_varbc_params.tar`

**Comment by CoryMartin-NOAA** [comment]
why does it fail? JEDI crashes or something else? I would think that if the BC files are missing, it should run with no BC the first cycle, right? How would we spin up BC on a new sensor?

**Comment by RussTreadon-NOAA** [comment]
I don't think JEDI currently has the ability to spin up radiance bias correction files.   Is this true, @emilyhcliu ?

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA @CoryMartin-NOAA Given the moderate complexity of this question, I would say let's just comment out that ob so develop continues to work and make a separate issue.

**Comment by RussTreadon-NOAA** [comment]
I agree.  If you can push this change (comment out `abi_g16`) I'll approve and we can merge.

**Review by RussTreadon-NOAA — APPROVED** [review]
Approve

**Comment by DavidNew-NOAA** [comment]
See GDASApp issue [#1364](https://github.com/NOAA-EMC/GDASApp/issues/1364)

**Pull request merged**
