### PR TITLE
Add updates for ozone and end-to-end results

### PR DESCRIPTION
**Pull request by emilyhcliu**
GDAS assimilates two types of ozone:
- Total Column Ozone 
- Profile Ozone

For the focus cycle: 2021080100Z, ozone data includes:
- ompsnp npp (profile ozone)
- ompstc npp (total ozone)
- omi aura (total ozone)

This PR includes the following updates for the three ozone data above:
- BUFR converters 
- ObsSpace YAML files
- Validation result

Here is the updated QC flowchart for ozone:
GSI-ozone-flowchart

### CODE REVIEW

**Comment by emilyhcliu** [comment]
### OMPSTC NPP  (Total Column Ozone)
**IODA data coverage converted from BUFR**
ufo_ompstc8_npp_omf_ozoneTotal_noqc
**QC (thinning applied)**
ufo_ompstc8_npp_omf_ozoneTotal_qc
**GSI (reference for validation)**
gsi_ompstc8_npp_omf_ozoneTotal_qc

**Comment by emilyhcliu** [comment]
### OMI AURA (Total Column Ozone)
**IODA data coverage converted from BUFR**
ufo_omi_aura_omf_ozoneTotal_noqc

**QC (Thinning applied)**
ufo_omi_aura_omf_ozoneTotal_qc

**GSI (reference for validation)**
gsi_omi_aura_omf_ozoneTotal_qc

**Comment by emilyhcliu** [comment]
### OMPSNP NPP (Profile Ozone; 21  layers)
**QC (no thinning) @ 100 hPa**

ufo_ompsnp_npp_omf_ozoneLayer_qc_1013_colret

**GSI (reference for validation) @ 100 hPa**
gsi_ompsnp_npp_omf_ozoneLayer_qc_1013

**Averaged Global Ozone Profile (after QC): GSI vs. UFO**
GSI | UFO
--- | ---
gsi|ufo

**Comment by emilyhcliu** [comment]
The converters and QC filter results are comparable to GSI.
However.... the increments are huge!
Here is the increment stats for OMPSNP (staticB is `identity`):
```
15002   0: ----------------------------------------------------------------------------------------------------
15003   0: Increment print | number of fields = 8 | cube sphere face size: C384
15004   0: eastward_wind                                | Min:+0.000000e+00 Max:+0.000000e+00 RMS:+0.000000e+00
15005   0: northward_wind                               | Min:+0.000000e+00 Max:+0.000000e+00 RMS:+0.000000e+00
15006   0: air_temperature                              | Min:+0.000000e+00 Max:+0.000000e+00 RMS:+0.000000e+00
15007   0: surface_pressure                             | Min:+0.000000e+00 Max:+0.000000e+00 RMS:+0.000000e+00
15008   0: specific_humidity                            | Min:+0.000000e+00 Max:+0.000000e+00 RMS:+0.000000e+00
15009   0: cloud_liquid_ice                             | Min:+0.000000e+00 Max:+1.355253e-20 RMS:+8.911311e-24
15010   0: cloud_liquid_water                           | Min:+0.000000e+00 Max:+3.720030e-20 RMS:+1.315073e-22
15011   0: ozone_mass_mixing_ratio                      | Min:+0.000000e+00 Max:+6.621965e+31 RMS:+4.210103e+29
15012   0: ----------------------------------------------------------------------------------------------------OOPS_TRACE[0] Increment<MODEL>::print done
```

Note: Both `identity` and `gsibec` staticB gave unreasonable ozone increments

**Review by ADCollard — DISMISSED** [review]

**Review by CoryMartin-NOAA — DISMISSED** [review]

**Comment by RussTreadon-NOAA** [comment]
Please update `feature/gdas-validation-ozone` with the current head of GDASApp `develop`.  It's 75 commits behind `develop`.  Fortunately there are no conflicts so updating should go smoothly.

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA I am working on it.

**Comment by RussTreadon-NOAA** [comment]
> @RussTreadon-NOAA I am working on it.

@emilyhcliu, turns out there are a few conflicts.  I have a merged `feature/gdas-validation-ozone` ready to go.  If it helps, I can push it to the authoritative repo.  Just let me know.

**Comment by emilyhcliu** [comment]
> > @RussTreadon-NOAA I am working on it.
> 
> @emilyhcliu, turns out there are a few conflicts. I have a merged `feature/gdas-validation-ozone` ready to go. If it helps, I can push it to the authoritative repo. Just let me know.

@RussTreadon-NOAA Yes, that would be really helpful. I was just scratching my head and trying to figure out how to resolve the conflict caused by the file being removed from the development but modified in the HEAD.

```
CONFLICT (modify/delete): parm/atm/obs/config/conv_ps.yaml deleted in develop and modified in HEAD. Version HEAD of parm/atm/obs/config/conv_ps.yaml left in tree
```

Please go ahead and push your merged version for the branch.  Many thanks....

**Comment by RussTreadon-NOAA** [comment]
**NOTE:** We no longer want to merge gdas-validation branches into `feature/gdas-validation`.  We should merge gdas-validation branches into `develop`.  [`feature/gdas-validation`](https://github.com/NOAA-EMC/GDASApp/tree/feature/gdas-validation) is no longer maintained. As of 3/19/2024 it is 75 commits behind the head of the authoritative [`develop`](https://github.com/NOAA-EMC/GDASApp/tree/develop).

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , the authoritative `develop` has been merged into `feature/gdas-validation-ozone`.  Done at adc025c.   I can't promise that the merged ozone yaml templates in `parm/atm/obs/config`  will work right out of the box.

**Comment by RussTreadon-NOAA** [comment]
As noted [above](https://github.com/NOAA-EMC/GDASApp/pull/827#issuecomment-2007507339), this PR needs to be **closed** and a **new** PR opened to merge `feature/gdas-validaiton-ozone` into `develop`.  

As is, this PR merges 425 files into `feature/gdas-validation`.  This reason for this is that `feature/gdas-validation` is 75 commits behind `develop`.  A sample PR of `feature/gdas-validation-ozone` into `develop` only changes 15 files.

**Comment by emilyhcliu** [comment]
> As noted [above](https://github.com/NOAA-EMC/GDASApp/pull/827#issuecomment-2007507339), this PR needs to be **closed** and a **new** PR opened to merge `feature/gdas-validaiton-ozone` into `develop`.
> 
> As is, this PR merges 425 files into `feature/gdas-validation`. This reason for this is that `feature/gdas-validation` is 75 commits behind `develop`. A sample PR of `feature/gdas-validation-ozone` into `develop` only changes 15 files.

@RussTreadon-NOAA Thanks for merging the develop into feature/gdas-validation-ozone.  I changed the base from `feature/gdas-validation` to `develop`.   The number of files changed drops to 15.  I will keep this PR and validate the yaml files again with the merged branch.

**Comment by emilyhcliu** [comment]
After examining the merged files for ozone. Only  `ompstc` yaml needs to remove the j2 file and then modify the original one for jinja template.  
There are three types:
- omi_aura 
- ompsnp_npp
- ompstc_npp   ---- remove ompstc8_npp.yaml.j2, update the ompstc_npp.yaml for jinja format, and rename to ompstc_npp.yaml.j2

Re-evaulate the end-to-end process for ozone with the latest JEDI-T2O/gdas-validation ([PR #113](https://github.com/NOAA-EMC/JEDI-T2O/pull/113))

**Comment by emilyhcliu** [comment]
First.  Add the latest GSI QC flowchart for ozone
GSI-ozone-flowchart pptx

**Comment by emilyhcliu** [comment]
Re-validation:
 - [x] ompsnp_npp --- comparable to [previous results](https://github.com/NOAA-EMC/GDASApp/pull/827#issuecomment-1872587337)  
 - [x] ompstc_npp --- comparable to [previous results](https://github.com/NOAA-EMC/GDASApp/pull/827#issuecomment-1872584467)
- [x] omi_aura --- comparable to [previous results](https://github.com/NOAA-EMC/GDASApp/pull/827#issuecomment-1872585177)

Notes for ompsnp_npp.  The obs error adjusted in gfs.v16.3.9 updates:
```
Author: RussTreadon-NOAA <26926959+RussTreadon-NOAA@users.noreply.github.com>
Date:   Tue Sep 12 14:58:49 2023 -0400

    gfs.v16.3.9 updates to global_convinfo.txt and global_ozinfo.txt (#10)
    
    * toggle usage flag to assimilate PlanetIQ GPSRO
    * toggle usage flag to assimilate NOAA-20 OMPS (Ozone Mapping and Profiler Suite)
    * adjust OMPS observation errors
  ```

The updated obs errors from gfs.v16.3.9 are also included in the yaml files for future update.

**Comment by emilyhcliu** [comment]
To-do list:
- [x] add updated obs errors for OMPSNP_NPP from gfs.v16.3.9 for future update.  
- [x] add error handling for ozone converters.  
Done!

**Comment by emilyhcliu** [comment]
### Original Flowchart
GSI-ozone-flowchart
### Updated Flowchart (The order of thinning is changed)
GSI-ozone-flowchart pptx
### Summary:
 
 - Error handlings are added in the ozone converters for missing input BUFR file or subsets
 - Adjust the order of data thinning in the stream of data filtering (the order impact results greatly)
 - The phase-1 test and end-to-end test results are checked with GSI.  Results are comparable between GSI and JEDI (see previous comments in this PR for test results and plots below)
- Two observation operators for retrieved ozone are tested - `ColumnRetrieval` (JCSDA developed) and `AtmVertInterLay` (EMC specific) 
    - Two **forward** operator results are comparable
    - However, there are problems with the **TL/AD model** from `AtmVertinterLay`, which caused large increments in the end-to-end test (see increments below)
    - JCSDA is going to remove `AtmVertinterLay` and only keep `ColumnRetrieval` in UFO (because `ColumnRetrieval` has more general and broader applications for tracers)
    - Therefore, the `ColumnRetrieval` is used for our ozone assimilation.
    - The converter, yaml files for testing (phase 1 test), and config (phase 2 end-to-end test) are ready!!

Here are the results of the increments from `ColumnRetrieval`:
```
0: ----------------------------------------------------------------------------------------------------
  0: Increment print | number of fields = 8 | cube sphere face size: C768
  0: eastward_wind                                | Min:-3.907985e-14 Max:+3.907985e-14 RMS:+5.241827e-17
  0: northward_wind                               | Min:-4.396483e-14 Max:+4.174439e-14 RMS:+5.732950e-17
  0: air_temperature                              | Min:-3.240075e-12 Max:+3.154810e-12 RMS:+1.119756e-15
  0: surface_pressure                             | Min:+0.000000e+00 Max:+0.000000e+00 RMS:+0.000000e+00
  0: specific_humidity                            | Min:-2.153242e-08 Max:+2.684943e-08 RMS:+8.244934e-12
  0: cloud_liquid_ice                             | Min:+0.000000e+00 Max:+1.618770e-20 RMS:+1.293217e-23
  0: cloud_liquid_water                           | Min:+0.000000e+00 Max:+1.474788e-19 RMS:+2.167418e-22
  0: ozone_mass_mixing_ratio                      | Min:-1.760182e-07 Max:+1.210675e-07 RMS:+8.044355e-10
  0: ----------------------------------------------------------------------------------------------------
```
Here are the increments from `AtmVertinterLay`: (large ozone increments)
```
0: ----------------------------------------------------------------------------------------------------
  0: Increment print | number of fields = 8 | cube sphere face size: C768
  0: eastward_wind                                | Min:-2.328804e-12 Max:+2.367884e-12 RMS:+3.127267e-15
  0: northward_wind                               | Min:-2.625011e-12 Max:+2.483347e-12 RMS:+3.413966e-15
  0: air_temperature                              | Min:-1.926708e-10 Max:+1.875833e-10 RMS:+6.634194e-14
  0: surface_pressure                             | Min:+0.000000e+00 Max:+0.000000e+00 RMS:+0.000000e+00
  0: specific_humidity                            | Min:-1.281455e-06 Max:+1.597886e-06 RMS:+4.893025e-10
  0: cloud_liquid_ice                             | Min:+0.000000e+00 Max:+1.618770e-20 RMS:+1.293217e-23
  0: cloud_liquid_water                           | Min:+0.000000e+00 Max:+1.474788e-19 RMS:+2.167418e-22
  0: ozone_mass_mixing_ratio                      | Min:-2.622343e-06 Max:+2.011652e+34 RMS:+6.550479e+32
  0: ----------------------------------------------------------------------------------------------------
```

JEDI Observer End-to-End Test Documentation
JEDI Observer End-to-End Test Documentation (1)
JEDI Observer End-to-End Test Documentation (2)

tagging @CoryMartin-NOAA @RussTreadon-NOAA @ADCollard @azadeh-gh @xincjin-NOAA for review!!
Thanks a lot!

**Review by ADCollard — APPROVED** [review]
Looks good!  Nice job.  you deserve a raise!

**Review by azadeh-gh — APPROVED** [review]

**Pull request merged**
