### PR TITLE
use role.jedipara for hera ci

### LINKED ISSUE #1172: Switch automated CI to role.jedipara on Hera
One of the changes outlined in #1150 is to run automated CI from role accounts instead of individual user accounts.  This issue is opened to move Hera automated CI to role.jedipara.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
One task in #1150 is to move automated CI to role accounts.  This PR moves Hera CI to role.jedipara.

Fixes #1172

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , I discovered something you know.  `ci/driver.sh` doesn't work if the PR points at a fork.   Script `ci/driver.sh` sets 
```
   repo_url="https://github.com/NOAA-EMC/GDASApp.git"
``` 
and executes
```
git clone --recursive $repo_url
```

My attempt to run hera-RT for this PR from role.jedipara failed with
```
https://github.com/NOAA-EMC/GDASApp/pull/1173
Processing Pull Request #1173
Cloning into 'GDASApp'...
fatal: unable to access 'https://github.com/NOAA-EMC/GDASApp.git/': SSL connection timeout
/scratch1/NCEPDEV/da/role.jedipara/CI/GDASApp/repo/ci/driver.sh: line 68: cd: GDASApp: No such file or directory
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
Is there some way we can extract the source repo from the github PR?

**Comment by CoryMartin-NOAA** [comment]
@RussTreadon-NOAA we need to make the following lines more intelligent:
https://github.com/NOAA-EMC/GDASApp/blob/f5bbec0077bb5c8cbfdb0d03caa35e2aa016d243/ci/gw_driver.sh#L53-L59

If we run `gh pr list --label "$CI_LABEL" --state "open" ` but change our `awk` command, we can get the branch/fork information

for example:
```
ID     TITLE                                                               BRANCH                         CREATED AT          
#1173  use role.jedipara for hera ci                                       RussTreadon-NOAA:feature/ci    about 50 minutes ago
#1169  Point the CI to the dev/gdasapp global workflow branch              feature/devgdasapp             about 1 day ago
#1146  Bring jcb into GDASapp and use version of jcb not using submodules  feature/move_jcb               about 8 days ago
#1145  Improving vrfy plots and Fixing blank plots                         feature/vrfy-plot              about 8 days ago
#1144  Updates to GDASapp to account for new JCB policies                  feature/rename_atm             about 9 days ago
#1133  Use spack-stack python on Hercules                                  feature/hercules-modules       about 15 days ago
#1042  Try to save a stable build with symlink                             feature/stable-symlink         about 1 month ago
#754   Create a converter for amusa from bufr to ioda                      feature/gdas-validation_amsua  about 6 months ago
```

We can grab the branch name and do a split on the colon to get the fork name

**Comment by CoryMartin-NOAA** [comment]
although it may be simpler to run it through a python script to extract the information rather than writing a complicated awk line (but I'm no awk expert)

**Comment by RussTreadon-NOAA** [comment]
The trick with awk or python is how to deal with a variable number of blanks in the title section of the list.  We want to skip over the title and extract the branch.

**Comment by RussTreadon-NOAA** [comment]
I think there is a way with gh options to extract the information we want.  Let me experiment tomorrow.

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA, seems got ci from a fork to work!

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , where can we find `jq`(JSON processor) on Hera?  I see `jq` in `/scratch1/NCEPDEV/da/Cory.R.Martin/CI/GDASApp/repo/ci/gw_driver.sh`.

**Comment by RussTreadon-NOAA** [comment]
For the time being, I followed `jq` [installation instructions](https://jqlang.github.io/jq) found online.  `jq` is in `~role.jedipara/bin`

**Comment by CoryMartin-NOAA** [comment]
@guillaumevernieres added this, he had me checkout his branch for testing something. @guillaumevernieres can you elaborate on what this is for?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres added this, he had me checkout his branch for testing something. @guillaumevernieres can you elaborate on what this is for?

Parsing json files ... but I clearly didn't test this properly! I'll switch to using something more standard. Can you revert what you cloned into "repo" @CoryMartin-NOAA ? Whatever I did does not work yet.

**Comment by guillaumevernieres** [comment]
I'm reading the comments backwards ... Did you get that `gw_driver.sh` script to do what we want @RussTreadon-NOAA ?

**Comment by CoryMartin-NOAA** [comment]
I reverted to develop, please let me know if I need to go back to a branch

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , this PR is ready for review.  `feature/devgdasapp` has been merged into `RussTreadon-NOAA:feature/ci`

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres , this PR is ready for merger into GDASApp `develop`.   If you can review & approve, I can merge.

**Review by guillaumevernieres — APPROVED** [review]
Looks good, thanks @RussTreadon-NOAA

**Comment by guillaumevernieres** [comment]
@RussTreadon-NOAA , the only issue I see is that the README won't match what the ci is doing until we switch on the jedi para cron.

**Pull request merged**
